### ISSUE TITLE
Feature request: Permit .json as a file extension

### ISSUE THREAD

**Issue by scmbradley** [bitburner-official/bitburner-src#1002]
It would be useful to write out JSON objects into a file with the `.json` file extension, rather than just using `.txt` or `.js`. This would permit proper display of the contents in the script editor, and give a better indication that the file contains JSON when listing files with `ls`.

**Comment by d0sboots** [comment]
60% workaround: json is a subset of js, so you can use `.js` to get proper syntax highlighting. You need to use different names (or a different directory) to distinguish them from scripts, though.

**Comment by LJNeon** [comment]
This was completed by #1137.
