### ISSUE TITLE
"Total production since last Augment Installation" value after offline period

### ISSUE THREAD

**Issue by arnauddub** [bitburner-official/bitburner-src#1003]
The value of "Total production since last Augment Installation" in the Active Scripts submenu displays a value which is far superior to the amount of money in "home" or in the Stats submenu after a long offline period. 

- Version of the game, e.g. Bitburner v2.5.2 (c6141f2ad)

**Comment by d0sboots** [comment]
Without a save game or steps to reproduce, there's no good way to look in to this one.

**Comment by arnauddub** [comment]
Here's a save from BN4.1 where after 2 days offline the value in the Active Scripts is ca. 8x the actual value on home/Stats.

[bitburnerSave_1704221313_BN4x1.json](https://github.com/bitburner-official/bitburner-src/files/13813067/bitburnerSave_1704221313_BN4x1.json)

Not sure what specific steps tpo reproduce should be.

**Comment by Snarling** [comment]
Fixed by #1025
