### ISSUE TITLE
Game sometime freezes when passing argument to script

### ISSUE THREAD

**Issue by ccheath** [bitburner-official/bitburner-src#1005]
I've got a script to cashout my hacknet hashes for money, and recently added the ability to change it to generate coding contracts by passing an argument. This will almost never work just after a reset (from installing augmentations) but will work just fine after some amount of time.  I added a tail at the very beginning of the script to see what any output might be showing but that doesn't even pop up.  All I get is the "running script with 1 thread pid 1 and args [x]" at the terminal and then the game freezes.

(save, script, and version below)

TYIA

[bitburnerSave_1704036619_BN13x1.json](https://github.com/bitburner-official/bitburner-src/files/13801541/bitburnerSave_1704036619_BN13x1.json)

```
/** @param {NS} ns */
export async function main(ns) {

	ns.tail();
	ns.disableLog("sleep");

	let hnUpgrade = "Sell for Money";
	let sleepTime = 2000;

	if (ns.args[0]) {
		hnUpgrade = "Generate Coding Contract"
		sleepTime = 15000;
	}

	let hnUpgradeCost = ns.hacknet.hashCost(hnUpgrade)


	let myHashes = ns.hacknet.numHashes();

	while (true) {
		//ns.clearLog();
		myHashes = ns.hacknet.numHashes();
		hnUpgradeCost = ns.hacknet.hashCost(hnUpgrade);
		if (hnUpgradeCost > 100000000000) {
			ns.print('EXITING... cost of upgrading our hacknet is over ', abbreviateNumber(Math.round(100000000000)))
			ns.exit()
		}
		ns.print('Current Hashes: ', abbreviateNumber(Math.round(myHashes)), ' - upgrade cost: ', abbreviateNumber(Math.round(hnUpgradeCost)));

		while (hnUpgradeCost > ns.hacknet.hashCapacity()) {
			upgradeHasCap(ns);
		}

		if (myHashes >= hnUpgradeCost) {

			ns.hacknet.spendHashes(hnUpgrade);
			ns.print(" --> Just spent ", hnUpgradeCost, " on ", hnUpgrade);
			await ns.sleep(sleepTime);

		}
		else {
			await ns.sleep(sleepTime);
		}
	}
}

/** @param {number} value */
function abbreviateNumber(value) {
	if (value < 1000) {
		return value.toString();
	}

	const suffixes = ["", "k", "M", "B", "T"];
	const suffixNum = Math.floor(("" + value).length / 3);
	let shortValue = '';

	// Adjust the precision based on the magnitude of the number
	let precision = (suffixNum >= 2) ? 3 : 1;

	shortValue = (suffixNum !== 0 ? (value / Math.pow(1000, suffixNum)) : value).toFixed(precision);
	const dotLessShortValue = (shortValue + '').replace(/(\.[0-9]+?)0+$/, '$1');

	return dotLessShortValue + suffixes[suffixNum];
}

/** @param {NS} ns */
function upgradeHasCap(ns) {
	const nodes = ns.hacknet.numNodes();
	let lowestIndex = 0;
	let lowestLevel = Number.MAX_SAFE_INTEGER;
	for (let i = 1; i < nodes; i++) {
		if (ns.hacknet.getNodeStats(i).hashCapacity < lowestLevel) {
			lowestIndex = i;
			lowestLevel = ns.hacknet.getNodeStats(i).hashCapacity;
		}
	}
	let success = ns.hacknet.upgradeCache(lowestIndex, 1)
	if (success) {
		ns.print("Upgraded cache level on hacknet node: ", lowestIndex)
	}

}
```

`Version:  2.5.1 (0c2997d32)`

**Comment by d0sboots** [comment]
At the beginning of an install, you have no hashnet nodes. This causes an infinite loop because `upgradeHashCap` won't do anything.

**Comment by ccheath** [comment]
I actually get an error if I do not purchase hacknet nodes before running the script (should have mentioned that). 
The crash happens if I run the script after purchasing hacknet nodes.

**Comment by cigarmemr** [comment]
Tried the script and confirmed that.
What causes freezing is that right after a soft reset (and have purchased hn-servers), the money you have is insufficient to upgrade the cache. This traps the `upgradeHasCap()` in an infinite loop. It tries to upgrade cache, fails, on and on. Once the money is enough the script will continue as usual.
To solve this, either to check whether you can afford the cache upgrade before actually upgrading, or to `sleep()` some interval inside the inner while loop.

**Comment by ccheath** [comment]
thank you very much, I will adjust the script to check for available funds before trying to upgrade.
