### ISSUE TITLE
ns.formulas.work.companyGains() reports the reputation rates in the wrong order for the "Security" field.

### ISSUE THREAD

**Issue by HiEv** [bitburner-official/bitburner-src#1008]
I'm running Bitburner v2.5.2 - Steam edition - Windows 10.

The calculations for all other fields seem fine, but for some reason the calculations of `ns.formulas.work.companyGains()` for the "Security" field are not in ascending order.  I took a peek at the source code, but I don't see why it's happening.

Try running this code:
```
/** @param {NS} ns */
export async function main(ns) {
	function sizeTextLeading (txt, len) {
		txt = "" + txt;
		if (len > txt.length) {
			txt = " ".repeat(len - txt.length) + txt;
		}
		return txt;
	}

	const ansiTxtCyan	 = "\u001b[36m";
	const ansiTxtDefault = "\u001b[39m";
	const ansiTxtYellow	 = "\u001b[33m";
	const comp = "Carmichael Security";
	let positions = ns.singularity.getCompanyPositions(comp);  // Gets an array of potential job positions.
	ns.tprint("\nCompany: " + ansiTxtCyan + comp + ansiTxtDefault);
	for (let position of positions) {
		let posInfo = ns.singularity.getCompanyPositionInfo(comp, position);
		let compRepRate = ns.formulas.work.companyGains(ns.getPlayer(), comp, position, ns.singularity.getCompanyFavor(comp)).reputation * 5;  // Company reputation gained/sec.
		let salary = posInfo.salary.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
		compRepRate = compRepRate.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
		ns.tprint("    Salary:  " + ansiTxtYellow + "$" + sizeTextLeading(salary, 8) + "/sec" + ansiTxtDefault
			+ "  Rep/sec: " + ansiTxtYellow + sizeTextLeading(compRepRate, 8) + ansiTxtDefault
			+ "  Field: " + ansiTxtYellow + posInfo.field + ansiTxtDefault
			+ "  Position: " + ansiTxtYellow + position);
	}
}
```

You'll get output that looks something like this:
```
Company: Carmichael Security
    Salary:  $   39.60/sec  Rep/sec:   406.61  Field: Software  Position: Software Engineering Intern
    Salary:  $   96.00/sec  Rep/sec:   485.61  Field: Software  Position: Junior Software Engineer
    Salary:  $  198.00/sec  Rep/sec:   543.06  Field: Software  Position: Senior Software Engineer
    Salary:  $  600.00/sec  Rep/sec:   593.88  Field: Software  Position: Lead Software Developer
    Salary:  $  960.00/sec  Rep/sec:   630.06  Field: Software  Position: Head of Software
    Salary:  $1,980.00/sec  Rep/sec:   630.06  Field: Software  Position: Head of Engineering
    Salary:  $2,772.00/sec  Rep/sec:   655.33  Field: Software  Position: Vice President of Technology
    Salary:  $3,168.00/sec  Rep/sec:   708.49  Field: Software  Position: Chief Technology Officer
    Salary:  $   31.20/sec  Rep/sec:   421.53  Field: IT  Position: IT Intern
    Salary:  $   79.20/sec  Rep/sec:   485.61  Field: IT  Position: IT Analyst
    Salary:  $  158.40/sec  Rep/sec:   543.06  Field: IT  Position: IT Manager
    Salary:  $  492.00/sec  Rep/sec:   580.90  Field: IT  Position: Systems Administrator
    Salary:  $  145.20/sec  Rep/sec:   525.11  Field: Security Engineer  Position: Security Engineer
    Salary:  $  145.20/sec  Rep/sec:   525.11  Field: Network Engineer  Position: Network Engineer
    Salary:  $  492.00/sec  Rep/sec:   543.06  Field: Network Engineer  Position: Network Administrator
    Salary:  $   60.00/sec  Rep/sec: 1,265.20  Field: Security  Position: Security Guard
    Salary:  $  234.00/sec  Rep/sec: 1,404.85  Field: Security  Position: Security Officer
    Salary:  $  792.00/sec  Rep/sec: 1,250.60  Field: Security  Position: Security Supervisor
    Salary:  $1,584.00/sec  Rep/sec: 1,394.53  Field: Security  Position: Head of Security
    Salary:  $  396.00/sec  Rep/sec: 1,057.13  Field: Agent  Position: Field Agent
    Salary:  $1,188.00/sec  Rep/sec: 1,329.35  Field: Agent  Position: Secret Agent
    Salary:  $2,400.00/sec  Rep/sec: 1,585.00  Field: Agent  Position: Special Operative
    Salary:  $   79.20/sec  Rep/sec:   429.53  Field: Software Consultant  Position: Software Consultant
    Salary:  $  158.40/sec  Rep/sec:   429.53  Field: Software Consultant  Position: Senior Software Consultant
```
Note that the reputation rates for the "Security" field go up in this order:
* 1,265.20 -> 1,404.85 -> 1,250.60 -> 1,394.53

I'd expect an order more like this:
* 1,250.60 -> 1,265.20 -> 1,394.53 -> 1,404.85

All of the other fields show the reputation calculations in ascending order.  Any ideas what's wrong with security?

**Comment by HiEv** [comment]
I should note that at least some of the formula's company reputation gain rates for security also don't match up with the _actual_ company reputation gain rates, though I haven't tested all of them.

**Comment by cigarmemr** [comment]
It is possible for higher positions rewarding less reputation than lower ones, not limited in the field of Security.

The reputation gain is affected by various skill levels such as:
- Software (and other technology related) positions weights Hacking skill the most
- Business jobs consider Charisma skill to be the most important

However, even for the positions of the same field, the weights of each skill may NOT be the same. This can be obtained from the [source code](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Company/data/CompanyPositionsMetadata.ts) as `XXXXEffectiveness` properties for each position.

Note that for the field Security, the weights change from (Hacking : Combat : Charisma) 
- 5:20:15 (Guard) to 
- 10:20:10 (Officer) and finally 
- 10:15:30 (both Supervisor and Head)

If your character is way too powerful in Combat while poor in Charisma, it is possible that Supervisor earns less reputation than Officer.

Outside of the code, you may think of it like this: As a Supervisor or Head of Security, you are more likely to assemble and order some tough guys fighting for you, rather than using your own fists. So personal Charisma counts more than ever lol.

**Comment by HiEv** [comment]
Sounds reasonable.
