### ISSUE TITLE
Feature request: Obtain estimated success chance for sleeves performing Bladeburner Contracts in NS scripts

### ISSUE THREAD

**Issue by cigarmemr** [bitburner-official/bitburner-src#1009]
As far as I've discovered, there is no way to obtain success chance estimation for sleeves performing Bladeburner Contracts. This renders some critical judgement like "Order the sleeve to stop while success chance drops too low" impossible.

Maybe an optional argument in `getActionEstimatedSuccessChance()` is good. Leaving it unset to obtain success chance for player while passing an index for the corresponding sleeve.

**Comment by gmcew** [comment]
Closed by #1428
