### ISSUE TITLE
creating a program while owning at the same time 

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#101]
[MrPeanutbutterz]
# DELETE THIS AFTER READING

# include (where relevant)

Regarding programs (.exe) 

At this moment the game shows that i'm creating burteSSH en FTPCrack while also owning the program 

BruteSSH.exe            BruteSSH.exe-99.89%-INC FTPCrack.exe            FTPCrack.exe-78.83%-INC 

- [ x] Save file
- [ x] Minimal scripts to reproduce the issue
- [ x] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v2.0.2 (3067703c)

**Comments From Original Issue**

[DandyV3000]
> hey letting you know that I was able to delete the copy,
> ls to see file name at home
> them rm [filename]
> for me it was 'BruteSSH.exe-6.18%-INC'
> hope this helps
> ![Capture2](https://user-images.githubusercontent.com/113217646/189459267-d7d15bae-a80c-4b90-93da-cb1592ebc354.PNG)
> ![Capture](https://user-images.githubusercontent.com/113217646/189459269-bddb952f-d1bc-4c6d-a3e6-e2be611e7009.PNG)
>

**Comment by alex-Symbroson** [comment]
Having the same issue. When starting to create a program the progress initially doesn't show up. and I can start the creation process a second time. After that the progress of the **first** instance shows up (but isn't progressing). Instead the second creation progresses in the background.

Further attempts to create the program switch out those two instances until one of them eventually finishes.
After that the completed program and the partly finished one (with an -INC extension) are left in the filesystem as shown in TheMas3212's screenshot

**Comment by Snarling** [comment]
Looks like same bug as #346 , closing this one.
