### ISSUE TITLE
Running scripts not properly cleared on soft reset/install augs

### ISSUE THREAD

**Issue by Kline-** [bitburner-official/bitburner-src#1033]
Version: Bitburner v2.5.2 (c6141f2ad)

This seems to occur more frequently using singularity.installAugmentations() than installing manually, but I've encountered this issue doing either. After the soft reset, scripts I had set to run either via the callback or from an autoexec setup in the settings would fail to run with no error messages, just "script killed". Reloading the page to flush everything out of memory resolves the issue 100% of the time.

I added some checks to prevent duplicate copies of a few scripts from running and ns.isRunning() is telling me a duplicate is already running while ps in the terminal, ns.ps() in a script, and the active running scripts in the GUI window report nothing running at all.

![image](https://github.com/bitburner-official/bitburner-src/assets/1126350/68e56be7-8e50-4d7e-9afa-076416c2d43b)

![image](https://github.com/bitburner-official/bitburner-src/assets/1126350/cd1e0b60-ed00-4ff9-bbea-adb464a74853)

[bitburnerSave_1705147736_BN12x8.json](https://github.com/bitburner-official/bitburner-src/files/13927922/bitburnerSave_1705147736_BN12x8.json)

Steps to reproduce with the attached save file:
- Either let sys.js run on start or start it manually if loading with startup scripts disabled. It should fire off some child scripts then start running normally.
- Run reset.js to soft reset with a callback to sys.js
- sys.js will start and even fire off a few child scripts then unexpectedly die.

**Comment by cigarmemr** [comment]
In the script sys.js the global object `world_state` is shared between instances of each running.

Note L358~L361 aka the function `initSleeves()` will push additional `cfg.SleeveNum` sleeves into the property `sleeves`:

```javascript
function initSleeves(ns) {
  for (let i = 0; i < cfg.SleeveNum; i++)
    world_state.sleeves.push(new Sleeve(ns, i));
}
```
However the `world_state.sleeves` already contains data of sleeves in previous running. After reset.js and another sys.js instance is raised up, the function `initSleeves()` is trying to push another `cfg.SleeveNum` sleeves into `world_state.sleeves`, resulting it contains `Sleeve` objects more than you actually own.

This renders some sleeve-related functions to fail as they are being applied to non-existing sleeves, thus terminates the sys.js.

Use a temporary array in `initSleeves()` to collect sleeves and assign it to `world_state.sleeves` should fix this problem:

```javascript
function initSleeves(ns) {
  const sleeves = []
  for (let i = 0; i < cfg.SleeveNum; i++)
    sleeves.push(new Sleeve(ns, i));
  world_state.sleeves = sleeves
}
```

Tested locally and observed sys.js will not be killed after reset.js is run. You may have to confirm that other features held by sys.js works normally or not.

**Comment by cigarmemr** [comment]
Ah I myself rely on ASI a lot, you may add semicolons to fit your coding style.

**Comment by Kline-** [comment]
Thanks, I guess I assumed that on soft reset everything would be cleared in
the game state as far as running scripts.

I didn't realize globals within a script would hold their state between
resets, but that certainly explains the issue I was seeing.
