### ISSUE TITLE
Cannot use input fields after closing alert box created by the game. 

### ISSUE THREAD

**Issue by Syhmac** [bitburner-official/bitburner-src#1047]
After using alert() function in my script to notify me about somethin I can't use input fields after closing alert box. 

Steps to reproduce:
1. Create a new script.
2. Use alert() function
3. Use ns.exit() function (I don't know if this is relevant but I have this in the line after alert)

Version: 2.5.2 (c6141f2ad) Steam
Platform: Windows 11

**Comment by Caldwell-74** [comment]
did you try/use ns.alert ?

**Comment by Syhmac** [comment]
`ns.alert()` works fine, thanks. I managed to overcome this by using NotificationAPI anyway. I haven't seen that there is `ns.alert()`. Documentation in game is really hard to navigate and find information in. I don't think I have even found anything about NS. Maybe a good idea would be to include a link to NS docs on the main page of documentation in game.

**Comment by Caldwell-74** [comment]
in the script editor on the bottom row is a link to the NS documentation

**Comment by Syhmac** [comment]
Oh! There it is. I was looking for it in Documentation tab. Confusing...

**Comment by d0sboots** [comment]
We should add a link in the docs tab, I've failed to find it there on several occasions too.

**Comment by Caldwell-74** [comment]
yep thats true
and maybe remake the non spoiler function list we had on the bitburner rtd (not beta and not official)
