### ISSUE TITLE
Weird way to copy scripts between servers

### ISSUE THREAD

**Issue by Syhmac** [bitburner-official/bitburner-src#1051]
I don't know if it's supposed to work that way, I probably know the reason why it's happening. You can copy scripts between servers in an odd way following those steps:

## Steps to reproduce
1. Create script on server-1
2. Save it
3. Run command `ls` on server-1
4. Connect with a server-2
5. Click on a script from `ls` command
6. It will open file in editor but on the server-2
7. You can save file now and it's copied

## Possible reason
Clicking a file probably runs `nano %filename%` so it runs on currently connected server.

## Game version
2.5.2 (https://github.com/bitburner-official/bitburner-src/commit/c6141f2adfe1e8b12015b8c19db21fb3d3db5a6c) Steam edition

**Comment by LJNeon** [comment]
Yea this seems like a bug, it probably uses the current server rather than the server that you were connected to when running the command.
