### ISSUE TITLE
Suggestion: Expose BB skill properties to BB API

### ISSUE THREAD

**Issue by MaWo2** [bitburner-official/bitburner-src#1071]
I want to max out the number of BB skill upgrades that can be purchased from a given (current) amount of skill points.

This can be done by checking increasing numbers with `ns.bladeburner.getSkillUpgradeCost(skillName,count)`. However, this is basically "trial and error" and not very efficient for large numbers (e.g. Hyperdrive levels in the millions or more).

I checked the code for the `getSkillUpgradeCost` function: You "only" need to solve a pq-formula to get the number of upgrades.
Unfortunately, it requires four variables, of which two are not available for scripting.
- BladeburnerSkillCost --> exposed by Bitnode multipliers
- Current Skill Level --> exposed by bladeburner API
- the skill's BaseCost --> not exposed
- the skill's Cost increase --> not exposed

Would it be possible to expose the two properties to the BB API?

**Comment by d0sboots** [comment]
Although I don't disagree that those could be good to add, if you know the formula can't you figure out the constants with a couple of calls to `getSkillUpgradeCost`?

**Comment by MaWo2** [comment]
I tried that. However, there are rounding errors.
With my Hyperdrive at a level of more than 16 millions, I get quite close to the hidden value for the cost increase. Rounding the base cost would produce a correct value, too.
But trying this on e.g. Reaper (level only 1k) produces values that are too far off. Especially the base cost value.
