### ISSUE TITLE
NetscriptDefinitions.d.ts is not ambient

### ISSUE THREAD

**Issue by jshepler** [bitburner-official/bitburner-src#1078]
Because there are some interfaces/types marked with `export`, the file is considered a module instead of being ambient. This requires us to import this in every script that uses anything declared in it. If it was ambient, we wouldn't need to `import {NS} from "@ns";`, for example (as well as not needing that path in tsconfig.json).

Setting aside the inconsistency of having some interfaces/types with the export and some without, I don't understand why it was done this way. So I edited my copy to remove all the export keywords (i.e. `export interface foo` becomes `interface foo`) and everything seems to work fine without needing to import that type file in any of my scripts.

Am I missing something?

**Comment by LJNeon** [comment]
I could be wrong but my immediate assumption is that it was done that way to avoid polluting the global namespace. There are a LOT of types in that file.

**Comment by jshepler** [comment]
> I could be wrong but my immediate assumption is that it was done that way to avoid polluting the global namespace. There are a LOT of types in that file.

There are no actual objects in there - just declarations, which are only used for type checking, intellisense, autocomplete, etc. i.e. nothing is added to the global namespace.

**Comment by LJNeon** [comment]
If you want to be able to just use them without importing them that requires adding them to the global namespace. That's what you're doing by making it ambient isn't it? What I'm saying is that I think the reason you want that change is the same reason it wasn't done that way.

**Comment by jshepler** [comment]
I get what you're saying. but it's not like this is a general-purpose library or anything like that. It's only for this game. Anything else someone wants to use will most likely not have any type name conflicts with NS types.

The inconsistencies that I mentioned raises enough doubt of intent that I wanted to ask.

I'm fine making the d.ts file ambient for myself, so doesn't really matter to me, but I wanted to raise the question. I'm curious if it was intentional or not.

**Comment by LJNeon** [comment]
The other issue is that the definitions are used internally in bitburner's source code as well, so it would be polluting that global namespace too.

**Comment by d0sboots** [comment]
That's probably the main reason

**Comment by jshepler** [comment]
If that was the intent, then using a namespace would be the way to go. Technically, those types are in the global **namespace**, but just aren't ambient. Those are two different things. 

By wrapping the types in an actual namespace, they would become ambient, but not in the global **namespace**. As long as there's not a top-level export (or import), it'll be ambient.

e.g.:
```ts
declare namespace Netscript {
    interface NS { }
    interface Person { }
    interface Player extends Person { }
}
```
Being ambient is not the same as being in the global namespace, though objects can be both. Objects attached to the global object (e.g. `window` in browser environments) are both global and ambient.

**Comment by jshepler** [comment]
Closing as I wasn't actually asking for it to be changed as it would be a breaking change. I wanted the raise the question in case I was missing something and it seems I didn't.
