### ISSUE TITLE
Script for running my hack.js on every server in the game crashes for no reason. 

### ISSUE THREAD

**Issue by Juicyu** [bitburner-official/bitburner-src#1080]
On homeserver go to folder scripts and run "spreadHacksV2.js ../hack.js"

The script is meant to run my hack.js on every server in the game, except home servers, if root access was gained and the script deployed to the server.
The Game chrashes when using the script but I can't see why.

[bitburnerSave_1707060044_BN1x1.json](https://github.com/bitburner-official/bitburner-src/files/14211289/bitburnerSave_1707060044_BN1x1.json)

**Comment by Caldwell-74** [comment]
https://discord.gg/AafjRUNN
come to the discord for script debugging
