### ISSUE TITLE
High level BN12 can cause BB stamina penalty to be NaN

### ISSUE THREAD

**Issue by TheAimMan** [bitburner-official/bitburner-src#1096]
![image](https://github.com/bitburner-official/bitburner-src/assets/147098375/f10ca7a7-20f7-4768-8fe3-ceb6e0edeaa2)

**Comment by TheAimMan** [comment]
Is fixed by https://github.com/bitburner-official/bitburner-src/pull/1093

**Comment by catloversg** [comment]
@d0sboots We can close this.
