### ISSUE TITLE
Go win(?) streak bonus on two losses

### ISSUE THREAD

**Issue by enderandrew** [bitburner-official/bitburner-src#1109]
You get 1 favor bonus for winning two games of Go in a row. That makes sense. It shows me a message that I receive +1 win streak bonus when I lose two games in a row. My faction favor does not seem to actually increase from two messages. It is just the message that is faulty.

[bitburnerSave_1708322281_BN1x1.json](https://github.com/bitburner-official/bitburner-src/files/14327011/bitburnerSave_1708322281_BN1x1.json)
- [ ] Save file I can attach
- [ ] Minimal scripts to reproduce the issue - N/A
- [ ] Steps to reproduce - lose two games in a row at Go
- [ ] Version of the game, e.g. Bitburner v2.6.0 dev

**Comment by d0sboots** [comment]
@ficocelliguy
