### ISSUE TITLE
Game freezes when hacking faction server

### ISSUE THREAD

**Issue by Juicyu** [bitburner-official/bitburner-src#1116]
The Game crashes after hacking a faction server. I noticed this for 
    "CSEC",
    "avmnite-02h",
    "run4theh111z",
    ".",
    "I.I.I.I"
I tried to hack them with a script and as soon as I had root access, the game froze when my script tried to hack the server
[bitburnerSave_1707060044_BN1x1.json](https://github.com/bitburner-official/bitburner-src/files/14365109/bitburnerSave_1707060044_BN1x1.json)

**Comment by LJNeon** [comment]
You should join the [Discord server](https://discord.gg/TFc3hKD) for help with this kind of question, but odds are you forgot to await something in an infinite loop.

**Comment by Juicyu** [comment]
My script works perfectly when commenting out these 5 server. I will join the Discord for further investigation :)

Update:
  while(true) {
    while(minSecurityLevel < ns.getServerSecurityLevel(server)){
      ns.print("weaken...");
      await ns.weaken(server);
    }
    
//this here 
    while(maxMoney > ns.getServerMoneyAvailable(server)){
      ns.print("grow...");
      await ns.grow(server);
    }

    while(minSecurityLevel < ns.getServerSecurityLevel(server)){
      ns.print("weaken...");
      await ns.weaken(server);
    }
//and this here
    while(ns.getServerMoneyAvailable(server) > ns.getServerMaxMoney(server) *0.8){
      ns.print("hacking...")
      await ns.hack(server);
    }
  }
  
  I guess these two will cause the problem because they will never be true... You were right.

**Comment by cigarmemr** [comment]
For those "empty" servers, none of the inner while's conditions are true. In this case the outer while is looped infinitly without any `await`ing.

This may be avoided by adding a judgement based on `maxMoney === 0` to identify the "empty" servers, and refuse to hack them for money with the given script. (they are still available to hack for exp though)
