### ISSUE TITLE
Game setting suppress TIX messages does nothing.

### ISSUE THREAD

**Issue by DJshelfmushroom** [bitburner-official/bitburner-src#1122]
Bitburner current version
[Screen recording 2024-02-22 10.08.41 PM.webm](https://github.com/bitburner-official/bitburner-src/assets/67295452/b5b06f3b-bd75-4dec-9c1c-a6a98036f823)

**Comment by d0sboots** [comment]
It's hard to tell from just that video, does it *still* keep happening even after you leave it on for a while? That could also just be a lot of toasts that are backed up.

**Comment by DJshelfmushroom** [comment]
Yes, I've had it on until I turn it off to record the video, and it was still sending me toasts
