### ISSUE TITLE
Just destroyed my first BN, now some of my scripts crash when I run them.

### ISSUE THREAD

**Issue by DJshelfmushroom** [bitburner-official/bitburner-src#1123]
(watch vid)
[Screen recording 2024-02-23 4.18.25 PM.webm](https://github.com/bitburner-official/bitburner-src/assets/67295452/270ef7a7-e3a4-4451-b5ca-a4867acb47c9)
[bitburnerSave_1708734054_BN1x2.json](https://github.com/bitburner-official/bitburner-src/files/14391097/bitburnerSave_1708734054_BN1x2.json)

**Comment by DJshelfmushroom** [comment]
really the most important scripts crash.

**Comment by d0sboots** [comment]
Almost certainly your scripts are making assumptions about how things were, that are no longer true. In any case, not a game bug.

**Comment by DJshelfmushroom** [comment]
@d0sboots could you help me solve then?

**Comment by d0sboots** [comment]
I'm kind of busy, but if you join the discord there are usually people around who will help answer questions and figure out what's going wrong with your scripts.

**Comment by DJshelfmushroom** [comment]
aight thanks
