### ISSUE TITLE
FEATURE REQUEST: (NetScript) Some way to print formatted and/or interactive text without the complexity of React

### ISSUE THREAD

**Issue by User670** [bitburner-official/bitburner-src#1146]
I'm thinking of Minecraft's ["Raw JSON text format"](https://minecraft.wiki/w/Raw_JSON_text_format), where JSON data can be passed into commands or other data values to produce formatted and/or interactive text.

I'd like a function that does something similar, so that one can output more than just plain text, but without having to deal with React or hacking around the game's code.

I'm thinking of these functionalities:
- bold, italics, underlined, strike-through, colored text
- tooltip when hover mouse over
- these click actions:
  - put text into the terminal text box
  - execute a command, as if user typed that through the terminal
  - copy some text into the user's clipboard

**Comment by d0sboots** [comment]
The first part already exists, via ANSI escape codes.

**Comment by User670** [comment]
> The first part already exists, via ANSI escape codes.

Still want clickable text.

**Comment by catloversg** [comment]
I raised this problem on Discord. It seems that nobody agrees with this idea. Personally, I think this feature should be implemented by the player as a part of their UI tools.

@d0sboots Should we close this issue?

**Comment by d0sboots** [comment]
OK.
In passing, I'll say that one thing that differentiates us significantly from Minecraft (and thus Minecraft's system of IO annotations) is that MC very explicitly wanted a system that was *not* turning complete, and so they made the system significantly more complicated/expressive as a result. In contrast, BB's solution is to let you do whatever you want by writing code, and have a much more minimal API
