### ISSUE TITLE
CORPORATION: expanding office size by a non-multiple of 3 has incorrect cost

### ISSUE THREAD

**Issue by adeilt** [bitburner-official/bitburner-src#1166]
# CORPORATION: expanding office size by a non-multiple of 3 has incorrect cost

## Summary

`corporation.upgradeOfficeSize` rounds up expansion cost to the nearest multiple of 3, but does not actually increase the size accordingly.  Either the cost should not be rounded up for non-multiples of 3 or the actual increase should match the cost.

## Issue Reproduction

The (extremely quick-and-dirty) demonstration script `test.js` (source below) demonstrates the issue by creating a new division, then calling `upgradeOfficeSize` to increase the max size of the offices in three different cities by 1, 2, and 3 employees respectively:

```
[home /]> run test.js
Running script with 1 thread(s), pid 2 and args: [].
test.js: Expanded AgriTest office size in Sector-12 by 1 at a total cost of: -4.360e9
test.js: Expanded AgriTest office size in Aevum by 2 at a total cost of: -4.360e9
test.js: Expanded AgriTest office size in Ishima by 3 at a total cost of: -4.360e9
```

Note that increasing the Sector-12 office from 3->4 cost 4.36b and increasing Ishima from 3->6 also cost 4.36b.

The relevant functions that compute the costs (`UpgradeOfficeSize` in `Actions.ts` and `corporation.getOfficeSizeUpgradeCost`) haven't changed since at least #503 (2023-05-15).

<details><summary>test.js demonstration script (click to expand)</summary>

```
/** @param {NS} ns */
export async function main(ns) {
  const div = `AgriTest${ns.args[0] ?? ""}`;
  ns.corporation.expandIndustry("Agriculture", div);
  ns.corporation.expandCity(div, "Aevum");
  ns.corporation.expandCity(div, "Ishima");
  ns.corporation

  const cities = ["Z", "Sector-12", "Aevum", "Ishima"];

  for (let i=1; i<4;i++) {
    const funds_pre = ns.corporation.getCorporation().funds;
    const size_pre = ns.corporation.getOffice(div, cities[i]).size;
    ns.corporation.upgradeOfficeSize(div, cities[i], i);
    const funds_post = ns.corporation.getCorporation().funds;
    const size_post = ns.corporation.getOffice(div, cities[i]).size;
    ns.tprint(`Expanded ${div} office size in ${cities[i]} by ${size_post - size_pre} at a total cost of: ${ns.formatNumber(funds_post - funds_pre)}`);
  }
}
```
</details>

## Suggested fixes

The easiest would probably be to just use something like
```
office.size += Math.ciel(requested_size_increase / 3) * 3;
```

for the actual increase as the cost computations wouldn't need to change.

Alternately, office size increases could be made more granular with single-employee size increases supported by lower costs.  This would be more work to implement as the existing cost curve would need to be matched and the cost computations rewritten.  However, it's my preferred solution as it rewards scripters over UI corporation users by allowing finer control over office size.

~~I'm happy to work on this, but I'll leave a little while for discussion before I start.~~

I've started on this in #1179.

**Comment by d0sboots** [comment]
I agree that being able to upgrade more fine-grained seems like a useful ability. Also, it would be a chance to clean up the multiple implementations of the formula and maybe put it in formulas? (No need to actually create a user-visible formulas function for them.)

If I did my math right, the proper geometric series is `cost = officeInitialCost * (m ** office.size) * ((m ** upgrades) - 1) / (costMultiplier - 1)`, where `m = costMultiplier ** (1/3)`.

**Comment by adeilt** [comment]
Your math is pretty darn close.  :)

```
Error: expect(received).toBeCloseTo(expected)

Expected: 3553764305895.2593
Received: 3553764305895.293

Expected precision:    2
Expected difference: < 0.005
Received difference:   0.03369140625
```

That's a test of the upgrade cost for taking an office of size 3 to size 153, so I think I'll just adjust the tests...
