### ISSUE TITLE
Bitburner v2.6.0 showed 3/3 Source File in Bitverse for IPvGO despite never playing it.

### ISSUE THREAD

**Issue by Te-M** [bitburner-official/bitburner-src#1174]
This is on the Steam version, not part of the beta branch.  Just finished my 50th BN12 challenge and thought I'd check the new one just to see it was already completed!  However, it doesn't seem to be listed under Source Files in Augmentations so I'm not sure if it was actually counting or not (I loaded the old save at least until it's fixed).

**Comment by catloversg** [comment]
@Te-M It's only a UI error, so you don't need to worry about it, just play the game as normal. It's been fixed in dev version (Steam Beta).

**Comment by Te-M** [comment]
Oh, good!  I looked around but forgot to check commits.  Thanks!
