### ISSUE TITLE
FEATURE and DOCUMENTATION REQUEST: Port limit

### ISSUE THREAD

**Issue by User670** [bitburner-official/bitburner-src#1190]
#1189 : I hit the port limit and the script crashed, and it's not immediately obvious what went wrong nor what I needed to do to fix it.

I'd like to request:
- something in the documentation saying that ports have a limit, and one should clean after their ports with `readPort` or `clearPort`.
- make the error message more clear what's happening - make it say "port limit reached" or something. Otherwise it's not immediately obvious which `Map` is exceeding its limit, especially considering I wasn't using a map myself.
- probably bad idea, but probably have `clearAllPorts` and `clearPortRange` functions so that cleaning up is easier.

**Comment by d0sboots** [comment]
I agree that the 3rd point is probably a bad idea. And we don't have any real control over the 2nd - that's the JS engine throwing, we could try to catch errors from ports but wrapping all port usage in `try`/`catch` would slow down the common case a lot, plus the stack trace should lead you directly to the point in *your* code where the issue happened (namely, `writePort`.)

However, the first point definitely could use some improved documentation.

**Comment by User670** [comment]
> plus the stack trace should lead you directly to the point in your code where the issue happened (namely, writePort.)

It leads to this line:
```js
await Promise.all(pids.map(pid => ns.nextPortWrite(pid)))
```
where `pids` is an array of PIDs (also port numbers) of hack/grow/weaken threads spawned by my batcher.

`writePort` happened inside the hack/grow/weaken threads, but didn't throw such an error.

So `nextPortWrite` actually created a port object in the Map...?
