### ISSUE TITLE
ns.singularity.destroyW0r1dD43m0n does not accept bitnode 14

### ISSUE THREAD

**Issue by GDennis** [bitburner-official/bitburner-src#1197]
The call to ns.singularity.destroyW0r1dD43m0n(14, 'start.js') fails because it does not accept the new bitnode 14.
The thrown error is "Invalid bitnode specified: 14"

- [x] Save file
[bitburnerSave_1711662541_BN12x83 reproduce.json](https://github.com/bitburner-official/bitburner-src/files/14795889/bitburnerSave_1711662541_BN12x83.reproduce.json)
call finish.js
- [x] Minimal scripts to reproduce the issue
   ns.singularity.destroyW0r1dD43m0n(14, 'start.js')
   see finish.js
- [x] Steps to reproduce
  call ns.singularity.destroyW0r1dD43m0n(14, 'start.js') after any bitnode is ready to be destroyed by bladeburner.
  in save file call finish.js
- [x] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
  Bitburner v2.6.0 (8154a4613)

**Comment by catloversg** [comment]
This bug was fixed on dev branch (Steam Beta).
