### ISSUE TITLE
wget with / causes bad files

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#12]
[hydroflame]
null

**Comments From Original Issue**

[phyzical]
> to confirm i think this is the bug? 
> ```
> /** @param {NS} ns **/
> export async function main(ns) {
> 	await ns.wget("https://gist.githubusercontent.com/ramzs/35fa68c0e4c83e4b66d2137d8364dbd6/raw/281998608078700ed213bad1cc019b31a5b2cccd/PaymentNotificator.gs", "/file.txt", "home")
> }
> ```
> ![image](https://user-images.githubusercontent.com/5182053/153178148-07280b07-17c2-4e2c-b9f5-231f2b82c284.png)
> 
> it works if i use `file.txt` 
> if i use `/file.txt` it saves it as a directory called / that you cannot cd into and cannot ls

[phyzical]
> on a side note should we even allow this anymore given the vscode integration?

[phyzical]
> related https://github.com/danielyxie/bitburner/issues/2991

**Comment by Snarling** [comment]
Closing as duplicate/part of #10
