### ISSUE TITLE
Negative Bladeburner Stamina

### ISSUE THREAD

**Issue by AlyTyler** [bitburner-official/bitburner-src#1206]
My Bladeburner stamina somehow got into the negatives. No scripts running just sleeves Training. Was at -550 at it's lowest. None of my actions should have been lowering stamina. I've attached my save file though I'm not sure it contains anything but proof this happened.

[bitburnerSave_1712010881_BN9x2.json](https://github.com/bitburner-official/bitburner-src/files/14829150/bitburnerSave_1712010881_BN9x2.json)

**Comment by Snarling** [comment]
Loaded game into the main release 2.6.0 -> verified that stamina is negative
Loaded game into the dev release 2.6.1 (https://bitburner-official.github.io/bitburner-src/ or development branch on steam) -> stamina no longer allowed to be negative and starts recovering from 0.

I'm not sure what originally caused your stamina to become negative on 2.6.0, but a bunch of Bladeburner code was refactored recently and it looks like 2.6.1 won't cause this behavior, so the issue has probably already been addressed for dev branch.

Note that if you load your game into 2.6.1dev, any further savegames won't be able to be loaded back into 2.6.0, but you should be fine if you stay on the dev branch until 2.6.1 releases.

**Comment by catloversg** [comment]
@d0sboots We can close this. Stamina is "clamped" between 0 and max stamina now. In old versions, stamina can be negative by doing tons of training with sleeves. It was reported in #844. In the current version, stamina can still be negative after training, but that negative value will be set to 0 in the next "tick".
https://github.com/bitburner-official/bitburner-src/blob/38d99ff15ec2e5d6e28108a2e8983304c56afb45/src/Bladeburner/Bladeburner.ts#L1271
