### ISSUE TITLE
Hacknet cost reducing augments do not apply to Hacknet Server cache

### ISSUE THREAD

**Issue by gmcew** [bitburner-official/bitburner-src#1261]
Hacknet Nodes (the un-upgraded version) have three upgrade categories: level, RAM and cores. These have corresponding entries in Multipliers.ts of: hacknet_node_ram_cost, hacknet_node_core_cost, hacknet_node_level_cost.
Unlocking Hacknet Servers gives, amongst other benefits, the fourth upgrade of "cache", which doesn't have a corresponding cost multiplier entry and gains no cost-reduction benefits from mechanic multipliers (stanek/go/augments).

Example solutions:
- Change hacknet cost-reduction descriptions to cover level, RAM, core cost decrease only.
- Add cost reduction to cache upgrades too; e.g. an additional multiplier entry or combining them all to a single "hacknet_upgrade_costs" entry. This will break things from old saves.
- Since cache is not the most useful upgrade on a Server, and Hacknet is not a massive factor in most scenarios - do nothing is also a valid option.

Steps to reproduce:
With Hacknet Servers unlocked, apply upgrade cost reduction (picture uses stanek at about 4% discount). Note cost of cache before and after discount.

Example:
![discount](https://github.com/bitburner-official/bitburner-src/assets/97335456/a317e1fb-3d10-4cf7-873e-62127d20d63d)
![no discount](https://github.com/bitburner-official/bitburner-src/assets/97335456/9cfc5942-1d87-4010-9c33-1ad62deae14b)

**Comment by d0sboots** [comment]
I feel like "do nothing" is a valid option here, but it's good to have this documented.
