### ISSUE TITLE
scheduleExec

### ISSUE THREAD

**Issue by sparkles3421** [bitburner-official/bitburner-src#1280]
ns.scheduleExec("file.js",5000)
ns.scheduleExec(fileName,TimeInMillis)

essentially just exec but can be scheduled by specific time, this way you can run 2 files one after the other without a ram problem.

**Comment by d0sboots** [comment]
You can accomplish this with `ns.exec("trampoline.js", remoteHost, 1, ...args)`

Where `trampoline.js` is:
```js
/** @param {NS} ns */
export async function main(ns) {
  ns.spawn(ns.args[0], {spawnDelay: ns.args[1]}, ...ns.args.slice(2));
}
```

Edit: However, there's no read need to do that if you're exec'ing on a remote host, and for a local host you can just use `spawn` directly.
