### ISSUE TITLE
Bad examples in markdown

### ISSUE THREAD

**Issue by Shadewing666** [bitburner-official/bitburner-src#1294]
In both bitburner.ns.getpurchasedservercost.md and bitburner.singularity.getdarkwebprogramcost.md, the example at the bottom use ${ns.formatMoney(cost)}

I could find no other reference to this function and when I tried to test it I got back a "function not defined" error.

I went digging and found formatMoney in various places in the code but they are all pulling from src/ui/formatNumber.ts, so not a directly player accessible function.

Can I suggest removing or changing the examples or making some of the other formatX function available?

**Comment by d0sboots** [comment]
Internally, `formatMoney(x)` is just `"$" + formatNumber(x)`. And `ns.formatNumber` does exist. So it should be an easy task to fix those examples.
