### ISSUE TITLE
some coding contracts have &nbsp; 

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#13]
[hydroflame]
null

**Comments From Original Issue**

[phyzical]
> is this one 
> * just a matter of replaces the  `&nbsp;` with pre tags 
> * just removing them and tweeking the text until they are all readable?
> * just removing the `&nbsp;` entirely?

[borisflagell]
> Still a relevant issue as of 1.7.0

**Comment by Snarling** [comment]
This has been fixed

**Comment by DJetson** [comment]
This appears to still be an issue as of v2.6.2. It can be reproduced by using ns.tprint() to output ns.codingcontract.getDescription() to the terminal window. 
![image](https://github.com/user-attachments/assets/d75f61e4-5961-46a0-9960-4e0dbffa548c)
