### ISSUE TITLE
Separate Docs into new repository

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#130]
[Tanimodori]
This project currently contains docs and its generated results which is not required for building the game. So I suggest moving docs into a new repository for better maintaining. So they can have different toolset and different configurations.

**Comment by Snarling** [comment]
@hydroflame I agree with @tanimodori here, are you able to make a bitburner-docs repo on this org? Then we can move docs/ and markdown/ over there (and maybe dist/bitburner.d.ts? I'm not sure if it has a different purpose), and I believe there's a way for us to set up a workflow here for updating markdown from the output of `npm run doc` (a bit more conversation on the same topic over at #129)

**Comment by Snarling** [comment]
Related to #61, closing this as duplicate.
