### ISSUE TITLE
Scripts can pollute the shared context

### ISSUE THREAD

**Issue by YarikTH** [bitburner-official/bitburner-src#1302]
It seems that all the scripts are working in the same context instead of being isolated from each other.

I bumped into this accidentally, when added sorting method sortOn() to the Array. It resulted in unwanted behavior and I reverted such implementation. But for my surprise, even if I have already removed the code, saved file and restarted the script, sortOn was still presented. Only restarting the game fixed it for me (I could write script to remove this prototype, but resetting the game is easier).
I'm not sure if it is actual game limitation or it depends on my game version and launch options.

Steps to reproduce:
```js
// test.js
String.prototype.leak = function () {
  return "WTF?";
}

/** @param {NS} ns */
export async function main(ns) {
}
```

```js
// test2.js
/** @param {NS} ns */
export async function main(ns) {
    ns.tprint(''.leak());
}
```

```
[home /]> run test.js 
Running script with 1 thread(s), pid 821 and args: [].
[home /]> run test2.js 
Running script with 1 thread(s), pid 822 and args: [].
test2.js: WTF?
```

This leak allows to communicate all the scripts on the same launch with each other if I feel cheaty or at least it causes big confusion when trying to debug what happens.

Version Bitburner v2.6.1 (d2c7b2504) from steam under Linux (Play --no-sandbox (diff flags for different linux distro)

**Comment by YarikTH** [comment]
It is not jailbreak if there is no jail in the first place
![image](https://github.com/bitburner-official/bitburner-src/assets/21075945/06003440-2f34-4257-b371-9c19caf2d9c9)

**Comment by catloversg** [comment]
There is no "leak" here. It's just how JS works. If you change the prototype of `String`, every string will be affected. Players can use port-related NS API to make scripts communicate with each other. Some players ignore those API and just use `globalThis`.

**Comment by YarikTH** [comment]
"Leak" here in the fact that each script is not isolated and thus all affect each other. They can be potentially isolated with iframes or worker threads, but as I understand it has a performance cost. I'm not a web developer, so I might be wrong in specifics.

Anyway, it is not a big deal. If using `globalThis` instead of proper in-game API considered normal practice, then it is not even an issue.

**Comment by d0sboots** [comment]
To add a bit more flavor to this: Between the fact that this is Javascript, and also some fundamentals of how the game is written, it is just not possible to lock everything down. We have chosen to embrace this as a "feature": Since getting access to the Player object and boosting your stats to the max is not terribly hard, you get to decide for yourself what is too "cheaty."
