### ISSUE TITLE
Hyperbolic Regeneration Chamber not working properly

### ISSUE THREAD

**Issue by Kaleidoscopio** [bitburner-official/bitburner-src#1308]
After loosing health doing Bladeburner actions, if I choose to heal by using the action "Hyperbolic Regeneration Chamber" the health will heal by 2 points then shortly after reduces by 2 points again automatically.
I've noticed this behavior initially while running an automation script for Bladeburner actions.
Killing the script and choosing the action manually has the same result.
Player health regenerates by two and then shortly after reduces by two.

Only way to heal at the moment is by using Hospital.

Game Version: {"version":"2.6.1","commit":"d2c7b2504","platform":"Steam"}

**Comment by catloversg** [comment]
@Kaleidoscopio Can you attach your save file? I cannot reproduce it.

**Comment by Kaleidoscopio** [comment]
[bitburnerSave_1716630544_BN3x3.json.gz](https://github.com/bitburner-official/bitburner-src/files/15443492/bitburnerSave_1716630544_BN3x3.json.gz)
