### ISSUE TITLE
FEATURE REQUEST: ANSI Escape Codes

### ISSUE THREAD

**Issue by GreenBeen494** [bitburner-official/bitburner-src#1326]
As far as I know, there is no way to do [ANSI](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) codes or anything else like that. It would be a nice add since it would be easy to tell the difference between the terminal-writes from scripts and the normal terminal commands (without any theme customizing, everything other than terminal-errors, which would be red, would be green).

Just a suggestion, maybe instead of ANSI codes, there could be a whole new custom version of ANSI.

**Comment by d0sboots** [comment]
You actually can do ANSI codes (at least the color ones).
