### ISSUE TITLE
Feature request: formula for predicting the security effect of growth

### ISSUE THREAD

**Issue by jcbollinger** [bitburner-official/bitburner-src#1331]
Bitburner v2.6.1 (Steam)

I would like to be able to predict the effect of a future `ns.grow()`, according to the state of the target server as of when the `grow()` lands. That is, I want an analog of `ns.growthAnalyzeSecurity()` that considers my predicted future server state instead of its current state.  This seems like a reasonable and natural thing for the formulas API to provide, but it doesn't seem to do so.

**Comment by d0sboots** [comment]
WDYM by "predicted future server state?" If you mean literally "the future state of the server, taking into account all pending hacks, grows and weakens" then there's no way that will be a formulas function. 

1. Formulas take a possible state as input and return a computed output. In other words, they do not depend on game state, but instead take whatever state needed for the calculation as input. So such a function would need to take as input "the set of all pending hacks, grows, and weakens for this server." But collecting that is itself the hard part. 
2. Related to 1, this type of function is something you should write yourself as needed when you are making a batcher. It's not a general utility method like the other formulas functions.

**Comment by jcbollinger** [comment]
> WDYM by "predicted future server state?" If you mean literally "the future state of the server, taking into account all pending hacks, grows and weakens" then there's no way that will be a formulas function.

I mean, **I** predict, and the requested function gives me a computation based on the hypothetical server state I have predicted.  Presumably, I would convey the prediction via a `Server` object that I prepare.  This seems pretty analogous to other functions in the Formulas API.

>     1. Formulas take a possible state as input and return a computed output. In other words, they do not depend on game state, but instead take whatever state needed for the calculation as input.

Yes, that's what I want.

> So such a function would need to take as input "the set of all pending hacks, grows, and weakens for this server." But collecting that is itself the hard part.

No.  I'm not asking for a function that considers actual game state.  I'm asking for one that computes the effect of a hypothetical `grow` on a server that is in a state that I specify.

>     2. Related to 1, this type of function is something you should write yourself as needed when you are making a batcher. It's not a general utility method like the other formulas functions.

What I have done is find the growth formula in the BitBurner source, and write a one-line function that emulates that, subject to one or two simplifying assumptions.  This is working for me so far, and the approach seems somehow thematic. But my workaround overestimates in some (well understood) cases, and it may stop working altogether if the growth formula is changed in a future version of BB.

This is not about getting BB to do work for me that I should do myself.  It is about providing access to the formulae that BB uses internally to compute growth effects.  Much like the existing members of the Formulas API.

**Comment by d0sboots** [comment]
In that case, I'm confused. You already have that function. It's `growthAnalyzeSecurity()`.

**Comment by jcbollinger** [comment]
> In that case, I'm confused. You already have that function. It's `growthAnalyzeSecurity()`.

I know about `ns.growthAnalyzeSecurity()`.  It's mentioned in the request.  It does not do the job I want because it performs its computation based on the state of the target server at the time of the call, not based on a state I can specify.  

For example, if the server `rothman-uni` currently has its maximum amount of money then `ns.growthAnalyzeSecurity(1, "rothman-uni")` returns `0`.  But if I anticipate hitting that server with a `hack` followed by a `grow`, then the security impact of the `grow` will in fact be greater than 0 (all else being equal).  I can compute the server state I expect at the time the `grow` lands, but the API doesn't provide a way for me to compute the correct security impact of that `grow` based on my expectation.

**Comment by d0sboots** [comment]
Just don't pass a servername to the function.

There is no "state" required to compute the security effect of a grow, so all the server parameter does is limit the effective amount of grows based on current money (as you noted).

**Comment by jcbollinger** [comment]
> There is no "state" required to compute the security effect of a grow

Of course there is.  The security effect differs depending on the difference between the target server's current and maximum money at the time the `grow` lands.

> so all the server parameter does is limit the effective amount of grows based on current money (as you noted).

Omitting the server parameter gives me an _upper bound_ on the security effect. This is useful and indeed does not depend on any server's state. But I want to compute the _actual_ security effect of my `grow`s, under the conditions that I expect will prevail at the times they land.  If there is already a way to do that then I would be delighted to hear it, but I haven't heard one or found one yet.

**Comment by d0sboots** [comment]
> Omitting the server parameter gives me an upper bound on the security effect. This is useful and indeed does not depend on any server's state. But I want to compute the actual security effect of my grows, under the conditions that I expect will prevail at the times they land. If there is already a way to do that then I would be delighted to hear it, but I haven't heard one or found one yet.

(It seems like you deleted this, but I'll answer the question anyway in two parts):

1. If you want to actually calculate the reduced effect of grows based on the amount of money on the server, then you'll need the equivalent of `numCycleForGrowthCorrected` that `growthAnalyzeSecurity` uses. The formulas version of this function is `ns.formulas.hacking.growThreads`. Using that in combination with the predicted future money will tell you the precise effect.
2. Why this is irrelevant: The security is only reduced for *entire threads* that go above what is needed. A partial grow thread still has its full security impact (due to the integer rounding in `numCycleForGrowthCorrected`.) As a result, if there is ever any difference between the upper bound and the true value, it means *you messed up in your calculations* and scheduled more grow threads than were needed.

Since this calculation is only needed to optimize a situation where you have *already* made a suboptimal choice, no one bothers with it.

**Comment by jcbollinger** [comment]
> (It seems like you deleted this, but I'll answer the question anyway in two parts):

Yes, I first wrote that comment when I was away from the game, and I wanted to confirm my assertion about game behavior.  Thank you for responding.
 
>     1. If you want to actually calculate the reduced effect of grows based on the amount of money on the server, then you'll need the equivalent of `numCycleForGrowthCorrected` that `growthAnalyzeSecurity` uses. The formulas version of this function is `ns.formulas.hacking.growThreads`. Using that in combination with the predicted future money will tell you the precise effect.

Thank you, that sounds like exactly what I was looking for.

>     2. Why this is irrelevant: The security is only reduced for _entire threads_ that go above what is needed. A partial grow thread still has its full security impact (due to the integer rounding in `numCycleForGrowthCorrected`.) As a result, if there is ever any difference between the upper bound and the true value, it means _you messed up in your calculations_ and scheduled more grow threads than were needed.

Fair enough. 
 
> Since this calculation is only needed to optimize a situation where you have _already_ made a suboptimal choice, no one bothers with it.

Thank you for indulging me.
