### ISSUE TITLE
can't import savegame from different computer, console shows type error 

### ISSUE THREAD

**Issue by herrxyz** [bitburner-official/bitburner-src#1342]
- [x] Save file
- [x] Steps to reproduce - open savefile
- [x] Version of the game, e.g. Bitburner v2.6.1 (d2c7b2504) on steam

cloud save is enabled, when I tried to load save at a different PC it wasn't loading due do this error (can't continue to play at different PC)
tried it using steam cloud and tried to import, both failed

Console says:
SaveObject.ts:216 o: TypeError: The compressed data was not valid: incorrect header check.
    at file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1986232
    at async l (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1985956)
    at async B.getImportDataFromSaveData (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1333011)
    at async Object.getSaveInfo (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:591581)
    at async AsyncFunction.<anonymous> (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:592212)

main.log from log-folder shows nothing special

didn't change gamefiles, just added and ran scripts
[bitburnerSave_1717344461_BN4x1.json.gz](https://github.com/user-attachments/files/15525931/bitburnerSave_1717344461_BN4x1.json.gz)

**Comment by d0sboots** [comment]
https://github.com/bitburner-official/bitburner-src/pull/1341 was submitted as a hotfix for this.

However, that by itself might not be enough to recover. Your best bet would be to get the new hotfix version of BB that was released, play that on the original computer (where it's still working), and then after you close the game steam sync ought to work properly. The manual import/export should work as well.

**Comment by gmcew** [comment]
I assume the hotfix referenced is the solution to this, but I propose keeping it open for broader information in case anyone else has the same issue, or the hotfix didn't fully resolve the problem here.

**Comment by herrxyz** [comment]
can I apply it by just select "dev" channel in steam beta's? or do I have to add it manually in a file?

**Comment by d0sboots** [comment]
The fix should be in the current stable release, if I understand right. But you'll have to have saved once from the original computer; it's not going to make the corrupted cloud save start working. 

Alternatively, the exported save file you posted here seems perfectly fine to import.

**Comment by gmcew** [comment]
I'm taking silence as success - as mentioned, importing the file in the original post seems to work ok
