### ISSUE TITLE
Bug ; Negative values while working for nitesec. 

### ISSUE THREAD

**Issue by Dev-Dia** [bitburner-official/bitburner-src#1344]
[bitburnerSave_1717381072_BN3x1.json.gz](https://github.com/user-attachments/files/15528091/bitburnerSave_1717381072_BN3x1.json.gz)
![image](https://github.com/bitburner-official/bitburner-src/assets/137475668/b7ea0ec4-5d58-4c95-9295-d8ba74fdf1e8)
Game v2.6.1
I was working for nitesec faction, while doing so I tried the donation mechanic for the first time;
I donated 100m, when I focused back on training my hours were negative, money negative, and my faction reputation had been reduced 70k or so. 
Restarting work reset the hours to 0, but the other values remain the same.

**Comment by catloversg** [comment]
This is very likely due to the system clock going backward. For example, let's say the system clock is at 07:00 PM, then suddenly something sets it to 07:00 AM (same day or previous day). We will try to mitigate this case, or at least notify the player about it.

**Comment by Dev-Dia** [comment]
This could definitely be the cause. My system clock often gets out of sync while switching operating systems. It had never been an issue before, so I did not consider it. Thanks.
