### ISSUE TITLE
IPVGO: progress resets due to the corrupted save data

### ISSUE THREAD

**Issue by Shawdown** [bitburner-official/bitburner-src#1352]
![image](https://github.com/bitburner-official/bitburner-src/assets/8985507/086ee77f-33b4-44b9-acb5-899d50039465)

If you play against the secret opponent which has its custom board size, save, and then restart the game, all the GO save data disappears.

Bitburner v 2.6.1 (`e8a825829`)

**Comment by d0sboots** [comment]
@ficocelliguy

**Comment by Shawdown** [comment]
❤️
