### ISSUE TITLE
grafting.getAugmentationGraftPrice: Invalid aug: Neural Accelerator

### ISSUE THREAD

**Issue by Madgui** [bitburner-official/bitburner-src#1386]
Hello guys, I think I found a bug. It's my first report so be kind.
it's happening on steam version and online version v2.6.1.
```
const x = ns.grafting.getAugmentationGraftPrice('Neural Accelerator')
```
This one is working, so the name is good:
```
const list = ns.singularity.getAugmentationPrereq('Neural Accelerator')
```
Regards.

**Comment by catloversg** [comment]
I cannot reproduce it. This script works as expected.

```js
/** @param {NS} ns */
export async function main(ns) {
  ns.tail();
  const x = ns.grafting.getAugmentationGraftPrice('Neural Accelerator');
  ns.print(x);
}
```

Can you attach your save file?

**Comment by Madgui** [comment]
[bitburnerSave_1718227233_BN8x2.json.gz](https://github.com/user-attachments/files/15811057/bitburnerSave_1718227233_BN8x2.json.gz)
Sure !
I deleted every script but TEST.js that show the issue.
Regards.

**Comment by catloversg** [comment]
`Neural Accelerator` is in your "Installed Augmentations" list. You cannot graft an installed augmentation.

**Comment by Madgui** [comment]
...And now I feel like a moron again ;)

**Comment by Madgui** [comment]
Not a bug.
