### ISSUE TITLE
You can't disable production limit for product.

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#14]
[hydroflame]
null

**Comments From Original Issue**

[phyzical]
> Is this one just a matter of providing "reset" buttons for all actions, we would add it to the sell action also.
> 
> also adding api actions for this "cancel"

**Comment by Snarling** [comment]
Accidentally linked this issue on the wrong PR.

**Comment by Snarling** [comment]
Verified that empty string does disable the product production limit, and it is documented on the modal.
![image](https://user-images.githubusercontent.com/84951833/197773956-9b0b74c1-c9fb-4bbc-a6b8-eea4d8a00cc4.png)
![image](https://user-images.githubusercontent.com/84951833/197774124-314719c8-7f7c-45c1-9733-6aab64f36738.png)
![image](https://user-images.githubusercontent.com/84951833/197774186-d3045971-5c97-4b2d-9240-b2abbfcf79d2.png)
 (Limit removed by submitting empty string)
