### ISSUE TITLE
Gang wanted level not matching growth rate 

### ISSUE THREAD

**Issue by hayned2** [bitburner-official/bitburner-src#1403]
Bitburner v2.6.1 (e8a825829)

[bitburnerSave_1718484079_BN2x1.json.gz](https://github.com/user-attachments/files/15854958/bitburnerSave_1718484079_BN2x1.json.gz)

![BitBurner Wanted Level](https://github.com/bitburner-official/bitburner-src/assets/63313054/024509d7-d6d7-4545-bc46-e8ce631dfdc7)

I wrote a script to manage my gang, and I'm looking at the Wanted Level in the screen. It shows a rate of about -3/second, but my Wanted Level is actually slowly _increasing_. I'm not sure if the displayed rate or the actual rate that's occurring is incorrect, but they don't match.

**Comment by d0sboots** [comment]
Someone else might chime in, but it's likely a mistake in your script. If you come to the discord, you might have better luck with debugging (there are more people hanging out who can help in real-time.)

**Comment by catloversg** [comment]
This bug is reproducible. I'll fix it.
