### ISSUE TITLE
Cannot Load Steam Cloud Files after recent patchfix

### ISSUE THREAD

**Issue by Taven334** [bitburner-official/bitburner-src#1438]
Hello I am now running into the issue of not being able to load my steam cloud save files when I do I get this error message 

Error "Cannot get save data. Error: o: TypeError: The compressed data was not valid: incorrect header check..
Stack:
o: TypeError: The compressed data was not valid: incorrect header check.
at file:///C:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1986333
at async l (file:///C:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1986057)
at async B.getImportDataFromSaveData (file:///C:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1333112)
at async file:///C:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1922636"

I have tried reinstalling the game and have changed the install disk, I have also tried the development build of the game and its still reporting the same error.

**Comment by catloversg** [comment]
The Steam Cloud save file is corrupted by the initial version of v2.6.1. We released a hotfix for it, so you should check if you are using the latest version. The hotfix version won't recover the corrupted save file, though. It only prevents the problem from happening again. If you still have a backup save file, you should load it and let the Steam Cloud replace the corrupted save file with the new imported one. In the worst case, if you don't have any backup save file, you can upload the corrupted save file here. I'll take a look and try to recover it if it's possible.

**Comment by Taven334** [comment]
I have verified that I am using v2.6.1
[9b7f5385319e4.json](https://github.com/user-attachments/files/15991298/9b7f5385319e4.json)

**Comment by catloversg** [comment]
Recovered save file:
[9b7f5385319e4.json.gz](https://github.com/user-attachments/files/15991579/9b7f5385319e4.json.gz)

**Comment by Taven334** [comment]
So I tried to load from file and this is what I got in return

Cannot get save data. Error: Error: Save game is invalid.
Stack:
Error: Save game is invalid
    at B.getImportDataFromSaveData (file:///C:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1333237)
    at async file:///C:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1922636

**Comment by Taven334** [comment]
Never mind I just loaded it as the archive itself and it worked thank you so much!
