### ISSUE TITLE
`ns.disableLog()` complaining about Invalid argument (adjust documentation?)

### ISSUE THREAD

**Issue by PeterNerlich** [bitburner-official/bitburner-src#1440]
After reading the documentation on `ns.disableLog()`, I wrote a separate function that compiled various host data via `ns.getServerSecurityLevel()` etc. and passed its name to `ns.disableLog()` as a string. The script failed with a RUNTIME ERROR `disableLog: Invalid argument:`, which came as a surprise to me.

Quickly glancing over [what the function actually does](https://github.com/bitburner-official/bitburner-src/blob/b597746343d960767fd5904a79bfc5097e0fb841/src/NetscriptFunctions.ts#L494) gives me the impression that I misunderstood the documentation and that there is only a specific set of functions *(all under the `ns` namespace?)* that can be specified. If so, I think it would be beneficial to explain this in the documentation.

**Comment by catloversg** [comment]
What did you try? What was your expectation after reading the documentation of `ns.disableLog`? Did you try to use it like this `ns.disableLog("myCustomFunctionNameInsteadOfNSAPI")`?

**Comment by PeterNerlich** [comment]
> Did you try to use it like this `ns.disableLog("myCustomFunctionNameInsteadOfNSAPI")`?

Yes, exactly
