### ISSUE TITLE
STATS: Reset info displays incorrect destruction time.

### ISSUE THREAD

**Issue by otac0n** [bitburner-official/bitburner-src#1465]
![image](https://github.com/bitburner-official/bitburner-src/assets/193584/50418cd3-2101-4540-ad3d-541c03dcbb5f)

Running `run b1t_flum3.exe` counts as destruction from here?  Either two stats should be provided or this should not update with execution of b1t_flum3.exe

**Comment by catloversg** [comment]
Technically, running b1t_flum3 is almost the same as destroying the BN via normal methods (hack/backdoor WD, Bladeburner). The only difference is that running b1t_flum3 does not grant SF rewards.

**Comment by d0sboots** [comment]
When you run `b1t_flum3.exe`, you still see the text before the BN selection that indicates that the current BN was destroyed. So lore-wise, I think this is correct.
