### ISSUE TITLE
Various autocomplete issues

### ISSUE THREAD

**Issue by kittycat2002** [bitburner-official/bitburner-src#1473]
Bitburner v2.6.2 (633da3830)

There are a couple issues with the current autocomplete implementation:
1. it doesn't handle partial quotes correctly so you may have difficulty autocompleting anything with spaces.
for example `run test.js "foo bar"` will pass `["foo bar"]` while `run test.js "foo bar` and `run test.js "foo  bar` will pass `['"foo', "bar"]`
2. there is currently no way to determine in a script's autocomplete method what argument the user is currently trying to complete.
for example `run test.js foo` and `run test.js foo ` will pass `["foo"]` to the method.

**Comment by d0sboots** [comment]
Yup. This relates to how the argument parsing is pretty rudimentary. It's not likely to change, but the issues are valid and real.

**Comment by gmcew** [comment]
To add to d0s' point above; there's a few other references for autocomplete's limitations, as well as some workarounds by other users at #522 and #1014 
To avoid too much duplication, I'll close this one
