### ISSUE TITLE
wirecutting minigame augmentation

### ISSUE THREAD

**Issue by BlueJay055** [bitburner-official/bitburner-src#1480]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
- [x] other ( when I bought one of the augmentations that was supposed to help with the wire cutting minigame it bugs out and indicates both correct and incorrect wires causing things to be a 50/50 everytime

**Comment by catloversg** [comment]
Please use the issue format and provide relevant information.

I cannot reproduce your problem. This is a screenshot of the wire-cutting game when you have access to `SoA - Knowledge of Apollo`.
![Capture](https://github.com/bitburner-official/bitburner-src/assets/152669316/88f20f55-846d-4a64-84d8-8824be0ed7eb)
In this case, the incorrect wires are 3 and 6. They use the color that is defined as the "disabled" color in your theme.
When you have that augmentation, you only need to cut the wires that don't have the "disabled" color.

**Comment by gmcew** [comment]
Augment does seem to function as intended; the "disabled" theme choice could be the root of the issue if it comes up again.
