### ISSUE TITLE
API Server: Support pushing json format

### ISSUE THREAD

**Issue by ccs19** [bitburner-official/bitburner-src#1485]
- [x] Steps to reproduce
Perform a post request to the API server at `http://localhost:9990` with this payload:

```
{
    "filename":"/apitest/test.json",
    "code":"code"
}
```

This results in a 400: 

```
{
    "success": false,
    "msg": "Invalid file extension: must be a script"
}
```

- [x] Bitburner v2.6.2 (633da3830)

Hello. I'm currently making an API server integration plugin for Jetbrains IDE support and wanted to support pushing JSON files. 

The use-case here is for configuration. For example, I'm writing some singularity scripts that periodically check a configuration file and switch to crime/work/faction by updating the config file. The workaround here is to just set the configuration's extension as `*.js`, but of course IDEs complain about that.

I see the extensions are [defined here](https://github.com/bitburner-official/bitburner-src/blob/8d39c7d9fcbb7d3aa0e4b8ab5395c5321085872a/src/Paths/ScriptFilePath.ts#L11) and that is causing the [save here ](https://github.com/bitburner-official/bitburner-src/blob/8d39c7d9fcbb7d3aa0e4b8ab5395c5321085872a/src/Electron.tsx#L86)to fail, Though since I'm not familiar with the code base, so I don't know if it's appropriate to add the extension there.

**Comment by catloversg** [comment]
The API Server is deprecated, so we won't make any changes to it. It may even be removed in future versions. The standard way to "interact" with Bitburner is to use the Remote File API (https://github.com/bitburner-official/bitburner-src/blob/dev/src/Documentation/doc/programming/remote_api.md).

**Comment by ccs19** [comment]
Ah... I was not aware of that, thanks! I was using the VSCode extension as a reference but will switch gears.

**Comment by gmcew** [comment]
For future reference regarding the VSCode extension/API server: #687 and #1034 
I note that the in-game docs (Tools & Resources) does refer to the VSCode extension, so whilst I'm proposing closing this issue, I'll capture the documentation point on the existing issue (#1034)
