### ISSUE TITLE
API Server: No response is sent with malformed data on file upload

### ISSUE THREAD

**Issue by ccs19** [bitburner-official/bitburner-src#1486]
- [x] Steps to reproduce
Perform a post request to the API server at `http://localhost:9990` with this payload:

```
{
    "filename":"/apitest/test.js",
    "code":"code"
}
```

The request will timeout with no response to the API caller.

- [x] Bitburner v2.6.2 (633da3830)

When testing file pushing, I encountered a timeout if the payload is not base64 encoded.

This results in this error: 

```
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at navigator.userAgent.toLowerCase.includes.document.saveFile (Electron.tsx:88:12)
    at <anonymous>:1:10
```

An error is thrown when calling `decodeURIComponent` [here](https://github.com/bitburner-official/bitburner-src/blob/8d39c7d9fcbb7d3aa0e4b8ab5395c5321085872a/src/Electron.tsx#L88), but an HTTP response is never sent.

**Comment by catloversg** [comment]
Please check #1485.

**Comment by gmcew** [comment]
As above; the API server is no longer supported - see other issue above for more context.
