### ISSUE TITLE
Replace bitnode multiplers of combat exp for gym with literal combat exp reductions

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#15]
[hydroflame]
null

**Comments From Original Issue**

[phyzical]
> is this one implemented? i had a look around for bitnode multipliers and gyms but had no luck seeing anything anymore

**Comment by Snarling** [comment]
Per previous comment this does not seem to be relevant anymore

**Comment by devryx196** [comment]
Implemented in TrainingTools.ts with three tools:

- **analyze_training_options**: Analyzes university and gym training options with exp rates and efficiency. Can filter by stat (hacking, strength, etc.) and city.
- **analyze_crimes**: Analyzes crime efficiency for money, exp, karma, or kills. Provides recommendations for best crimes for different goals.
- **calculate_training_time**: Calculates time and cost to reach a target skill level at various training locations.

These tools help AI agents make informed decisions about:
- Which university courses or gyms to use for maximum exp/dollar efficiency
- Which crimes to commit based on optimization goals (money vs exp vs karma)
- How long it will take to reach specific skill levels
