### ISSUE TITLE
Cannot Select new bitnode

### ISSUE THREAD

**Issue by Taven334** [bitburner-official/bitburner-src#1506]
I got to the bitnode selection screen but cannot select the next bitnode.
![Bitnode](https://github.com/user-attachments/assets/09abf43b-8eee-47ab-be77-bd21c71084e4)

**Comment by d0sboots** [comment]
Can you upload your save? Best guess is there is something weird with it.

**Comment by Taven334** [comment]
[bitburnerSave_ 1721481066_BN 1x 1.json.gz](https://github.com/user-attachments/files/16321192/bitburnerSave_.1721481066_BN.1x.1.json.gz)

**Comment by Taven334** [comment]
It must have been something with my install, I exported the save file and reinstalled and its now allowing me to choose a bitnode!

**Comment by d0sboots** [comment]
Very odd. I think it's more likely something strange happened in your game state and reloading fixed it, but I'm glad it's working now. We'll keep an eye out for other instances of this.
