### ISSUE TITLE
CCT descriptions often print &nbsp; 's

### ISSUE THREAD

**Issue by Handsome-Dan** [bitburner-official/bitburner-src#1514]
Here's a sample CCT description, as printed to the terminal.  Several other CCT descriptions are similarly polluted.  I mean, you can tell what the author was going for, but it certainly doesn't print as expected.  ---Handsome Dan

```
Given a triangle, find the minimum path sum from top to bottom. In each step of the path, you may only move to adjacent numbers in the row below. The triangle is represented as a 2D array of numbers:

 [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[8],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[3,8],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[4,6,1],
&nbsp;&nbsp;&nbsp;&nbsp;[9,9,6,8],
&nbsp;&nbsp;&nbsp;[5,8,1,9,5],
&nbsp;&nbsp;[7,4,5,9,8,4]
]

 Example: If you are given the following triangle:

[
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2],
 &nbsp;&nbsp;&nbsp;&nbsp;[3,4],
 &nbsp;&nbsp;&nbsp;[6,5,7],
 &nbsp;&nbsp;[4,1,8,3]
 ]

 The minimum path sum is 11 (2 -> 3 -> 5 -> 1).
```

**Comment by Handsome-Dan** [comment]
Bah, in the comment above the & nbsp ; prints as expected on a web page -- it does not do so in the game terminal.

**Comment by d0sboots** [comment]
> Bah, in the comment above the & nbsp ; prints as expected on a web page -- it does not do so in the game terminal.

XD

Put it in a code block and that will show the issue.

**Comment by Handsome-Dan** [comment]
OP edited per @d0sboots (to which, Hi!).  Glad to see that @gmcew is looking into it.  Excelsior!

**Comment by Handsome-Dan** [comment]
Hooray!  I made a positive change to Bitburner by making someone else do all the work!  I'm a genius!  :-)
