### ISSUE TITLE
[BUG?] Inconsistent rounding behavior in MinesweeperGame

### ISSUE THREAD

**Issue by mmjr-x** [bitburner-official/bitburner-src#1520]
I was looking through the code of the MinesweeperGame and I noticed that the intention in its setup seemed to be that the grid is rectangular, see the difficulty config below, in each case both height and width are consistent

https://github.com/bitburner-official/bitburner-src/blob/dd5fcc077ac6fddfc32ada8de4ce108ca23d444f/src/Infiltration/ui/MinesweeperGame.tsx#L29-L32

However when playing the game the grid was not square:

![image](https://github.com/user-attachments/assets/c78f14b4-6d83-472b-a145-c0269c0debc3)

This made me wonder if there was an off by 1 error somewhere in the code, so I started looking for that. Seems the culprit is an inconsistent rounding issue instead in the following code:

https://github.com/bitburner-official/bitburner-src/blob/dd5fcc077ac6fddfc32ada8de4ce108ca23d444f/src/Infiltration/ui/MinesweeperGame.tsx#L167-L187

Turns out the difficulty's height and width values are interpolated in the same manner, however the floating point value resulting from this (e.g. `4.418230611480418` for both width and height) is handled differently between the setup of the columns and rows. In the line below you can see that for the number columns the interpolated difficulty's width is `Math.round`ed :

https://github.com/bitburner-official/bitburner-src/blob/dd5fcc077ac6fddfc32ada8de4ce108ca23d444f/src/Infiltration/ui/MinesweeperGame.tsx#L170

And in this line below you can see that for the number rows the interpolated difficulty's height is not `Math.round`ed, resulting in some cases in a height that is 1 higher than the column count (because of the way the for loops are set up, doing no rounding will result in behavior similar to a `Math.ceil`):

https://github.com/bitburner-official/bitburner-src/blob/dd5fcc077ac6fddfc32ada8de4ce108ca23d444f/src/Infiltration/ui/MinesweeperGame.tsx#L169

I don't know if this is intentional? If not the behavior should probably be made consistent (either round them both or not round them both). If it is the case that it should always favor the higher difficulty (as it is it doing when not rounding) it might be nice to `Math.ceil` the values explicitly (this will make the behavior more clear in the code)?

Also note that this behavior is inconsistent with the generation for the   grid-template-columns and  grid-template-rows css properties which are both rounded (although in this specific case and with the way css grid's work the grid-template-rows does not actually do anything and could be removed entirely):

https://github.com/bitburner-official/bitburner-src/blob/dd5fcc077ac6fddfc32ada8de4ce108ca23d444f/src/Infiltration/ui/MinesweeperGame.tsx#L113-L114

On a side note, the amount of mine's is also not rounded or ceiled, it might be also good to do that for consistency sake:

https://github.com/bitburner-official/bitburner-src/blob/dd5fcc077ac6fddfc32ada8de4ce108ca23d444f/src/Infiltration/ui/MinesweeperGame.tsx#L177

If a maintainer agrees with my findings I would be happy to raise a pull request which make's this behavior consistent?

**Comment by d0sboots** [comment]
Nice investigation! Yeah, rounding these consistently makes sense, so that the interpolation behavior is centered.

**Comment by mmjr-x** [comment]
@d0sboots Thanks! :D 

Shall I make a PR for this? And if so what behavior has your preference? (I'm leaning towards rounding instead of ceiling)

**Comment by d0sboots** [comment]
> Shall I make a PR for this? And if so what behavior has your preference? (I'm leaning towards rounding instead of ceiling)

If you feel inspired to. I agree that rounding makes the most sense.

**Comment by mmjr-x** [comment]
I made the PR, still have to test it though hence why I have raised it as a draft (have to properly set up the dev env up for that first)

**Comment by mmjr-x** [comment]
I did some testing on the PR, everything seems to be in order, so I marked the PR as ready for review :) (details about the tests can be found in the PR)
