### ISSUE TITLE
IPVGO: Concerns regarding in-game "How to Play" instruction

### ISSUE THREAD

**Issue by bupjae** [bitburner-official/bitburner-src#1538]
Bitburner v2.6.2 (633da3830)

1. This game uses Chinese scoring system (counts Empty Nodes + my Routers still on board), while [linked guide](https://way-to-go.gitlab.io/#/en/capture-stones) uses Japanese scoring system (counts Empty Nodes - my Routers removed from board)

2. This game does not remove "dead" Routers when game ends; the owner of the territory must place their Routers to capture manually before pressing Pass Turn or End Game. This fact should be mentioned in the insturction.

**Comment by d0sboots** [comment]
To point 1: The distinction does not (typically) matter for determining who won, or the margin of victory. However, since ipvgo uses the raw score values in determining how multipliers are gained, the difference is *quite* relevant to us.

**Comment by bupjae** [comment]
I just found that both points were explained on Discord Pinned message:

> How is the score calculated? Are prisoners counted?
> IPvGO uses the old traditional scoring for Go (area scoring) rather than the modern Japanese territory scoring. All stones are alive unless captured, and prisoners are not calculated. It comes out to the same if you show your work and play out the contested/theoretically dead chains. The displayed score is always the ending score if both players pass. This was chosen for its simplicity to teach and to calculate, rather than using the modern shortcuts designed to make physical games quicker.

Still, I think this message should also be present on in-game text.

**Comment by d0sboots** [comment]
@ficocelliguy

**Comment by ficocelliguy** [comment]
Technically the full scoring rules are in the "How to Play" tab, since area scoring is so simple, but (as has been pointed out here and from prior confusion in the discord) specifically drawing the distinction between the system IPvGO uses and territory scoring is useful for people with prior knowledge of Go. The PR linked above adds a lot of detail on this, both in the instructions tab and linked from the endgame score modal. 

Feedback on how the instructions are phrased in that PR would be welcome.

**Comment by bupjae** [comment]
The "[linked guide](https://way-to-go.gitlab.io/#/en/capture-stones)" I mentioned is from this snippet:

https://github.com/bitburner-official/bitburner-src/blob/e16ac34c15f69a79d186ad23365b2f9534b63825/src/Go/ui/GoInstructionsPage.tsx#L235-L238

This snippet has link to the guide with wording "slightly simplified scoring". So, I was assumed that the game would use scoring system mentioned in the guide.

Now we have detail-explained scoring system elsewhere, My suggestion is
* remove the text "slightly simplified scoring"
* If we want to retain the link, write some text that the scoring system in the linked guide is different with that of IPvGO. Otherwise, remove or replace the link.
