### ISSUE TITLE
Typos in the NetscriptDefinitions.d.ts

### ISSUE THREAD

**Issue by HiEv** [bitburner-official/bitburner-src#1543]
KarmaRequiremennt -> KarmaRequirement  (2 places)
assicated -> associated
commited -> committed
analagously -> analogously
stockmarket -> stock market

The first typo also affects the following files, not just in the filenames, but also [in the contents of each of these files](https://github.com/search?q=repo%3Abitburner-official%2Fbitburner-src%20bitburner.karmarequiremennt.md&type=code):
- markdown/bitburner.karmarequiremennt.md
- markdown/bitburner.karmarequiremennt.type.md
- markdown/bitburner.karmarequiremennt.karma.md
- markdown/bitburner.playerrequirement.md
- markdown/bitburner.md

I would have submitted a pull request, but I'm not sure of the right way to correct all of those issues.

**Comment by catloversg** [comment]
@d0sboots `KarmaRequiremennt` is an interface name. What do you think about this case?

**Comment by d0sboots** [comment]
I'm not sure why that's even in the public interface. I guess for documentation? But as near as I can tell, we never return objects of type PlaterRequirement, just the JSON-serialized form. As such, it should be more than safe to fix the name.
