### ISSUE TITLE
All BladeBurner actions have 0.0% probability and fail

### ISSUE THREAD

**Issue by Kaleidoscopio** [bitburner-official/bitburner-src#1551]
No script needed, no steps to reproduce are needed.
Just load attached save and all Bladeburner actions are 0.0% chance.

I have stupidly high values for Bladeburner activity by the way. :|

Version: 2.6.2

[bitburnerSave_1722984900_BN12x6.json.gz](https://github.com/user-attachments/files/16516440/bitburnerSave_1722984900_BN12x6.json.gz)

**Comment by catloversg** [comment]
Both population and estimated population in Sector-12 are 0. You need to move to another city.

**Comment by Kaleidoscopio** [comment]
ahahah, thanks.
I wonder how that happened. :P

**Comment by gmcew** [comment]
You're probably aware, but to justify closing this so quickly: certain actions reduce _real_ population by percentages or absolute amounts. When you run out of synthoids completely, no action can succeed -  this is intentional!
