### ISSUE TITLE
Stats say "Sleeves" instead of "Travel"

### ISSUE THREAD

**Issue by Soham-Kakkar** [bitburner-official/bitburner-src#1562]
When I check my stats on the stats page, I see Sleeves even though I am on BN1.1 (Re-playing the game from scratch) while that money was actually spent on Travelling 

![image representing issue](https://github.com/user-attachments/assets/3c477b72-0962-44ac-a13f-23846de1e010)

- Save file:
[bitburnerSave_1723276066_BN1x1.json.gz](https://github.com/user-attachments/files/16568859/bitburnerSave_1723276066_BN1x1.json.gz)

- Version of the game: Bitburner v2.6.2 (633da3830)

**Comment by catloversg** [comment]
It was fixed in #1456.
