### ISSUE TITLE
DOCUMENTATION: API reference ns.weaken() contains "constant" 0.05 which may not be true

### ISSUE THREAD

**Issue by bupjae** [bitburner-official/bitburner-src#1572]
Bitburner v2.6.2 (633da3830)

https://github.com/bitburner-official/bitburner-src/blob/633da383016ad0521f9f1c17cdd99478d2701e41/markdown/bitburner.ns.weaken.md?plain=1#L32

The API document implies that the amount of security decreased is constant 0.05.

However, it may not be true when one of the following is true:
* The number of threads is not 1
* The number of cores is not 1
* BitNode has ServerWeakenRate. (i.e. 11 and 12)

**Comment by bupjae** [comment]
https://github.com/bitburner-official/bitburner-src/blob/633da383016ad0521f9f1c17cdd99478d2701e41/markdown/bitburner.ns.hack.md?plain=1#L36

I just found API document of ns.hack() has similar issue. I think it would be better to remove this line too.

**Comment by d0sboots** [comment]
These values are understood to be per-thread, although given how this is written you wouldn't necessarily understand that.

For hack (and grow), the value truly is constant per-thread; it is not changed by any modifiers or cores. It should remain in the docs 

For weaken, I think it is good to keep the 0.05 constant in there, something like "This function usually lowers the security level of the target server by 0.05 per thread, and only in unusual situations does it do less. Use `weakenAnalyze` to determine the exact current value."
