### ISSUE TITLE
Bladeburner: No Synthoid population but still Synthoid Communities and chaos

### ISSUE THREAD

**Issue by Schlumpf** [bitburner-official/bitburner-src#1575]
After hunting all Synthoids in all cities, there are still communities and chaos.
![grafik](https://github.com/user-attachments/assets/91267d4c-15a4-48f3-b219-6f383a49bd02)
And there are still Messages like:
`[2024-08-13 13:52:16] Intelligence indicates that the Synthoid population of New Tokyo just changed significantly`

That sounds not plausible. Are there still Synthoids or not?

**Comment by catloversg** [comment]
Synthoid Population, Estimated Synthoid Population, and Synthoid Communities are 3 different things:
- Synthoid Population: You cannot access this data. That's the real population.
- Estimated Synthoid Population: This is an estimated number. You can improve its accuracy by performing some actions.
- Synthoid Communities: It's not related to the other two.

**Comment by gmcew** [comment]
To supplement the above;
- chaos is also unrelated to real synthoid population mechnically; it's more general city unrest as a result of your actions rather than active synthoids causing the chaos, lore-wise.
- The `Intelligence indicates that the Synthoid population of CITY just changed significantly` event has a population decreasing and increasing form; same description deliberately so you must correct your population estimate to find which it was. Note this is one of the few ways a city population can increase again.

**Comment by Schlumpf** [comment]
- I understand, that there can be chaos without Synthoid population. That's OK and could make sense.
- The `Est. Synthoid Population` in all citys is `0.000`. I can do `Field Analysis` anywhere after `Intelligence indicates that the Synthoid population of CITY just changed significantly` messages, but the estimated population is still 0.
There are `Tensions between Synthoids and humans lead to riots in CITY! Chaos increased` messags, too. But the est. population is still `0.000`, even after many `Field Analysis`. The message tells, that there have to be Synthoids somewhere.
- Shouldn't the number of communities be linked to the population when the population is approaching 0? It doesn't make sense to have communities without a population, does it?

**Comment by catloversg** [comment]
Can you attach your save file? If Estimated Synthoid Population is always 0, your Synthoid Population may be 0. I can check it for you.

To be honest, some in-game messages and naming is not the best, plot-wise. "Tensions between Synthoids and humans lead to riots in CITY! Chaos increased" just means that the chaos increased. It does not care about Synthoid Population. The "Synthoid Communities" is the same. It's not related to Synthoid Population. The naming is bad, but it's hard to change now.

**Comment by catloversg** [comment]
Can you attach your save file? If Estimated Synthoid Population is always 0, your Synthoid Population may be 0. I can check it for you.

To be honest, some in-game messages and naming are not the best, plot-wise. "Tensions between Synthoids and humans lead to riots in CITY! Chaos increased" just means that the chaos increased. It does not care about Synthoid Population. The "Synthoid Community" is the same. It's not related to Synthoid Population. The naming is bad, but it's hard to change now.

**Comment by Schlumpf** [comment]
Savefile: [bitburnerSave_1723552226_BN10x2_population0.json.gz](https://github.com/user-attachments/files/16611746/bitburnerSave_1723552226_BN10x2_population0.json.gz)

If the population is really 0, I have some suggestions:
- The community count cannot be larger than the population count. If the population decreases, the number of communities should be limited to the number of the population.
- If the population reaches 0, all events with Synthoids like the chaos message above or Synthoids migrating **to** another city should pause. Or chaos could set to 0, too and stop changing while no Synthoids are around. If Synthoids from another city migrate to this city and the population raises, and chaos mechanic can start working again.
- Eventually a new secret achievement for killing all Synthoids?

**Comment by catloversg** [comment]
In your save file, the estimation values of all cities are 0. If Estimated Synthoid Population is 0, Field Analysis (FA) won't help you. You need to do the Tracking contract. There are 4 ways to improve the estimation:
- Tracking: improve it by a "count". It's the only way to improve the estimation after it drops to 0.
- FA, Investigation, Undercover Operation: improve it by a "percentage".

In your case, you need to do the Tracking contract until Estimated Synthoid Population has a "decent" value. 100e3 is fine. After that, you can do FA.

**Comment by Schlumpf** [comment]
OK, that's the information I needed. Many thanks :)
