### ISSUE TITLE
ns.sleeve.setToBladeburnerAction does not provide the list of actions in the method signature

### ISSUE THREAD

**Issue by ficocelliguy** [bitburner-official/bitburner-src#1581]
Recording this issue for Venusaur based on the discussion on the discord suggestions channel
https://discord.com/channels/415207508303544321/415213435974975508/1273346517679472731

Currently setToBladeburnerAction  does not offer any help as to what strings are valid actions:

![image](https://github.com/user-attachments/assets/24c11d5c-ea9d-46a4-9a16-23c59d15567a)

Compare this to sleeve.travel():
![image](https://github.com/user-attachments/assets/09a080e9-1dd9-4bf4-8c49-52b42603af77)

A type could be added to the NetscriptDefinitions file similar to CityName
https://github.com/bitburner-official/bitburner-src/blob/dev/src/ScriptEditor/NetscriptDefinitions.d.ts#L7797

Note that this type should probably be also copied and used in the code that handles the actual sleeve code:
https://github.com/bitburner-official/bitburner-src/blob/dev/src/PersonObjects/Sleeve/Sleeve.ts#L482

**Comment by bupjae** [comment]
For the note, the following sleeve function could be improved with same way:

`setToUniversityCourse(sleeveNumber: number, university: string, className: string): boolean;`
`setToGymWorkout(sleeveNumber: number, gymName: string, stat: string): boolean;`

`university` and `gymName`: subset of `LocationName`
`className`: `UniversityClassType`
`stat`: `GymType`
