### ISSUE TITLE
DOCUMENTATION: behavior of ns.corporation.createCorporation does not match with document.

### ISSUE THREAD

**Issue by bupjae** [bitburner-official/bitburner-src#1582]
Bitburner v2.6.2 (633da3830)

After I read https://github.com/bitburner-official/bitburner-src/blob/633da383016ad0521f9f1c17cdd99478d2701e41/markdown/bitburner.corporation.createcorporation.md ,
I expected that `ns.corporation.createCorporation` would return false if the creation of corporation has been failed in anyway. i.e.

1) You don't have access to corporation. (i.e. you don't have sf3 and you are not in bn3)
2) You already have corporation
3) Corporation name is not given
4) You selected to seed-money but you are not in bn3
5) Current bn doesn't allow to create corporation
6) You selected to self-fund but you don't have enough money

I expected that all of these case returns false.

However, in current implementation https://github.com/bitburner-official/bitburner-src/blob/633da383016ad0521f9f1c17cdd99478d2701e41/src/Corporation/Actions.ts , 1, 2, 3, 6 returns false, while 4, 5 throws error.

**Comment by bupjae** [comment]
I was kinda liked to modify game code to match documentation. But either way is OK.

**Comment by d0sboots** [comment]
IMO all but (maybe) 6 should throw, as they indicate programmer error instead of an unexpected game state. But many of them are arguable, and it's not a big enough deal that it's worth breaking the API over.
