### ISSUE TITLE
API: Adjust ns.getPurchasedServers() RAM cost

### ISSUE THREAD

**Issue by Faenre** [bitburner-official/bitburner-src#1600]
(Version 2.6.2)

## Context

Discord user Nolshine noticed that the cost for `NS.getPurchasedServers()` is disproportional to its value and the other functions in its design space.

| Function | RAM cost |
| --- | --- |
| [NS.getPurchasedServerLimit()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.getpurchasedserverlimit.md) | 0.05 GB
| [NS.getPurchasedServerMaxRam()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.getpurchasedservermaxram.md) | 0.05 GB
| [NS.getPurchasedServerUpgradeCost()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.getpurchasedserverupgradecost.md) | 0.1 GB
| [NS.getPurchasedServerCost()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.getpurchasedservercost.md) | 0.25 GB
| [NS.getPurchasedServers()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.getpurchasedservers.md) | **2.25 GB**
| [NS.scan()](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.scan.md) | 0.2 GB

Worth noting, there are many ways to avoid paying this price together, including:
- Scanning `home` and filtering the results (0.2 GB)
- Wrapping `getPurchasedServerUpgradeCost` in a `try { } catch { ; }` block and incrementing a counter (0.1 GB)
- Maintaining a `pservs.txt` list (0 GB)
- Writing data into ports for each server (0 GB)
- Hard-coding your pserv names into the manager (0 GB)

## Problem

Several of the "solutions" require re-architecting code, or having deeper game awareness, to solve what should be a very simple task: getting a list of purchased servers and then moving on. This doesn't seem like it _should_ be a Problem though, here, unless you're getting into deep RAM optimization, which should generally be more important than workers than managers (unless you're getting into wide multi-manager networks, but that's deep into endgame territory).

I feel like it's an antipattern to teach players to avoid using the API, and while optimization and ram-reduction can definitely be rewarding, the steeper price of 2.25 sends the message that "I should do everything myself". Which is fine, rolling your own can often be better. Besides, hard-coding is free, why not do that? But libraries are supposed to be meaningfully convenient. Managers are an opportunity to teach players better coding habits though, like relying on libraries when they are helpful and optimizing after the fact; especially since the problem space for managers is supposed to be about formulaic thinking, not performance-squeezing.

## Solution

I propose the `NS.getPurchasedServers()` function be reduced to 0.5GB, 1 GB, or 1.5 GB. These feel in line with the fact that `NS.scan('home')` costs 0.2 GB and also returns these values, and the only hard part is filtering them (which can be done for about 0.05-0.1 GB). The values I suggested are all more affordable, while still offering room for DIY improvement. Just as importantly, they encourage healthy API awareness without looking at the API as being a player trap.

I'm happy to make the PR if this sounds agreeable and we can agree on a number.

**Comment by Nolshine** [comment]
Well, adding my two-cents as promised will be difficult when you've so perfectly summarised my opinion on the matter. I should add that one more function related to pservs that costs 2.25GB is `ns.purchaseServer()`, but since that action has some associated weight, maybe that makes sense. No (legitimate) means (that I know of) exist to circumvent the cost for that action either. But then `ns.upgradePurchasedServer()` only costs 0.25GB. So it feels kind of inconsistent. Not sure how related that is to the issue proposed here but it is a part of the thought process that brought me to opening the discussion in the discord.

**Comment by d0sboots** [comment]
The disparity between `ns.purchaseServer` and `ns.upgradePurchaseServer` leads to some potentially interesting choices (or it can be ignored). For instance, you can have one script that buys all the servers with only 1GB of initial RAM, and this will be very cheap to do. Then your main script only needs to upgrade them, reducing the RAM cost.

However, as an information-only API, NS.getPurchasedServers() does feel overly expensive for what it does. Lemme start a fight in general and see what others think XD

**Comment by Faenre** [comment]
Speaking of interesting choices, `ns.getServer()` is similar in that the most common use-cases for it can be done with _other_ functions for 0.1 or 0.05 GB. However, getServer() bundles -multiple- other functions, returns a ton of useful information (including `purchasedByPlayer`), and still comes in at less than this.

Honestly, the more I look at this, I kinda want to suggest this function should cost **0.25 GB** and be done with it altogether. `ns.getPurchasedServers()` has the same effect as the below 0.2 GB function:

```js
const pservs = ns.scan("home").filter((host) => host.startsWith("pserv"))
```

I realize there's something to be said for learning to optimize your own code but at this point it's just a QOL feature, and a 25% upcharge feels fine for that.
