### ISSUE TITLE
Infinite loading when date is too far in the past

### ISSUE THREAD

**Issue by kibogdan** [bitburner-official/bitburner-src#1629]
[bitburnerSave_777811909_BN1x1.json.gz](https://github.com/user-attachments/files/16740969/bitburnerSave_777811909_BN1x1.json.gz)

I changed the date on the pc to 1994, trying to get an achievement, and got an infinite loading
this save file causes the same problem in the web version

Bitburner v2.6.2 (216bf616)

![image](https://github.com/user-attachments/assets/ca7196a3-dacf-44f1-a577-88c5c66fee17)

**Comment by catloversg** [comment]
When you set your machine's current date back too far, the offline time is too long. When we load a save file, we will calculate the offline time and generate coding contracts based on it. In this case, the game is trying to generate ~390e3 contracts. That's why it freezes. I'll change how we calculate the number of "bonus" contracts to fix this problem.

In the meantime, you should load your backup. If you don't have any backup, I can edit your save file to "rollback" your change of time.

**Comment by d0sboots** [comment]
Thanks for the analysis, I knew it had to be some offline-time calculation but most things just add bonus time. I guess we might need bonus time for contracts too...

**Comment by kibogdan** [comment]
I don't have any backup( @catloversg, could you help me? (thank you in advance)

**Comment by catloversg** [comment]
Here you are.
[bitburnerSave_1724667347_BN1x1.json.gz](https://github.com/user-attachments/files/16747357/bitburnerSave_1724667347_BN1x1.json.gz)

**Comment by kibogdan** [comment]
I've tried to load from file and it doesn't help me. 
I have a screen recording that shows this [https://drive.google.com/file/d/1b1cQ-RIezeAm4ILyjrMwT121sIs98UNf/view?usp=drive_link](url)

**Comment by catloversg** [comment]
Your link is protected. You can upload it here (GitHub).

**Comment by kibogdan** [comment]
I can't uploaad it here 'cause it's too big(224mb 2:50)
I've opened the link

**Comment by catloversg** [comment]
Your screen recording shows that Steam cannot launch the game. It has nothing to do with the save.
- Verify that my save file works by importing it on https://bitburner-official.github.io/
- Restart your machine.
- Disable Steam Cloud for Bitburner.
- Uninstall Bitburner.
- Make sure that there are no remaining data of Bitburner.
- Install Bitburner.
- Make sure that Steam Cloud for Bitburner is disabled.
- Open Bitburner. It will show a new save file.
- Import my save file.

**Comment by kibogdan** [comment]
I've tried your safe file in web version, and it isn't working (same problem)

**Comment by catloversg** [comment]
I just loaded it, and it worked. I need more information than "it isn't working".

**Comment by kibogdan** [comment]
I'm sorry. I've upload it to web version which had the same problem (in another browser it worked)

**Comment by catloversg** [comment]
In that case, you can try to clear the data of the browser that you imported the problematic save file. You can search "'browser name' clear data for one site". For the Steam version of Bitburner, you can try my steps.

**Comment by kibogdan** [comment]
It worked!!!!!!!!
Thank you so much)

**Comment by d0sboots** [comment]
Reopening this as it's still a generally relevant issue, and this is the bug with the most info
