### ISSUE TITLE
The sellShort() return value is incorrect

### ISSUE THREAD

**Issue by jcbollinger** [bitburner-official/bitburner-src#1633]
Version: BitBurner v2.6.2 (633da3830)

The documentation for `ns.stock.sellShort()` says that its return value is the sale price per share.  Therefore, I expect the money gained from a short sale to be the product of the sale price times the number of shares sold, less the commission.  That is not the case in practice.

This script demonstrates:
```
export async function main(ns) {
  const commission = ns.stock.getConstants().StockMarketCommission;
  const numShares = 100;
  const purchasePrice = ns.stock.buyShort("MGCP", numShares);

  const initialMoney = ns.getPlayer().money;
  const salePrice = ns.stock.sellShort("MGCP", numShares);
  const finalMoney = ns.getPlayer().money;

  ns.tprintf("Starting money: $%d\n" +
             "Sold %d shares @ $%d / share (commission %d)\n" +
             "Final money:    $%d\n" +
             "Expected final: $%d",
    initialMoney, numShares, salePrice, commission, finalMoney,
    initialMoney + numShares * salePrice - commission);
}
```
The last two lines of terminal output should print the same number, but they consistently do not.  (Tested in BN 8 with no other scripts running, so there's no chance of unexpected income.)  For example:
```
[home /]> run /test/short-sale-test.js 
Running script with 1 thread(s), pid 63 and args: [].
Starting money: $3807518788371131
Sold 100 shares @ $11112 / share (commission 100000)
Final money:    $3807518789360311
Expected final: $3807518789382426
```

**Comment by bupjae** [comment]
The return value of sellShort() is the stock price at which each share was sold.
However, this is not equal to "unit sell price" for selling short position.

When you sell short position, you gain "some amount" of money so that the final profit becomes `({average price the player owns in short position} - {current stock price}) * numShares - comission`

**Comment by jcbollinger** [comment]
> The return value of sellShort() is the stock price at which each share was sold. However, this is not equal to "unit sell price" for selling short position.
> 
> When you sell short position, you gain "some amount" of money so that the final profit becomes `({average price the player owns in short position} - {current stock price}) * numShares - comission`

Ok. I think that by "final profit" you mean "the net change in money from buying short and then selling the short position".  Your formula makes sense to me in that context. In that case, since I pay in money to buy a short position (unlike in the real stock market), that would mean that when I sell the short position, I should get back my initial investment +/- an adjustment based on the differential between the (average) price I paid and the price at the time I sold.  The differential component is then the profit. That is:
```
export async function main(ns) {
  const commission = ns.stock.getConstants().StockMarketCommission;
  const numShares = 100;
  const purchasePrice = ns.stock.buyShort("MGCP", numShares);
  const initialMoney = ns.getPlayer().money;
  const salePrice = ns.stock.sellShort("MGCP", numShares);
  const [longShares, longPriceAvg, shortShares, shortPriceAvg] = ns.stock.getPosition("MGCP");
  const finalMoney = ns.getPlayer().money;

  ns.tprintf("Starting money: $%d\n" +
             "Sold %d shares @ $%d / share (commission %d)\n" +
             "Final money:    $%d\n" +
             "Expected final: $%d",
    initialMoney, numShares, salePrice, commission, finalMoney,
    initialMoney + numShares * (2 * shortPriceAvg - salePrice) - commission);
}
```
But that's still not predicting the actual money I receive from the sale:
```
[home /]> run /test/short-sale-test.js 
Running script with 1 thread(s), pid 76 and args: [].
Starting money: $2883684654712
Sold 100 shares @ $18502 / share (commission 100000)
Final money:    $2883686382854
Expected final: $2883682704433
```
Now, I seem consistently to be gaining much more from my short sales than I predict, so that's a problem that I can live with, but I would sure like to be able to predict correctly.

**Comment by jcbollinger** [comment]
The behavior seems to be correct after all, so closing.
