### ISSUE TITLE
Game can get "soft bricked" when modifiying BitNode list

### ISSUE THREAD

**Issue by elliecolorado** [bitburner-official/bitburner-src#1650]
# Steps
·Exported a save with the "export" in the settings tab.
·Opened the save file in VSCode, without unzipping the .gz file.
·Modified it to include all bitnodes to level 3 (changed the "sourceFiles" list).
·Saved the change and accepted the changes when 7zip showed the "The file 'save' was modified. Do you want to update it in the compressed file?" popup.

When I imported it back again and the game reloaded, it didn't load at all. I tried:
·Killing all scripts (from game and from steam game initializing options)
·Loading previous saves
·Reinstalling
·Deleting all save and game files before reinstalling.
·Turning cloud saves off before deleting all save and game files and reinstalling.

At one point, I tried this:
1) Turned cloud saves off.
2) Deleted all Bitburner files and saves.
3) Uninstalled the game.
4) Restarted the PC.
5) Installed it again. 

When entering it, it showed me the option to import a save from two years ago (which I thought would have already been deleted), or continue with a clean new game.

I didn't import the old save, so I had a clean new game. Then:
1) Imported an unmodified recent save and it worked.
2) Modified the file again, changing part of the bitnodes (I had [1,2] and [4,1], and added bitnodes [2,2] and [3,2]), and it works.
3) Modified it again to set all four to level 3 and it works.
4) Modified it again to add all bitnodes 1 to 11 to level 3 and the bug happens.
5) Modified it again to add all bitnodes 1 to 9 to level 3 and the bug happens.

Uninstalling, restarting the PC, and installing again alone doesn't solve the loading part either.

# Game version
Bitburner v2.6.2 (633da3830)

# OS
Windows 11

# Broken save file
[bitburnerSave_1726087623_BN4x2.json.gz](https://github.com/user-attachments/files/16975857/bitburnerSave_1726087623_BN4x2.json.gz)

**Comment by elliecolorado** [comment]
When I modified it the last two times (bitnodes 1 to 11, and then 1 to 9) I made sure it worked before modifying it again each time.

**Comment by catloversg** [comment]
Modifying the save file is a "dangerous" action:
- It can brick your save file if you are not careful.
- Generally, we don't fix any problem caused by loading an edited save file.

A hint for your problem: When you have SF9, the game expects Hacknet Servers, not Hacknet Nodes. In your save file, you still have Hacknet Nodes while having SF9.

**Comment by elliecolorado** [comment]
> Modifying the save file is a "dangerous" action:
> 
>     * It can brick your save file if you are not careful.
> 
>     * Generally, we don't fix any problem caused by loading an edited save file.
> 
> 
> A hint for your problem: When you have SF9, the game expects Hacknet Servers, not Hacknet Nodes. In your save file, you still have Hacknet Nodes while having SF9.

That makes sense. I will try removing BN9. Thanks for the hint and sorry for the inconvenience.

**Comment by elliecolorado** [comment]
Its, in fact, just the SF9 existing while not having Hacknet Servers
