### ISSUE TITLE
Singularity.workForFaction() documentation remarks

### ISSUE THREAD

**Issue by PyroGenesis** [bitburner-official/bitburner-src#166]
Bitburner version: 2.1.0

The remarks in the documentation for `ns.singularity.workforfaction()` in `markdown/bitburner.singularity.workforfaction.md` seem to be incorrect?

The remarks say you will not receive your reputation until you finish the task and provides a workaround which keeps restarting `workforfaction()` every 60 seconds. But I just tried it out in bitburner and I do get the reputation right away, and `getFactionRep()` reflects it correctly as well.

**Comment by quacksouls** [comment]
Thank you for this.  You're right.  Since v2.0 of the game, when you work for a faction you immediately get the reward.  The documentation of `ns.singularity.workforfaction()` should be updated to reflect the new work mechanic in v2.0.  Please see PR #168.
