### ISSUE TITLE
Script-Editor throws Errors

### ISSUE THREAD

**Issue by Mathekatze** [bitburner-official/bitburner-src#1667]
Without even having a file opened, switching to the script editor causes the following error. It also occurs with opened files and pops up repeatedly while typing in code. This is getting in the way when trying to edit my scripts.

UNCAUGHT PROMISE ERROR
You forgot to await a promise
maybe hack / grow / weaken ?

RUNTIME ERROR:

n is null
stack:
self.onmessage/</<@https://bitburner-official.github.io/dist/ts.worker.js:37:4820577
self.onmessage/<@https://bitburner-official.github.io/dist/ts.worker.js:37:4820970
loadForeignModule@https://bitburner-official.github.io/dist/ts.worker.js:37:187031
_handleMessage@https://bitburner-official.github.io/dist/ts.worker.js:37:136880
handleMessage@https://bitburner-official.github.io/dist/ts.worker.js:37:136493
_handleRequestMessage@https://bitburner-official.github.io/dist/ts.worker.js:37:135285
_handleMessage@https://bitburner-official.github.io/dist/ts.worker.js:37:134726
handleMessage@https://bitburner-official.github.io/dist/ts.worker.js:37:134613
onmessage@https://bitburner-official.github.io/dist/ts.worker.js:37:136585
o/self.onmessage@https://bitburner-official.github.io/dist/ts.worker.js:37:207766

[bitburnerSave_1727366068_BN1x1.json.gz](https://github.com/user-attachments/files/17152094/bitburnerSave_1727366068_BN1x1.json.gz)

game version: Bitburner v2.6.2 (633da3830)

**Comment by catloversg** [comment]
I cannot reproduce your issue with your save file. The stack trace shows an issue with monaco editor (it's the code editor that you are using). Can you reload your browser, try playing on another browser, or use Steam app?

**Comment by Mathekatze** [comment]
This appears to have been caused by some interaction with the NoScript-plugin. Changing the NoScript-settings for bitburner has fixed the problem.
