### ISSUE TITLE
[Feature] Direct JSON file reading

### ISSUE THREAD

**Issue by KaBlaize** [bitburner-official/bitburner-src#1688]
Hello there,

I play this game for years.. and now I have rebuilt my entire script collection 3 times and using JSON for storing configs for a few scripts. 

I'd be interested in implementing JSON file reading if you agree on implementing it.

It would be like simple:
(I know it's not the preferred way to implement.. it's just for explanation)

``` JavaScript
NS.prototype.getConfig(filePath, defaultValue) {
  if (!ns.fileExists(filePath)) {
    ns.write(filePath, JSON.stringify(
      defaultValue, 
      null, 
      2
    ))
   }

  return JSON.parse(ns.read(filePath))
}

```

I know it's not much.. but it can make other players playing with the idea to store config in JSON files.

Please think about it, I have a little time for work with the source code.

Regards,
KaBlaize

**Comment by d0sboots** [comment]
You've pretty much hit on exactly how this would be implemented... and it can be implemented that way in user code. In general, we usual leave stuff like this up to the players, when it is easy for players to create for themselves. It provides an obvious "hook" for people to get started with. Some stuff in the game is even a little bad on purpose, for just this reason.

**Comment by catloversg** [comment]
I agree with d0sboots here. This kind of simple utility function should be in the "userland".
