### ISSUE TITLE
Work formulas are broken

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#169]
1. `ns.formulas.work.classGains(ns.getPlayer(),"algorithms","Summit University")` throws `Cannot read properties of undefined (reading 'earnings')`
1. `ns.formulas.work.factionGains(ns.getPlayer(),"field",1)` throws `Cannot read properties of undefined (reading 'hackExp')`
1. `ns.formulas.work.crimeGains("DRUGS")` does not require owning Formulas.exe (also crime types are case sensitive [`ALL CAPS`](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Crime/CrimeHelpers.ts#L20) while [courses](https://github.com/bitburner-official/bitburner-src/blob/dev/src/PersonObjects/Sleeve/Sleeve.ts#L223), [locations](https://github.com/bitburner-official/bitburner-src/blob/dev/src/PersonObjects/Sleeve/Sleeve.ts#L342), [universities](https://github.com/bitburner-official/bitburner-src/blob/dev/src/PersonObjects/Sleeve/Sleeve.ts#L202), and [work](https://github.com/bitburner-official/bitburner-src/blob/dev/src/NetscriptFunctions/Singularity.ts#L931) [types](https://github.com/bitburner-official/bitburner-src/tree/dev/src/PersonObjects/Sleeve/Sleeve.ts#L311) are all case insensitive / lower case (Faction names, however, are [case sensitive CamelCase](https://github.com/danielyxie/bitburner/blob/dev/src/Faction/data/FactionNames.ts), just to buck trend as well)).

- [x] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.1.0 (8f4636cb)

**Comment by fdellwing** [comment]
```javascript
ns.tprint(ns.formulas.work.factionGains(ns.getPlayer(),"SECURITY",1))
ns.tprint(ns.formulas.work.classGains(ns.getPlayer(),"ALGORITHMS","Summit University"))
```

ClassType and FactionWorkType are case sensitive:

https://github.com/bitburner-official/bitburner-src/blob/19e8946d9aed90a26be35b8f8999238cdd70d5e5/src/Work/ClassWork.tsx#L14-L27

https://github.com/bitburner-official/bitburner-src/blob/19e8946d9aed90a26be35b8f8999238cdd70d5e5/src/Work/data/FactionWorkType.ts#L1-L5

But they should probally be handled case insensitive.

**Comment by Draco18s** [comment]
Sorry, but while the definitions might be in all-upper, but they get cast to lower when used:

https://github.com/bitburner-official/bitburner-src/blob/0519b6adf7ad07b992297ef4ef7370eb90798b15/src/PersonObjects/Sleeve/Sleeve.ts#L223

So, no, you're incorrect.

**Comment by fdellwing** [comment]
They might be in other cases, but not in the formulas API:

https://github.com/bitburner-official/bitburner-src/blob/d74c380e4218ca9990d389c686eb268cfaeefef4/src/NetscriptFunctions/Formulas.ts#L370-L384

They are used exactly like you pass them to the function. If you run the 2 lines of code I posted above, you will see that they totally work.

But there are things that should be changed:

1. Change the user deployed type string to all uppercase before passing it to the next function
2. Validate you got a valid type and if not return an error and do not crash in the game code

The error in `factionGains` is from this line:

https://github.com/bitburner-official/bitburner-src/blob/d74c380e4218ca9990d389c686eb268cfaeefef4/src/Work/formulas/Faction.ts#L47

as `baseStats` is undefined.

**Comment by AlexeyKozhemiakin** [comment]
Shall there be an netscript API to expose correct values for Work Type, Crime Types, list of univercities and class types?

**Comment by Draco18s** [comment]
> Shall there be an netscript API to expose correct values for Work Type, Crime Types, list of univercities and class types?

Yeah, that'd be nice.

> They are used exactly like you pass them to the function. If you run the 2 lines of code I posted above, you will see that they totally work.

Doesn't mean they're not broken. If you pass an invalid string to crimeGains (and several other things) you'll get "not a valid type" error. Eg:

    Invalid crime type: INVALID

Null Reference Exceptions (which is what "Cannot read properties of undefined" is in JS parlance) is a type of Boneheaded Exception. From [Vexing Exceptions](https://ericlippert.com/2008/09/10/vexing-exceptions/):

> **Boneheaded exceptions** are *your own darn fault,* you could have prevented them and therefore they are bugs in your code. You should not catch them; *doing so is hiding a bug in your code.* Rather, you should write your code so that the exception cannot possibly happen in the first place, and therefore does not need to be caught. That argument is null, that typecast is bad, that index is out of range, you’re trying to divide by zero – these are all problems that you could have prevented very easily in the first place, so prevent the mess in the first place rather than trying to clean it up.

The game should tell me that the string I passed in *is not a valid string* rather than trying to read from an undefined value.

Oh and also, they don't *actually* require Formulas.exe, so they're still broken even if the string casing is correct (or the documentation is wrong, as the docs say anything under `ns.formulas` requires Formulas.exe and none of the work ones do). ;)

Oh and other functions do work just fine with all-lower case, such as `ns.sleeve.setToFactionWork(sleeveNum,factionName,"hacking");`

**Comment by fdellwing** [comment]
Do you actually read more than the first sentence that I write?

**Comment by Draco18s** [comment]
> Do you actually read more than the first sentence that I write?

I did. I fixed my local scripts, but I'm still pointing that the game is flawed. Just because there *are* valid strings doesn't mean there's *not a bug.* The bug is that if you pass in an invalid string the game chokes on it. On top of that, what strings are considered valid are *inconsistent* between different functions.

So, same question back at you. You have not shown that there is not a bug.

**Comment by fdellwing** [comment]
> So, same question back at you. You have not shown that there is not a bug.

I did never say that there is no bug!

Even in my first answer:

> But they should probally be handled case insensitive.

This there my suggestions on how the **game** code needs to be changed:

> But there are things that should be changed:
>
>    1. Change the user deployed type string to all uppercase before passing it to the next function
>    2. Validate you got a valid type and if not return an error and do not crash in the game code

**Comment by Draco18s** [comment]
> This there my suggestions on how the game code needs to be changed:

Ok, I will admit that I misread that section. The way it was phrased seemed to suggested that **I** had to change what I was doing (because of the use of `you`).

**Comment by Snarling** [comment]
Some of the categories need to be more directly exposed to the player as enums and as documentation, similar to how ns.enums.CrimeType is exposed in the most recent dev builds, and the expected type for ns.singularity.commitCrime is directly documented in the function as expecting either a CrimeType enum member or as one of the valid strings.

![image](https://user-images.githubusercontent.com/84951833/198870616-b123adbc-5e15-45c3-978a-db6674b30daa.png)

**Comment by Snarling** [comment]
But also, the game should accept non-capitalized versions of these inputs anyway, or even fuzzy matches (as it currently works with crime functions)

Some TODOs for/relating to this issue:

* ~~Expose a FactionWorkType enum to player.~~ Done
* ~~Document functions that take in a FactionWorkType as needing members of this enum, or any of the string literals that are in that enum (see example using CrimeType above).~~ Done
* ~~Same as above for ClassWorkType~~ Done
* Modify functions that take in these inputs to actually be case-insensitive. Optionally implement a fuzzy matching system similar to the findCrime function that crime functions use.
* ~~Add a companyGains function and associated CompanyWorkType enum, with same treatment as above.~~ Done
* Standardize casing for all of these WorkType enums as either all lowercase or as all uppercase. Will require handling loading a save that has the old capitalization.
* ~~Add missing formulas API checking for work formulas~~ Done
