### ISSUE TITLE
manualHack(), but nothing for growth and weaken

### ISSUE THREAD

**Issue by Te-M** [bitburner-official/bitburner-src#1690]
A bit of a spoiler, but _ns.singularity_ has a terminal hack but not the same for the other two.  Might also be fun to add the BasicHGWOptions.stock? options to the _ns.singularity_ functions from the normal _ns_ equivalents as a bit of a bonus even though technically you can't do it manually.

**Comment by catloversg** [comment]
I don't get what you want here. Are you suggesting equivalent APIs for `grow` and `weaken` (`manualGrow` and `manualWeaken`)? If that's the case, you will have to explain why it's necessary.

In the past, we did not have the `backdoor` CLI and the `ns.singularity.installBackdoor`. `manualHack` had been the only API that allowed installing a backdoor on servers. There was/is no need for `manualGrow` and `manualWeaken`. It's the same with the suggestion of `BasicHGWOptions`. That option is only relevant for the normal `ns.hack`.

**Comment by d0sboots** [comment]
Manual hacking (from the commandline) is also slightly different in that it effects intelligence and works faster, and the singularity function replicates this behavior. But grow/weaken don't have that bonus IIRC, the terminal versions just work the same as the API versions.
