### ISSUE TITLE
BladeBurner Overclock skill seems sub-optimal

### ISSUE THREAD

**Issue by BanovMiroslav** [bitburner-official/bitburner-src#1692]
Overclock makes tasks faster, but the reward for tasks is calculated directly proportional to time. And you just end up depleting your contracts faster, and not gaining anything from it.

I guess if you just want to end the bitnode fast using Black Ops, Overclock skill makes that faster so it's good for that?

- Version of the game 2.6.2

**Comment by catloversg** [comment]
What does "sub-optimal" mean in this context? Generally, Overclock is one of the best skills. It reduces the action time of all actions, and rewards of some actions don't depend on time. Having a high reward is not always good, especially when it takes too long to complete the action. For an optimal run that uses Bladeburner route, Overclock is definitely one of the top priority skills.

**Comment by BanovMiroslav** [comment]
Hm, actually I am looking at the code again and it seems that the xp increase is calculated based on time, but other things like rank and money doesn't seem to be. I kind of felt it was too slow of a bitnode and I was investigating why it was so. I thought I was lured into investing in Overclock for nothing. I didn't play very optimal, and I did a lot of training, and also I even Incite Violence, both were not worth it.

I am closing close this ticket, sorry for the trouble.
