### ISSUE TITLE
Official code documentation is hard to find

### ISSUE THREAD

**Issue by JohannesPertl** [bitburner-official/bitburner-src#1696]
The [link to the official documentation](https://github.com/bitburner-official/bitburner-src/blob/stable/markdown/bitburner.ns.md) for NS is only located in the `Scripts Editor` ingame. 
This is confusing for new users, as it should also be included in the `Documentation` page of the sidebar, especially because of the deprecated Beta RTD. 

Suggestions:

- Add the link to the `Resources` section of the ingame Documentation page
- Add the link to the main `README.md`
-  Add a disclaimer that https://bitburner-beta.readthedocs.io/en/latest/index.html is deprecated, as it is the first result on google

**Comment by catloversg** [comment]
Most of your suggestions were implemented on the dev branch. Updating `README.md` will be handled by #1697.
