### ISSUE TITLE
Embed a font

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#17]
[theit8514]
![unknown](https://user-images.githubusercontent.com/1175401/147937778-44d927e6-f5e4-473e-b39a-a8c6da3e2e8c.png)

MacOS uses by default a Mac-specific font. These fonts are missing the Unicode characters for minimize and restore. Potential solution is to change the unicode symbols used, or embed a font with those symbols.

**Comment by Snarling** [comment]
Not sure if the original issue is still a thing, but embedding a default font is a good idea.
