### ISSUE TITLE
SleeveWorkGains available in documentation, but not in NS scripts

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#170]
[This page](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.sleeveworkgains.md) and [type def](https://github.com/danielyxie/bitburner/blob/73bcf0870f2ad5f995391bca7cb53e772a10ab9f/dist/bitburner.d.ts#L6606) exist, but there does not appear to be any code that constructs, returns, or otherwise deals with this interface.

Either the type def (and therefor doc) need to be removed, or a method of obtaining this information needs to be exposed.

- [x] Version of the game, e.g. Bitburner v2.1.0 (8f4636cb)

**Comment by AlexeyKozhemiakin** [comment]
Yes! 
I'd like to work on adding capabilities to get sleeve gains info in order to make a decision which crimes is more profitable\gives more experience.

Shall it be exposed as the extension Formulas or separate Sleeve API?

**Comment by Snarling** [comment]
Removing the SleeveWorkGains interface makes more sense.

ns.formulas.work already has functions for determining gains for an arbitrary player-like object performing a particular task, and the return types are a WorkStats object which has all the same information as the unused SleeveWorkGains interface. Adding a `ns.sleeve.getSleeve(i)` function (similar to the existing `ns.getPlayer()`) would allow the already-existing formulas functions to just work with sleeves.

**Comment by Draco18s** [comment]
tbh, I think work gains for sleeves should just be a part of the sleeve API, at least for the sleeve's *active* task (although getting all the data for every possible task just requires cycling through the list and cataloging, so...maybe not that).

For the time being I have a janky solution for which job to work for by roughly sorting [all the possible strings](https://github.com/bitburner-official/bitburner-src/blob/19e8946d9aed90a26be35b8f8999238cdd70d5e5/src/Company/data/companypositionnames.ts) first by ordering each *category* (so part time work, then misc work, Software Consultant, Business Consultant....) based on my own experience on how well each pays (business pays better than software, agent pays better than almost anything else...) and then taking the index of the category and the index of the job title within that category and adding them together.

Which makes something like "Network Administrator" worth "6" and "Security Officer" worth "9" (unitless values, as its just a rough sorting order). It's not perfect, but it's close enough for now.

---

As an aside, it appears that `ns.formulas.mockPlayer()` is meant to handle some stuff dealing with sleeves: create one, assign the sleeve's stats, and it can get plugged into any method that accepts a `Player` object.

*test*

Actually that works. Just compared the result with the UI and it's spot on; only thing is, we need #165 merged in order to do that with companies. It's a bit round-a-bout than just querying "get me this sleeve's gains doing job Y" but I can work with it if I have to.

    export async function main(ns) {
	    var p = ns.formulas.mockPlayer();
	    p.skills.hacking = 110;
	    p.skills.strength = 109;
	    p.skills.defense = 109;
	    p.skills.dexterity = 109;
	    p.skills.agility = 109;
	    p.skills.charisma = 105;
    
	    ns.tprint(ns.sleeve.getInformation(0).mult)
	    ns.tprint(ns.formulas.work.factionGains(p,"FIELD",1));
    }
`{"agility":1,"agilityExp":1.1,"charisma":1,"charismaExp":1.1,"companyRep":1.265,"crimeMoney":1,"crimeSuccess":1,"defense":1,"defenseExp":1.1,"dexterity":1,"dexterityExp":1.1,"factionRep":1.265,"hacking":1.179675,"hackingExp":1.1,"strength":1,"strengthExp":1.1,"workMoney":1.1}`
`{"money":0,"reputation":0.11035132867132867,"hackExp":2,"strExp":2,"defExp":2,"dexExp":2,"agiExp":2,"chaExp":2,"intExp":0}`

(You'll have to do that math by hand)

![image](https://user-images.githubusercontent.com/1750680/198870217-242d7c7c-70ea-4434-82ab-44e13743455f.png)

**Comment by Draco18s** [comment]
@Snarling got it in one while I was dickering around. :+1:

**Comment by AlexeyKozhemiakin** [comment]
> Removing the SleeveWorkGains interface makes more sense.
> 
> ns.formulas.work already has functions for determining gains for an arbitrary player-like object performing a particular task, and the return types are a WorkStats object which has all the same information as the unused SleeveWorkGains interface. Adding a `ns.sleeve.getSleeve(i)` function (similar to the existing `ns.getPlayer()`) would allow the already-existing formulas functions to just work with sleeves.

I drafted the changes here https://github.com/AlexeyKozhemiakin/bitburner-src/commit/8e5f614795f8be0690039480d825a6aef4b19b3d

GetSleeve api already exists in form of GetSleeveInformation which has a typo in typedefinition - Mult, not Mults as Person should have to be interchangeable. How to handle this? Move to next version as breaking changes?

**Comment by Draco18s** [comment]
I'd change it to `mults`, yeah. I don't think all that many people are using it right now.
Might be able to alias it though, eg. `mult => mults`
