### ISSUE TITLE
If server is already backdoored, backdooring it again shouldn't work.

### ISSUE THREAD

**Issue by SansForSSBU** [bitburner-official/bitburner-src#1702]
If you connect to a server which you have already backdoored and backdoor it again, you get a loading bar and wait for the backdoor to happen. Instead of this, a message should show up that you've already backdoored the server and don't need to backdoor it again.

Game ver: Bitburner v2.6.2 (633da3830)

**Comment by catloversg** [comment]
Warning: There is a major spoiler of the endgame content ahead.

There are 2 potential meanings of this suggestion:
- Add a warning message for `backdoor` CLI. [1]
- Change the behavior of `backdoor` CLI and the `singularity.installBackdoor`: If a server has already been backdoored, we would not do anything and just print a warning message.

[1] is probably fine. I'll do that if @d0sboots agrees.
[2] is a different matter. I don't think we will do that. Installing a backdoor on WD triggers the end of the current BN. That action is important.

**Comment by SansForSSBU** [comment]
I'm referring to meaning [1], the early-game meaning where you're just trying to backdoor everyone and might do it by just looking through the result of running `scan`, then find that you're wasting time looking at loading bars when you've already backdoored this server.

**Comment by catloversg** [comment]
A small clarification: even if we add a warning message, everything else will be the same (the waiting time, the effect/benefit of "backdoor-ing" a server, etc.). That warning message may not be very useful for you.

**Comment by d0sboots** [comment]
Yeah, adding a "Note: You have already backdoored this server" seems fine for the CLI as a convenience, but it shouldn't actually change anything about what it's doing. Just an aid for your memory.

**Comment by gmcew** [comment]
The manual terminal command `analyze` can be used to determine if the connected server is backdoored, and that result is also available programmatically as part of `getServer`.

I'd view re-backdooring the same server and wasting a few seconds the minor inconvenience to encourage implementing some pre-backdoor checking logic. It may be worth highlighting that this information is available before attempting the backdoor as part of the CLI note?

**Comment by JkktBkkt** [comment]
Should a similar note be applied to the non-CLI method's output as well?
I had no idea there is an accessible field before looking through the source here and issues, as other fields returned by ns.getServer that I use are easily accessible through other methods.
