### ISSUE TITLE
API: ns.singularity.getCurrentWork().completion (when grafting) returns an empty object.

### ISSUE THREAD

**Issue by alainbryden** [bitburner-official/bitburner-src#1706]
When grafting an augmentation, `ns.singularity.getCurrentWork()` returns an object such as this:
```js
{
  "type": "GRAFTING",
  "cyclesWorked": 3692,
  "augmentation": "Bionic Legs",
  "completion": {}
}
```
It looks like "completion" is just an empty object. I expected it to be e.g. a decimal between 0.0 and 1.0

It's also not terribly clear what "cyclesWorked" infers. An expert player might know that a cycle is 200ms, in which case a player can use this in combination with `ns.grafting.getAugmentationGraftTime` to infer the completion / time remaining, but that's quite a bit to infer.

All that said, an argument could be made that the ability to `await ns.grafting.waitForOngoingGrafting()`, as well as the progress that is automatically displayed on the HUD, makes it relatively low-priority to surface this information to the API.

**Comment by d0sboots** [comment]
I agree that the "completion" thing is weird. The ship has probably sailed on "cyclesWorked".
