### ISSUE TITLE
The Knowledge of Apollo augment ruins the wire cutting game and makes it unplayable.

### ISSUE THREAD

**Issue by ProtoDolph** [bitburner-official/bitburner-src#1717]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by d0sboots** [comment]
Can you elaborate a little?

**Comment by gmcew** [comment]
A similar issue was reported in #1480 ; theme colours are key to how this augment makes things look within the minigame. Without further detail, I'll close this as not planned on the assumption its the same problem.
