### ISSUE TITLE
Feature Request: Allow tail to read/ follow txt files

### ISSUE THREAD

**Issue by bcox** [bitburner-official/bitburner-src#1719]
There are a number of times that I would love to log different things in different files.  I can do that with file writes, but I can't tail the created files to see updates.  It would be amazing if tail could follow a text file as well as a script.

**Comment by d0sboots** [comment]
This is a great case for writing a simple program (possibly called `tail.js`) to do what you want; as a program, it will naturally come equipped with a tail log that you can update as your chosen text file (provided as a commandline argument?) changes.

Small utilities like this that are nice-to-have but not *absolutely* critical are things we tend to leave to players to create.

**Comment by bcox** [comment]
That is completely fair and in hindsight obvious.  Thanks for the response.
