### ISSUE TITLE
Suggestion: expose alias and unalias in ns

### ISSUE THREAD

**Issue by Tanimodori** [bitburner-official/bitburner-src#172]
The `alias` and `unalias` command cannot be called in scripts by `ns` (except via HTML console input injection). This makes tasks like auto-connect alias, bin alias creation difficult. It will be better to have them (or something like getAlias and setAlias).

**Comment by OneOfMany07** [comment]
I don't understand what you mean by "auto-connect alias, bin alias creation".

For the first task, I'm guessing you're trying to replicate the AutoLink.exe feature with your own code.  And override the regular way to perform the action ('connect the-hub' without a backdoor on it).  I'm not sure why you'd have to override alias to do so.  alias="run connect.js" and make your connect.js script autocomplete the server names.

'bin alias creation' is opaque to me.

Alias/unalias in real life are part of the shell.  I think there are ways to automate those actions (send a string to the document), but why do you require it?  My aliases survive bitnode completion.  Though I'm not dynamically changing them.

**Comment by Tanimodori** [comment]
The "auto-connect alias" is mainly use to connect to quest line servers like CSEC and backdoor them. `connect` is not available until singularity. The `AutoLink.exe` only works with `Deepscan` and both need a long time to create.

"bin alias creation" means auto alias like `alias foo="run bin/foo.js"` for each script under `bin`

Yes, it is possible to run command by [injecting HTML](https://bitburner.readthedocs.io/en/latest/netscript/advancedfunctions/inject_html.html) but with some limitations.

Yes, alias/unalias is bash commands but we can run `.sh` and have `.bashrc` which bb lack of.

So I think it is better to implement something that user can run `.sh` or execute commands in scripts rather than add a `ns.alias`. I'm closing this issue as not planned now.
