### ISSUE TITLE
mem reports bladeburner.nextUpdate() as corporation.nextUpdate()

### ISSUE THREAD

**Issue by jcbollinger** [bitburner-official/bitburner-src#1741]
The `mem` command in the bitburner console reports usage of `ns.bladeburner.nextUpdate()` as `corporation.nextUpdate()`.

For example, given this script:
**/test/next-update.js**
```
/** @param {NS} ns */
export async function main(ns) {
  await ns.bladeburner.nextUpdate();
}
```
I produce this output:
```
[home /]> mem /test/next-update.js 
This script requires 2.60GB of RAM to run for 1 thread(s)
  1.60GB | baseCost (misc)
  1.00GB | corporation.nextUpdate (fn)
```
I expect the last line of that to report usage of `bladeburner.nextUpdate()`, not `corporation.nextUpdate()`.

Observed in Bitburner v2.6.2 (633da3830).

**Comment by d0sboots** [comment]
Sadly (and maybe surprisingly), this one is infeasible given how the game works. But, I'm pretty sure all the `nextUpdate` functions have the same cost, so there's a silver lining at least.

**Comment by gmcew** [comment]
I'm going to close this as unplanned due to technical limitations; preferably any future `nextUpdate` functions should also be consistent with RAM cost.
