### ISSUE TITLE
Infiltration doesn't reset failure count after success.

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#175]
Example: I just finished an infiltration mission where I succeeded getting 2 failed challenges. I start the next one and am immediately dumped out after a single failure (not the expected 3):
https://user-images.githubusercontent.com/1750680/198900597-25bd4f87-878b-4854-985e-7e057a83f232.mp4

- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.1.0

**Comment by jz0p** [comment]
I think this is working as intended?

Looks like your hp was too low, and you were killed.  For each failure you take a hit to hp. If hp is <= 0 you die. You can either go to a hospital and heal, or allow the failure to 'kill' you, wherein your hp will reset to full.

**Comment by Draco18s** [comment]
*Ah ha.*
I knew HP did something, but I've never managed to connect when I took damage to anything specific in the hacking minigames. As in, one time I went in with 0 HP and didn't *seem* to have any problems (I really should have documented that one).

It also isn't clear when it kicks you out that it was due to not having HP and you auto-visit the hospital with no indication that that happens.
