### ISSUE TITLE
Don't we have a referencing feature?

### ISSUE THREAD

**Issue by seannaquah** [bitburner-official/bitburner-src#1755]
Umm... This may sound silly, but I can't seem to find a ns.currentserverwhatever statement, like say, ns.currentservername to refer to the current servername, or ns.currentserverdate, or ns.currentservertime to refer to the current date, you know, ns.currentwhatever current whatever I'm trying to refer to. Or at least an ns.getCurrentServerName() to get the current server's name that my script is running on (for obvious reasons), or ns.getCurrentServerDate() and/or ns.getCurrentServerTime() to get the current date or time of the server my script is running on for whatever reason. lol. But basically you get my point. an ns.getCurrentServerWhatever(), especially an ns.getCurrentServerName() (assuming you have root access to the server or it won't run) will help a lot with writing automation scripts. I suggest not accessing using ns.currentserverwhatever property, since it breaks encapsulation laws but rather to use get methods like ns.getCurrentServerName(), etc.

**Comment by d0sboots** [comment]
There are a number of ways you can get the current server's name. The most straightforward is through <https://github.com/bitburner-official/bitburner-src/blob/stable/markdown/bitburner.ns.getserver.md> without any arguments; that will return a full `Server` object for the current server, which includes the hostname.

As to date and time, servers don't have separate dates and times, there is just the javascript clock, which is fundamentally your clock. Use standard APIs like <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now> for that.

**Comment by gmcew** [comment]
I think d0sboots answered this nicely - I'll close this for now.
