### ISSUE TITLE
Infiltration rewards should not scale so negatively on player multipliers

### ISSUE THREAD

**Issue by jz0p** [bitburner-official/bitburner-src#176]
Bitburner version 2.1.0

Minimal scripts to reproduce?
-unknown. was using 'ai.js', a script to automate infiltration, but the problem happens without it as well.

Penalties to infiltration occur when adding a certain number of augmentations (or certain types?).
These penalties reduce infiltration money rewards by a factor of ~15x, and rep rewards by a factor of ~5x.

If this is intended, why?

If not, steps to reproduce:

CASE1: Baseline
1] load savefile, observe rep and money rewards of any infiltration
2] install any 1 augmentation / reset
3] repeat same infiltration as step1. observe rep and money rewards are unchanged

CASE2: Hidden Penalties
1] load savefile, observe rep and money rewards of any infiltration (unneeded if already known from CASE1)
2] buy the following augs from Slum Snakes (gang):
Graphene Bionic Legs Upgrade
CordiARC Fusion Reactor
Graphene Bionic Spine Upgrade
3] buy all augs from Daedalus
4] install augs/reset
5] repeat same infiltration as step1
6] observe the penalties (15x reduction in money. 5x reduction in rep)

[bitburnerSave_1666810319_BN9x1.zip](https://github.com/bitburner-official/bitburner-src/files/9898432/bitburnerSave_1666810319_BN9x1.zip)

**Comment by Mughur** [comment]
The higher your stats are the easier the infiltrations are.
The easier the infiltrations are the lower their rewards are.
Sorry, no bug here, just balancing

**Comment by catloversg** [comment]
@d0sboots I think we can close this. Having higher stat multipliers means the player can improve their raw stats faster and infiltrate harder locations to get better rewards. Having a light penalty when they have high stat multipliers makes sense to me. It gives incentives to the player to improve their stats and infiltrate harder locations.
