### ISSUE TITLE
Purchase "hacknet-node-0" result in random string

### ISSUE THREAD

**Issue by Tanimodori** [bitburner-official/bitburner-src#177]
Run the script:

```ts
import { NS } from '@ns';

export async function main(ns: NS) {
  let host = ns.purchaseServer('hacknet-node-0', 1);
  ns.tprint(host);
  const purchasedServers = ns.getPurchasedServers();
  ns.tprint(purchasedServers.join(','));
}
```

![image](https://user-images.githubusercontent.com/29478770/199048563-b04af1cb-1bb8-4d39-8f44-efaa80399950.png)

# include (where relevant)

- [ ] Save file
- [x] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.1.0 (8f4636cb)

**Comment by Minzenkatze** [comment]
Seems to be intended behaviour, see Server.ts line 61.
```typescript
// "hacknet-node-X" hostnames are reserved for Hacknet Servers
if (this.hostname.startsWith("hacknet-node-")) {
    this.hostname = createRandomString(10);
}
```

**Comment by Tanimodori** [comment]
Seems intended but undocumented.
