### ISSUE TITLE
Bladeburner assassinations should affect karma.

### ISSUE THREAD

**Issue by stoltzld** [bitburner-official/bitburner-src#1777]
Bladeburner assassinations should affect karma.

**Comment by d0sboots** [comment]
In terms of lore/logical consistency, that absolutely makes sense. I'm terms of game balance, I don't know gangs or bladeburner well enough to know if this would destabilize things, but I suspect it would be fine.

**Comment by catloversg** [comment]
If we only give a small, flat negative karma, it won't affect the balance. Karma is only useful for 3 purposes:
- Get invitations from some factions. "The Syndicate" requires -90 karma.
- Unlock gang (-54000).
- Achievement `KARMA_1000000` (-1e6).

Currently, the best way to farm karma is to commit "homicide" crime (-3 karma/3s).

If we make this change, I think we should deduct karma for all successful Bladeburner's actions that involve "retirement" (our euphemism for killing):
- Contract and Operation: -1. The action time of these actions can be reduced to 1 second, so we have to use a small flat value.
- Black Operations: -15. There are only 21 BlackOps, and not all of them involve killing, so it's not a problem if we use a slightly higher value. -15 karma is the same amount of karma for "heist" crime, which is the crime giving the highest "negative karma".
