### ISSUE TITLE
MISC: "home" string is used instead of SpecialServers.Home

### ISSUE THREAD

**Issue by gmcew** [bitburner-official/bitburner-src#1786]
From #1781; broader replacement of "home" string usage rather than SpecialServers.Home

>When I look at the new change in https://github.com/bitburner-official/bitburner-src/pull/1779, I see the usage of "w0r1d_d43m0n" string. We have SpecialServers (src\Server\data\SpecialServers.ts), so it's best to use it.

>This PR also checks src\Server\data\servers.ts. For most special servers, hostname, organizationName, and specialName have the same value (some special servers have special values for organizationName, though).

>We use the "home" string in too many places in our codebase. I'm not sure if we should change all of them to SpecialServers.Home, so I have not touched them.

**Comment by d0sboots** [comment]
"home" is very short and honestly harder to mess up than SpecialServers.Home. So, I think there is low-to-negative urgency to replace it with a constant.
