### ISSUE TITLE
Bug or feature? Smart Storage immediately activated when purchased by script

### ISSUE THREAD

**Issue by MaWo2** [bitburner-official/bitburner-src#179]
I had some hard time getting my corporation script to work, because smart storage behaves differently, when purchased/unlocked by script, in comparison to manual purchasing.

If I manually purchase smart storage (Corp UI), I need to activate it, before it works.

However, if I purchase smart storage in a script, it is already activated. Due to this activation, later commands to buy material do not work, unless smart storage is deactivated by the script first.

Is this intended?

**Comment by LiamGeorge1999** [comment]
if it's not intended, and it doesn't mention that it automatically activates when purchases through the API (which I imagine it doesn't) and there's an API call to enable it and disable it, then it's an undocumented feature at best, and needs documenting.

But I happen to agree with MaWo2 that this is a bug. Just my 2 cents.

**Comment by Snarling** [comment]
After testing, this does not seem to happen anymore. Bought smart supply through a script and it did not automatically enable, I also saw nowhere in the code where this would have happened.
