### ISSUE TITLE
grafting allows augments without prerequisites installed

### ISSUE THREAD

**Issue by NoOneNeedsThat** [bitburner-official/bitburner-src#1811]
i can graft augments upgrade even if i dont have prerequisites implanted

augment "Bionic Arms" purchased, but not installed
![grafik](https://github.com/user-attachments/assets/af0340e2-a010-49cc-9ce4-54fc6af5bbd3)

grafting laboritory allows "Graphene Bionic Arms Upgrade"
![grafik](https://github.com/user-attachments/assets/062ebf20-c6a6-4cbe-938c-a431b13f44fd)

grafting is starting, can tell u in 1h if successful
![grafik](https://github.com/user-attachments/assets/b5fb962c-8213-49ff-bd41-c0b498e8b40a)

Version: 2.6.2

**Comment by NoOneNeedsThat** [comment]
![grafik](https://github.com/user-attachments/assets/af470b31-ad07-48f9-a60c-f73b498b36db)

as expected, in 2.6.2 u can graft augments into ur body without installing prerequisites first \o/

**Comment by gmcew** [comment]
For context, this is a very old bug (thanks Cald and Catloversg for the reference) - [discord](https://discord.com/channels/415207508303544321/415213413745164318/1021801649712414782)
An alternative to removing this behaviour is to endorse it as intended and document it.

**Comment by d0sboots** [comment]
I decided that grafting is a bit underpowered, so endorsing this seems fine. :D
