### ISSUE TITLE
CODEBASE: Remove debug code for finding bugs in pre-v2.4.0

### ISSUE THREAD

**Issue by catloversg** [bitburner-official/bitburner-src#1817]
For context, please check #1816.

I created this issue to make sure that we don't forget removing the debug code. After 1 or 2 versions, if we don't receive any reports about those bugs, I'll remove the debug code and close this issue.

**Comment by d0sboots** [comment]
I actually think it's a good safety check to keep in general, so I don't think we should remove it. If something regresses later, I'd rather find out about it than not.
