### ISSUE TITLE
Close/open game causes current in game scripts to be used, not originals from when first run.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#183]
To reproduce:
Run a script on a server
Change the source code of the script to use different arguments or print something new
Close the game
Open the game

Result:
The supposedly still running process uses the updated script, not the old script from when it was run the first time (before game close)

Expected:
That the overwritten file would be saved in the background, until all processes using it are gone.  And that old version of the script would be used when the Steam game opens.

Steam's Bitburner v2.1.0 (8f4636cb)

**Comment by Snarling** [comment]
This is how the game works. Whenever you launch a script (including on page reload), the game loads the saved script. If you have overwritten the saved script, then of course that's what it's now going to load when you reload the page, because you have destroyed the previous script.

**Comment by OneOfMany07** [comment]
"By design" is a choice.  I was pointing out how the game differs from the fake reality it portrays, and the fix seemed simple to me.  Guess your username is earned.

**Comment by Snarling** [comment]
It would work the same on your own computer. If you had a file set to run whenever you start up your computer, and you launch it, and then you edited that file before restarting, it would load the version that you edited, it wouldn't magically remember the version that you overwrote. If you don't want the game to forget the contents of your file, don't overwrite it, just like real life
