### ISSUE TITLE
Corp dialog boxes: text fields require highlight to backspace

### ISSUE THREAD

**Issue by BenS29** [bitburner-official/bitburner-src#1840]
Bitburner v2.7.0 (fbe1546fd)
In the corporations, whenever I open a dialog box to buy or sell a resource, the first character of every text field is not editable unless I highlight it first. In other words, when I try to change the buy/sell amount or price, it doesn't let me delete the first character unless I click and drag to highlight or press SHIFT+LEFT to highlight. This only started happening in this latest update. Attached is my save file, in case you need it.
[bitburnerSave_1733888602_BN10x2.json.gz](https://github.com/user-attachments/files/18089177/bitburnerSave_1733888602_BN10x2.json.gz)

**Comment by catloversg** [comment]
The "Sell" dialog has been changed to not accept an empty string for "Sell amount" and "Sell price". Let's say the current value is "MP". It's fine to delete "P", but if you also delete "M", the price is an empty string. In previous versions, the game shows you an error dialog when you press "Confirm". Now, it does not allow an empty string.

Tips:
- If you have to delete the string up to the first character, it's very likely that you are making a mistake. MAX and MP are fine choices as default values for "amount" and "price". Even when you need to use different values, it's usually something based on MAX and MP (MP\*0.9, MP\*2, etc.).
- You should read the in-game documentation of Corporation (it's also available at https://github.com/bitburner-official/bitburner-src/blob/stable/src/Documentation/doc/advanced/corporations.md). You have made many classic mistakes in your Corporation.

**Comment by d0sboots** [comment]
Although I agree with what you said, this *is* rather awkward behavior for a text box. "M" is just as invalid as "", so why is "M" allowed but "" is not? It feels like the behavior of deferring the error until later was more correct.
