### ISSUE TITLE
Game exports save as .json.gz which is unable to be imported back

### ISSUE THREAD

**Issue by drfidelis69** [bitburner-official/bitburner-src#1864]
[bitburnerSave_1734704952_BN3x1.json.gz](https://github.com/user-attachments/files/18211840/bitburnerSave_1734704952_BN3x1.json.gz)
Running the game on the web version v2.7.0 (fbe1546fd) available at bitburner-official.github.io on a Chromebook running version 130.0.6723.126 (in case it matters)

**Comment by catloversg** [comment]
I can import your save file normally.

![Capture](https://github.com/user-attachments/assets/4b1f5f45-0cf7-4fb6-93fc-363af93489d7)

What is the error when you import it?

**Comment by drfidelis69** [comment]
Okay, its user error, consequence of playing on old versions and then moving to release build, I was on the 2.3.2 version at danielyxie.github.io/bitburner when trying to load a 2.7.0 file. For reference, it says "Save game had not content or was not base64 encoded"
