### ISSUE TITLE
Request: Remove 2nd confirmation on Import

### ISSUE THREAD

**Issue by JasonGoemaat** [bitburner-official/bitburner-src#196]
The 'import' process is confusing.   When I do it I get asked for confirmation or the ability to compare saves.  I know what I'm doing so I click 'confirm'.  Then it says it 'found' a 'newer' save that I might want to use instead.  I'm assuming this is the last save that happened on the last game I was running, the one I just tried to delete by importing my old save.  I still don't know what the two buttons mean because the numbers are so similar.   I don't think it should do a comparison if I've already confirmed.  I have no idea what it is comparing to.

**Comment by Snarling** [comment]
This is due to the game trying to load your steam cloud save, which is not up to date with the version you have saved locally. If it keeps prompting you over and over, this is probably an issue with your steam cloud save settings.

**Comment by Snarling** [comment]
Closing this to consolidate steam save-related issues on one issue.
