### ISSUE TITLE
Market-TA changes the sell price, but the sell dialog doesn't parse the altered value without error.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#202]
This is my first run through with a corporation, but I've seen errors when setting sell prices for materials and products with Market-TA.

When Market-TA (I or II) is activated and I click on the connected Sell button, they'd changed the previous "Sell price" to include the name of the algorithm being applied.  Such as '(Market-TA.II)' for no previous price, or 'MP (Market-TA.II)' when I'd entered 'MP' for the price before.

**Steps to reproduce:**
If I only change the sell amount (MAX to PROD) and try to save the change, the old price text gets parsed as if I entered it and I get an error pop-up.  With a common version being...

`Error: Invalid value or expression for sell price field: SyntaxError: Unexpected token '.'`

I just tried deleting the 'MP (Market-TA.II)' value after triggering the error.  Meaning it had nothing when I clicked "Confirm", and it saved fine.  Now that field doesn't mention the feature being enabled (clicking the sell button on the material gives a blank sell amount field).

But the setting in Market-TA for that material still has the slider buttons turned on for both I and II.  I think the action of enabling the Market-TA feature is what changes the text.  Meaning I can break that field again by disabling then re-enabling Market-TA.

**Expected:**
I don't completely follow how these work, so I'm hesitant to offer an "expected result" beyond "no errors for things I haven't changed".  If the sell value is ignored then the user shouldn't be able to change anything with Market-TA active.  If it's more complex then a separate flag seems logical.  Either an indicator that lights up in the dialog, or a new string to use the value it offers (MTA or MTAII maybe?)

**Version:** Steam Bitburner v2.1.0 (8f436cb)

**Comment by Draco18s** [comment]
Yeah this has bugged me as well. But my corp is all automated now so I no longer have to mess with it.

**Comment by Snarling** [comment]
This no longer applies (see https://discord.com/channels/415207508303544321/459097632896188436/1146714735623028786)

**Comment by Draco18s** [comment]
Including the message being linked (as a screenshot or quoted text) is useful for those folks who haven't joined the server (particularly because the link doesn't help one *join* the server either, even if it is a public server).

But thanks for the update. :)
