### ISSUE TITLE
Missing API documentation for SleeveTask type.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#206]
The online MD page for [SleeveTask](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.sleevetask.md) is almost empty.

`SleeveTask type`
`Object representing a sleeve current task.`
`Signature:`
`export type SleeveTask = any;`

I was starting bitnode 10, which allows use of the sleeve API's, and was looking through documentation to see how it all works.  I found [this page](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.sleeve.gettask.md) about a function that'll return the SleeveTask, but I can't find how to use the returned object.  Printing didn't immediately show anything (implicit conversion to string?)

And the built in IDE didn't offer any hints about the returned object's contents (dot didn't trigger a list of contents).  The hinting doesn't always work perfectly for me, but I'd hoped it might be how other's guessed how to use it.

**I can try to deep dive for the code to figure this out, but maybe this is a good task for someone new to work on?**  They could look for additional areas that would benefit from documentation tweaks.  Like a few other pages are mostly blank, but a very similar one has the details I'd hope to see (differing by the first initial being capitalized...one being the interface, and the other the object it returns/uses?).

**Comment by AlexeyKozhemiakin** [comment]
I agree, getSeeveTask returns inconsistent responce, depending on task it can be actionType, type etc.

**Comment by Draco18s** [comment]
The first bit you'd want to check is `task.type` which will return the general nature of the sleeve's current actions (`FACTION` etc; corresponds to the first dropdown in the UI) and from that you can check for more specific details (`task.factionWorkType`, `task.factionName`, `task.companyName`, etc; corresponds to the second and third dropdowns).

You can JSON.stringify the returned task object and print it to the console to examine it.
