### ISSUE TITLE
Sleeve Infiltrate Synthoids - documentation and bug

### ISSUE THREAD

**Issue by AlexeyKozhemiakin** [bitburner-official/bitburner-src#207]
- [x] Infiltrate synthoids lack documentation what exactly is doing
- [  ] Should it be called Incite Violence which is doing smiilar thing? Good idea to add more comments in log how much it's chaos and contracts generating.
- [x] UI lacks progress bar
- [ ] Counterintuitive behavior - the more sleeves are working on it - the less it's granting contrats and operation (it become clear after I added text) const amt = Math.pow(infilSleeves, -0.5) / 2;
[11/10 18:28:49] Sleeve: Infiltrated the synthoid communities. Generated 0.5 new contracts and operations.
[11/10 18:25:47] Sleeve: Infiltrated the synthoid communities. Generated 0.28867513459481287 new contracts and operations.
[11/10 18:28:49] Sleeve: Infiltrated the synthoid communities. Generated 0.35355339059327373 new contracts and operations.

**Comment by AlexeyKozhemiakin** [comment]
first two items fixed

**Comment by Mughur** [comment]
> Should it be called Incite Violence which is doing smiilar thing? Good idea to add more comments in log how much it's chaos and contracts generating.

Sleeve infiltration doesn't increase chaos, therefore calling it "incite violence" wouldn't be a good option.

**Comment by Draco18s** [comment]
Additionally the sleeve's task object is just `{type:"INFILTRATION"}` when the others have more details, eg. `{"type":"BLADEBURNER","actionType":"General","actionName":"Diplomacy"}`

**Comment by Snarling** [comment]
Fixed by #412 (progress bar and better description)
