### ISSUE TITLE
At least two files that likely should be locally generated are in the git tree.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#215]
Very new dev here, so I apologize if I'm confused here.  I'm still setting things up to experiment with helping out.

I grabbed the current dev branch and was poking through files.  Two showed "errors" according to Visual Studio Code.  `tsdoc-metadata.json` has a comment at the top that this file shouldn't be tracked in git, and it points at the other file `api-extractor.json`.

I also wonder if `.vs` (and .vs/FileContentIndex and .vs/v17) should exist or be ignored by git...  Seems like it's for version 17 of Visual Studio (from 2017?).

tsdoc-metadata.json
```
// This file is read by tools that parse documentation comments conforming to the TSDoc standard.
// It should be published with your NPM package.  It should not be tracked by Git.
{
  "tsdocVersion": "0.12",
  "toolPackages": [
    {
      "packageName": "@microsoft/api-extractor",
      "packageVersion": "7.19.4"
    }
  ]
}
```

And api-extractor.json is the other file.
```
/**
 * Config file for API Extractor.  For more info, please visit: https://api-extractor.com
 */
{
  "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",

  /**
   * Optionally specifies another JSON config file that this file extends from.  This provides a way for
   * standard settings to be shared across multiple projects.
   *
```

**Comment by myCatsName** [comment]
I think this "issue" relates to "Comments aren't permitted in JSON", causing Visual Studio to complain. 
![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/45c7bec9-10fd-4385-ba7c-dafcd49c8f98)

 2 solutions are pointed to [in this discussion](https://stackoverflow.com/questions/47834825/in-vs-code-disable-error-comments-are-not-permitted-in-json), both of which "fix" the VSC error for me.

First is for user to "set language mode" in VSC or update a local config if wanting a persistent change.
![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/2a045cea-42d8-4b4c-9f19-4843ebd3f860)

Other suggestion is for dev to update commented JSON files to `.jsonc` (JSON with comments). This also "fixes" the VS error for me, but created other issues, probably just skill issue on my part.

![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/a4d46b5b-21e4-499d-becd-250e3378971a)

@Snarling 

There are package-lock dependencies for `"strip-json-comments": "^3.1.1"` https://www.npmjs.com/package/strip-json-comments making me think a workaround might be in place that would need attention or removal if updating file extensions.

We also have JSON5, which allows comments.

If a production solution is as simple as updating `.json` to `.json5` or c, then I would ask for help with I assume a config issue? when updating api-extractor.jsonc VS stops complaining but 
![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/f5201183-92d2-4652-9472-0ec9b02caaf3)

**Comment by catloversg** [comment]
@d0sboots Can we close this? This is just the complaint of VS Code about JSON with comments. It can be "fixed" by using the solution at https://stackoverflow.com/a/47834826.

**Comment by d0sboots** [comment]
The OP *looked into* this because of those VS Code errors, yes, but I'm not sure that the issue here is wrong/obsolete: "At least two files that likely should be locally generated are in the git tree."

**Comment by catloversg** [comment]
`api-extractor.json` is the config file for `API Extractor`. We set our config for `API Extractor` in it, so it must be in Git.
`tsdoc-metadata.json` is generated/updated when we run `npm run doc`. AFAIK, we don't use this file in our toolchain, so it was added to `.gitignore` in 2489ec43fe348785bd562eb1dd69c4107135e3bb. I'll remove it in the next PR.
