### ISSUE TITLE
Ending Infliltration Repositions, Resizes, and Repopens Script Logs

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#25]
[Xenosplitter]
### Expected Behavior
When exiting an infiltration, open script (file.script and file.js) logs remain how they were set up before beginning the infiltration

### Actual Behavior
Exiting an infiltration via running out of HP, completing the infiltration, canceling mid infiltration, and canceling before starting the infiltration cause all open script logs to reappear in the middle of the screen, how they appear when first opened. This resets log window sizes, positions, and minimized status.

### Steps to Reproduce
1. Run a script
2. Open the script's log
3. Resize, reposition, or minimize the log file, keeping it on screen
4. Navigate to an infiltration (I use Joe's Guns, but others work too)
5. Finish the infiltration in some fashion (success, failure, cancelation)
6. Note how the log window repositions itself to the center

**Comments From Original Issue**

[akuma6099]
> I just wanted to tack onto this because I was about to open an issue on it. You can reproduce this problem by simpling navigating to any company, selecting infiltration, then cancel. I've yet to reach a level of XP to bring down the difficulty so I kept checking then cancelling and I observed this same behavior. My organized log windows stacked in the lower right corner all resized and opened in the middle as if I just launched the scripts with --tail.

[Xenosplitter]
> Without doing any investigative work, a blind guess on why this might happen is that opening the infiltration screen tries to hide open logs. This might be done by noting which logs were open, closing them, then reopening the logs once more. This would explain why all windows reset (because they are in this theory). Perhaps a better way to hide the log windows would be to set their element display styles to `display: none;` temporarily, resetting back to `display: flex;` once finished.

**Comment by myCatsName** [comment]
I think this was fixed with PR #769
