### ISSUE TITLE
hackAnalyzeThreads results always in infinite on various servers V1.3.0

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#26]
[Unkn0wnNPC]
Just run the script below and it'll always result in Infinite on various servers

`export async function main(ns) {
 let destinations = ns.read("/hackV2/servers-sorted.txt");
 destinations = JSON.parse(destinations);
 let test = ns.hackAnalyzeThreads("foodnstuff", 1)
 ns.print(test)
}`

![bitburner_Issue](https://user-images.githubusercontent.com/71597557/149597087-1d7604f8-f570-48ec-8d8a-556d945f91b6.jpg)
[bitburnerSave_1642201801_BN1x0.json.txt](https://github.com/danielyxie/bitburner/files/7873742/bitburnerSave_1642201801_BN1x0.json.txt)

**Comments From Original Issue**

[nickinitro]
> can confirm!

[geiloschefos]
> same...

[zeddrak]
> Are you in a bitnode with a BitNodeMultipliers.ScriptHackMoney == 0?
> If so, this would be the correct response (no amount of threads will allow you to steal any money)
> 
> #2454
> One recent correction that I know was made was to include the BitNodeMultipliers.ScriptHackMoney, but that shouldn't create this behavior where it wasn't before, as the 0 case would be the same either way.
> 
> Similarly having a server security of 100+ should result in infinity, because of:
> `const difficultyMult = (100 - server.hackDifficulty) / 100;`
> 
> As would a server.moneyAvailable == 0.
> 
> Basically, anything that makes this denominator 0 should return infinity:
> `return hackAmount / Math.floor(server.moneyAvailable * percentHacked);`
> 
> ```
>     hackAnalyzeThreads: function (hostname: any, hackAmount: any): any {
>       updateDynamicRam("hackAnalyzeThreads", getRamCost(Player, "hackAnalyzeThreads"));
> 
>       // Check argument validity
>       const server = safeGetServer(hostname, "hackAnalyzeThreads");
>       if (!(server instanceof Server)) {
>         workerScript.log("hackAnalyzeThreads", () => "Cannot be executed on this server.");
>         return -1;
>       }
>       if (isNaN(hackAmount)) {
>         throw makeRuntimeErrorMsg(
>           "hackAnalyzeThreads",
>           `Invalid growth argument passed into hackAnalyzeThreads: ${hackAmount}. Must be numeric.`,
>         );
>       }
> 
>       if (hackAmount < 0 || hackAmount > server.moneyAvailable) {
>         return -1;
>       } else if (hackAmount === 0) {
>         return 0;
>       }
> 
>       const percentHacked = calculatePercentMoneyHacked(server, Player);
> 
>       return hackAmount / Math.floor(server.moneyAvailable * percentHacked);
>     }
> 
> ```
> ```
> /**
>  * Returns the percentage of money that will be stolen from a server if
>  * it is successfully hacked (returns the decimal form, not the actual percent value)
>  */
> export function calculatePercentMoneyHacked(server: Server, player: IPlayer): number {
>   // Adjust if needed for balancing. This is the divisor for the final calculation
>   const balanceFactor = 240;
> 
>   const difficultyMult = (100 - server.hackDifficulty) / 100;
>   const skillMult = (player.hacking - (server.requiredHackingSkill - 1)) / player.hacking;
>   const percentMoneyHacked = (difficultyMult * skillMult * player.hacking_money_mult * BitNodeMultipliers.ScriptHackMoney) / balanceFactor;
>   if (percentMoneyHacked < 0) {
>     return 0;
>   }
>   if (percentMoneyHacked > 1) {
>     return 1;
>   }
> 
>   return percentMoneyHacked;
> }
> ```

[zeddrak]
> Hmm...
> I guess that if BitNodeMultipliers.ScriptHackMoney could be < 0, then moving it before the check could result in a different behavior, but that'd still be really weird, as the previous version would've ended up in negative threads being needed.

[zeddrak]
> Update, I am working on a fix for this in my scripts. Once I've completed and tested there, I will check with Hydroflame if he wants them imported into the source game. It is a complicated problem though (since the amount grown is now partially based on the threads used, making getting the threads needed a self-referential nightmare akin to determining how much rocket fuel you need to get into orbit...)

[zeddrak]
> [My Discord discussion in developement](https://discord.com/channels/415207508303544321/459097632896188436/934590171066802187)
> 
> > Ok, concerning the growAnalyze, I have a couple of options to deal with the infinity issues:
> > https://github.com/danielyxie/bitburner/issues/2635
> > https://github.com/danielyxie/bitburner/issues/2628
> > 
> > Option 1) Just retun Math.min(growAnalyze normal value, server.moneyMax) --- this basically assumes a minimum of $1 server and ignores the extra power added to grow ($1/thread) and so will return larger values than actually needed (potentially MANY times larger in some case. Theoretical example: if it takes 100 threads to double - grow x2 - a certain server with moneyMax of $200, then 100 threads is all that would be needed to grow it to max from $0, but this naïve solution is returning 200)
> > 
> > Option 2) Is basically to use a first order differential equation - ie, how many threads it takes is dependent on how many threads you need... I'll look up one of the approximation techniques for that kind of first order differential equation and use that (most approach very quickly, and we only need to get to an error <1 since integer threads anyways). This has the added advantage of taking into consideration the extra grow power for non-full grows as well.
> > 
> > Opinions?
> > (Follow-up: If we go with option 1, should I also change the previously discussed functions to behave accordingly - eliminating the infinity thing entirely? Basically, this would change the mechanic for growing <$1 servers to assume $1, instead of $1/thread, consistently.) 

[phyzical]
> i'm personally not a fan of having an equation
> Mostly because a complicated algorithm to stop this issue will break one day, not if just when 😆
> 
> The other way to look at this would be to fix the issue on the other side, anywhere the result could be `Infinity`make it invalid. 
> though i dont like this one because Infinity will eventually be a valid result due to the cap on number in JS land
> So we  would have to consider to use a number system similar to other idle games where they use letters for additional categorizing of large numbers. but we just have no reason for numbers to get bigger than the js cap at this time
> 
> imho, just make the minimum 0.00000000001 (or 1).
> 
> But its a question for higher powers

**Comment by Snarling** [comment]
Fixed by 45ca94b
