### ISSUE TITLE
Hospital Unusable after BitNode Reset

### ISSUE THREAD

**Issue by koenenalexander** [bitburner-official/bitburner-src#264]
After starting BitNode 2 for the first time, the health stat does not appear to increase as expected (either by leveling up defense or by using a hospital).

Version: Bitburner 2.1.0 release
Possibly related to https://github.com/danielyxie/bitburner/issues/4242

Steps to Reproduce:

1. Load attached save file,
2. Connect to w0r1d_d43m0n,
3. Install backdoor,
4. Select and enter BitNode2,
5. Notice, health shows 17/10,
6. Fail an infiltration mini-game at joesguns,
7. Cancel infiltration,
8. Attempt to heal at Hospital,
9. Observe, no health is returned and the debug panel shows the error below.

`Uncaught TypeError: Cannot read properties of undefined (reading 'getCost') at getHealed (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:21:1023391) at Object.He (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:16072) at Ke (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:16226) at file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:34213 at Or (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:34307) at Mr (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:34721) at file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:40369 at Be (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:116040) at file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:36180 at Ar (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:247:36210)`
[PreBitNodeReset.zip](https://github.com/bitburner-official/bitburner-src/files/10283002/PreBitNodeReset.zip)

**Comment by Mughur** [comment]
This is fixed in the current build

**Comment by Snarling** [comment]
Issue is not present in 2.2
