### ISSUE TITLE
Html markup in notification

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#267]
![image](https://user-images.githubusercontent.com/1750680/209623785-edb4277c-b875-4237-a65a-49de995ce488.png)

- [x] Version of the game, e.g. Bitburner v2.1.0 (0133945c)

**Comment by Snarling** [comment]
Issue is here, `<br />` should be `\n`. Issue still present in 2.2
https://github.com/bitburner-official/bitburner-src/blob/19e8946d9aed90a26be35b8f8999238cdd70d5e5/src/Bladeburner/Bladeburner.tsx#L1968

**Comment by Snarling** [comment]
Fixed in latest commit [0ec4ef3](https://github.com/bitburner-official/bitburner-src/commit/0ec4ef31ab5f7172a84baf8cf377d6202699d5b3)
