### ISSUE TITLE
possible issue with scheduling

### ISSUE THREAD

**Issue by kingrodriguez** [bitburner-official/bitburner-src#274]
Bitburner v2.2.0 (680027cd)

i have a botnet, that attacks a target in sequenced attacks (hack > weaken > grow > weaken > repeat).
they run in parallel with a spacing of 200ms (was 50 initially, but increased for debugging)
i calculated everything, so that after every batch of (properly threaded) hack - weaken -grow - weaken the server is back at max money and min security.
i log an output, whenever one of the scripts terminate.
i currently run 59 batches in parallel, until i check, that the precondition (min sec, max money) is set.

i see, that after enough scripts are deployed and running, they are getting out of sync., which leads to inefficiency =P

here are logs from the start of the deployments:
```
done 7/59 hacking,       started 1672497136693 delayed 71355.54759433669
done 7/59 weakeningHack, started 1672497136694 delayed 0
done 7/59 growing,       started 1672497136695 delayed 19281.479358489785
done 7/59 weakeningGrow, started 1672497136695 delayed 400
done 8/59 hacking,       started 1672497137497 delayed 71355.54759433669
done 8/59 weakeningHack, started 1672497137498 delayed 0
done 8/59 growing,       started 1672497137499 delayed 19281.479358489785
done 8/59 weakeningGrow, started 1672497137502 delayed 400
done 9/59 hacking,       started 1672497138321 delayed 71355.54759433669
done 9/59 weakeningHack, started 1672497138321 delayed 0
done 9/59 growing,       started 1672497138322 delayed 19281.479358489785
done 9/59 weakeningGrow, started 1672497138322 delayed 400
```

and here from the end
```
done 50/59 weakeningHack, started 1672497173230 delayed 0
done 50/59 growing,       started 1672497173258 delayed 19281.479358489785
done 50/59 weakeningGrow, started 1672497173286 delayed 400
done 50/59 hacking,       started 1672497173203 delayed 71355.54759433669   # this one tips everything off
done 51/59 hacking,       started 1672497174114 delayed 71355.54759433669
done 51/59 weakeningHack, started 1672497174143 delayed 0
done 51/59 growing,       started 1672497174169 delayed 19281.479358489785
done 51/59 weakeningGrow, started 1672497174196 delayed 400
```

the commented script was start first, as you can see from the time stamp, when it started, but finishes last in the block (sometimes even 1 or 2 blocks later)
i calculate the delays once, before starting the 59 blocks and start all the batches with the same delays. no level up happened in the mean time or other events, that could corrupt the timings.

overall i followed this schema: https://bitburner.readthedocs.io/en/latest/advancedgameplay/hackingalgorithms.html#batch-algorithms-hgw-hwgw-or-cycles

from the manual i take the 20 - 200ms spacing,

is there an issue with the scheduler? or need we even higher spacing? because i am pretty sure my hardware is no issue at all.
the out-of-order script finished over 600ms late. if that is an bug, it is hereby reported, if we need higher spacing, i hereby suggest adopting the docs.

**Comment by Caldwell-74** [comment]
thats most likely just a task collision issue
after hack or grow security is increased if a task starts in the timeframe between them and the following weaken the time of that task is longer than what you would expect / calculated

**Comment by kingrodriguez** [comment]
unfortunately not. i stop deploying batches, before the first one is finished:

```js
const starttimeMS = Date.now()
const attackTimeMS = x // obviusly calculated
const attackSpacingMS= 250

// loop
if (Date.now() - starttimeMS < attackTimeMS + 4*attackSpacingMS) {
    deployBatch()
}
await ns.sleep(4*attackSpacingM)
// loop
```

because of logging etc i can see, that nothing is deployed at the time the attacks hit the target.
also because of slow / neglectable increase of skill, i calculate all the timings at once before n batches are finished. when the batches are done, i recalculate everything

**Comment by Caldwell-74** [comment]
are your worker sleeping first to get to their task start time or are you spawning in them the moment they should be starting their task?

**Comment by kingrodriguez** [comment]
sleep for timing first, then attacking

**Comment by kingrodriguez** [comment]
havent pushed yet, but can provide the code, in case it helps

**Comment by kingrodriguez** [comment]
the script for a single job (grow / weaken look the same)
```js
export async function main(ns) {
    const target = ns.args[0]
    const delay = ns.args[1]
    const time = ns.args[2]
    const deploymentID = ns.args[3]
    const job = ns.args[4]
    const infinite = ns.args[5]

    if (infinite === "true")
        while (true) {
            await ns.sleep(delay)
            await ns.hack(target)
        }
    else {
        await ns.sleep(delay)
        await ns.hack(target)
        // ns.tprintf(`${deploymentID} ${job} started ${time} delayed ${delay}`)
    }
}
```

**Comment by Caldwell-74** [comment]
okay iam still sure its just task collisions
for the task time calculation the moment they start their task is important not when the script is launched
even if you stop launching scripts before the first task is finished with that sleep they might sleep into an unsafe window

**Comment by kingrodriguez** [comment]
ok i will make a log before the hack/grow/weaken call to make sure, they start in order.
i am with ya - i also think it is a mistake on my side. sped like 7 days to find the issue O.o

**Comment by Snarling** [comment]
This appears to be an issue with a player script, so I'm closing this issue. See the batching and code reviews channels on the discord for assistance with resolving these timing issues.

Bitburner uses builtin javascript methods for scheduling actions (e.g. window.setTimeout). Also keep in mind that if the window loses focus, your browser may throttle or stop executing js, which would also lead to timing issues even if your code does not have errors.
