### ISSUE TITLE
"Recovery Mode Activated" (also unable to reference 'args' at all for some reason)

### ISSUE THREAD

**Issue by mlchen2** [bitburner-official/bitburner-src#285]
Hello. Today's January 2nd (v2.1.0) update broke my save for some reason. Booting up the game now with the below save file will put my game in "Recovery Mode". After I disable Recovery Mode, attempting to run any script that references "args" (args[0], args[1], args.length, etc.) will throw the below error:

RUNTIME ERROR
test2.js@home (PID - 1)

args is not defined
stack:
ReferenceError: args is not defined
    at Module.main (home/test2.js:3:13)
    at M (file:///E:/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:271504)

[RECOVERY_BITBURNER_1672702257.zip](https://github.com/bitburner-official/bitburner-src/files/10333787/RECOVERY_BITBURNER_1672702257.zip)

[argsScriptThatThrowsError.txt](https://github.com/bitburner-official/bitburner-src/files/10333789/argsScriptThatThrowsError.txt)

**Comment by Snarling** [comment]
`ns.args`, not `args` for your second issue. `args` is expected to be undefined there.

Taking a look at the save issue now

**Comment by Snarling** [comment]
Looks like your save issue has been fixed by the existing hotfixes, which are live on steam and at https://bitburner-official.github.io/bitburner-src/

To get steam to see the update, you may need to close and relaunch steam

**Comment by mlchen2** [comment]
Thanks! It works now!
