### ISSUE TITLE
ns.bladeburner.getBonusTime given ram cost of ns.corporation.getBonusTime

### ISSUE THREAD

**Issue by Fulmens** [bitburner-official/bitburner-src#288]
Script :
```
export async function main(ns) {
    ns.bladeburner.getBonusTime();
}
```
Running the mem tool on this script gives the following output :

[home ~/]> mem test.js 
This script requires 1.02TB of RAM to run for 1 thread(s)
  1.02TB | corporation.getBonusTime (fn)
  1.02TB | Max Ram Cap (misc)
  1.60GB | baseCost (misc)

Instead of the 0 ram cost of the documentation.
Version of the game: Bitburner v2.2.0 (95e3c1ac)

**Comment by Fulmens** [comment]
Just checked, ns.gang.getBonusTime has exactly the same problem.

**Comment by Snarling** [comment]
https://github.com/bitburner-official/bitburner-src/commit/bb566dc57c28919d3f044f3a60ebc6fb3bea1fea
Fixed by removing ramCost of corporation.getBonusTime (all the others are already 0 cost which is why they're able to have the same name without conflicting). Fix is live.
