### ISSUE TITLE
Allow regional settings to use comma instead of period.

### ISSUE THREAD

**Issue by LanceLake** [bitburner-official/bitburner-src#289]
Look at any money stat on version 2.1.0.

In the US, we use commas for the periods unlike the UK. 

1 thousand dollars looks like in the UK: 1.000,00 (I believe)

In the US, it's 1,000.00

Perhaps look at the local computer settings and pull from that to determine how to display the money? :)

**Comment by MaWo2** [comment]
I think you are at a misconception here: The game actually uses the US annotation.

The game does not display one thousand dollars as 1000 (or 1,000), but rather as "1 k" with three decimals.

When you enter a BN and only have 1,030.00 Dollars, the game displays it as 1.030 k.
This is the correct use of the US decimal delimiter.

Another example: If you provide non-integer values in the terminal or in scripts, you need to use 1.9, not 1,9 (German annotation).

As a German user, I would really like to have it displayed as 1,030 k or 1,9.
However, I think this would be breaking many scripts. At least, it would make it very difficult to share scripts.
