### ISSUE TITLE
Add ability to view current Sleeve Intelligence stat

### ISSUE THREAD

**Issue by Kriknav** [bitburner-official/bitburner-src#294]
Bitburner v2.1.0 (8f4636cb)

I recently noticed that all my sleeves had the same stats and augmentations (in fact none had installed augs), yet the newly obtained one had a lower chance than the others to successfully complete a crime.

I searched the web and found out that apparently sleeves have their own intelligence stat, which would make sense.  I think it'd be helpful to see the sleeve's int stat either in the main UI or at least under the More Stats screen just to avoid any confusion.

Thank you.

**Comment by Mughur** [comment]
It already is there in 2.2: `ns.sleeve.getSleeve(i).skills.intelligence`
