### ISSUE TITLE
Charisma gain from Recruitment in the Bladeburner HQ seems a little steep?

### ISSUE THREAD

**Issue by Fancybreakfast** [bitburner-official/bitburner-src#295]
- I failed at attaching a .json so I uploaded a .txt copy. 
- I have some charisma modifiers and I am in BN9x2. 
- Join Bladeburner Division. Start a Recruitment action under the General tab. Witness the gains!  
- BitBurner v2.2.1 (c46cedd5)

"[1/4 15:32:55] Player: Successfully recruited a team member! Gained 398,000.0 charisma exp"

[bitburnerSave_1672875640_BN9x2.txt](https://github.com/bitburner-official/bitburner-src/files/10348260/bitburnerSave_1672875640_BN9x2.txt)

First time submitter and generally clumsy, so I apologize for any missteps.

**Comment by Snarling** [comment]
Yeah it looks like the formula for this XP gain is just crazy, from what I can tell it's been like that for at least 9months...
It should be 1/1000 of that value. It's multiplying a bladeburner XP constant (documented as base stat gain per second) by a number of milliseconds.

**Comment by Zelow79** [comment]
I don't disagree this was probably a bug, but that was probably the only good thing about Recruitment lol. RIP.

**Comment by Snarling** [comment]
This was fixed

**Comment by xtvo23** [comment]
![bb_charismabug](https://github.com/user-attachments/assets/13c0aebe-a287-41f6-adf0-594b77377e8b)


This bug appears to be back now. I'm getting 1000x the charisma exp you would expect. It looks like some refactoring occurred a few months ago and the fix got reversed. This is the old code:

https://github.com/bitburner-official/bitburner-src/blob/d4f0ea50da34c84593c5a4244e32fb12d4be79e0/src/Bladeburner/Bladeburner.tsx#L1496-L1500

And the new:

https://github.com/bitburner-official/bitburner-src/blob/95394b59567fc0a2ef54617034c5bfad2c11cef0/src/Bladeburner/Bladeburner.ts#L1135-L1138

Removing the factor of 1000 on 1136 should fix it. I'd submit a pull request but I'm a bit of a github noob and couldn't quite figure it out.

**Comment by cmsautter** [comment]
yeah, seems legit, the exp gain needs to be divided by 1000 again.
