### ISSUE TITLE
cannot access file dir c:/

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#30]
[k4zter]
wasn't able to access c:/ and had to use a script to remove all contents in the file to get rid of the folder even tho the game fully recognizes that there is a file there with c:/

![bitburner_MtzGpkFVIv](https://user-images.githubusercontent.com/50892886/150626082-19540555-7b97-457a-8d05-9101571cbb9a.png)

Bitburner v1.4.0 (49de4a28)(steam)

**Comments From Original Issue**

[phyzical]
> just to confirm (this is obviously windows right?)
> 
> or have you created a folder called c:/? 
> 
> didn't relise we give bitburner access to the hardrive.. 
> i assume we dont otherwise thats pretty scarey....

[k4zter]
> yeah it was a folder i pushed from VSC and it took the file dir of my folder on my pc...

[phyzical]
> hmm might be something to ask in the discord channel for VS code. (but we can try to repo it and see what happens) 👍 

[k4zter]
> Yeah I fixed it by changing the settings in vsc to not push my PC Dir but the people that I was asking help to fix this told me to issue it anyways

[phyzical]
> @lordducky hey thought i would tag you on this one, any chance this can be added as part of your webserver updates :). tldr we just need to make sure that we cant save invalid directory names i.e `c:\` and `/` as these cannot be `cd` into once they are copied across via the webserver

**Comment by Hoekstraa** [comment]
Tested as of today, on a dev build of 2.3.2. The folder can now be opened like any other valid folder name.
Hence I'm considering it fixed and closing the issue.
