### ISSUE TITLE
No ability to see office employee experience

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#304]
https://github.com/bitburner-official/bitburner-src/blob/dev/src/NetscriptFunctions/Corporation.ts#L675-L690

Without the ability to see employee experience levels, there's no way for an automated script to move employees out of training.

- [x] Version of the game, e.g. Bitburner v2.2.1 (c46cedd5)

**Comment by Snarling** [comment]
totalExp should be added here and in the relevant type definition in NetscriptDefinition.d.ts

https://github.com/bitburner-official/bitburner-src/blob/0c2d402f0b72c09c633e161e520e0f4f66614316/src/NetscriptFunctions/Corporation.ts#L682-L701
