### ISSUE TITLE
setAutoJobAssignment can delete employees

### ISSUE THREAD

**Issue by Infinite-Trial** [bitburner-official/bitburner-src#311]
If there are N unassigned employees in an office then setAutoJobAssignment can be used to set the number of unassigned employees to any number less than N (including negative) after which it is no longer possible to return them.

- [x] Minimal script to reproduce the issue
`ns.corporation.setAutoJobAssignment("Division", "Sector-12", "Unassigned", -10)`

- [x] Version of the game, e.g. Bitburner v2.2.1 (c46cedd5)

**Comment by Mughur** [comment]
Fixed in #307
