### ISSUE TITLE
Cleanup dist/ext folder

### ISSUE THREAD

**Issue by tiziodcaio** [bitburner-official/bitburner-src#313]
Mathjax is still into dist/ext folder

**Comment by tiziodcaio** [comment]
It's not completed, since mathjax still into dist/ext.

**Comment by Snarling** [comment]
That's fair. And actually there probably is a way for us to get rid of it, I think we can use webpack and something like [mathjax-loader](https://www.npmjs.com/package/mathjax-loader) to create svgs for the equations at build time, then we don't need to bundle mathjax itself at all. Pretty sure none of our equations have dynamic math content so I think that approach would work.

Will require some internal refactoring though.
