### ISSUE TITLE
Hacknet/Hashnet upgrade tooltips should always show a significant digit (non-zero)

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#315]
Some bitnodes lower the effectiveness of Hacknet/Hashnet upgrades until the early upgrades all show "+ 0.000 h / s ..." so I can't know what I'm getting for my money.  I suggest that these tooltips should show values in scientific notation when necessary, to offer a non-zero digit or 3 like "+ 1.25e-5 h / s ...".

I've unlocked bitnode 9 (I think it is) once, so the modified Hashnet is what I'm using.  I can see all 0's for the 11th level, 3rd for RAM, and I finally have a 0.001 on the 3rd level of Cores (with 4GB RAM and 10 levels).  That whole time I can only guess the effects of those upgrades by their later effects and price, or the Total if I get enough servers together.

I think there was talk about changing the number formatting library, so maybe this was left out because it was broken with the old library?

Bitburner v2.2.1 (c46cedd5) - has been true since I started playing though (2.1 I think?)

**Comment by MaWo2** [comment]
There also seem to be rounding issues involved:
If I buy my first Hacknet server, I get 0.001 h/s production rate.
If I buy the second one, I have 0.003 h/s production rate.

This makes it difficult to estimate, how much cache you need to buy, if you plan some offline time.
