### ISSUE TITLE
Error: Trying to do infiltration on invalid location. (at "Infiltration")

### ISSUE THREAD

**Issue by UnionStylistSteerableUnwary** [bitburner-official/bitburner-src#320]
### How did this happen?

Was doing an infiltration on a place when the Casino script I use tried flying me across the world to play Blackjack. It seems to have aborted the infiltration and crashed BitBurner.

### Environment

* Error: Error: Trying to do infiltration on invalid location.
* Page: Infiltration
* Version: v2.2.1 (c46cedd5)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save

[RECOVERY_BITBURNER_1673571593.zip](https://github.com/bitburner-official/bitburner-src/files/10407243/RECOVERY_BITBURNER_1673571593.zip)

**Comment by Snarling** [comment]
Without a more minimal reproduction method, this looks to just be an issue with your casino script potentially clicking buttons that are no longer on the screen, which can cause unexpected interactions like this. Will look into it more if a more minimal repro method is provided.

**Comment by TheMas3212** [comment]
Closing this due to no response
