### ISSUE TITLE
BUG/FEATURE: script production stats only propagate up 1 ancestor deep

### ISSUE THREAD

**Issue by maconard** [bitburner-official/bitburner-src#322]
## Description
When a script earns XP and/or money, these stats are tracked in the Active Scripts section as "Total online production", "Online production rate" (simple division of the prior stat and the runtime), and "Total offline production". When a script spawns scripts that earn XP and/or money, the sum of all those children have their stats tracked in that parent script. However, it does not continue applying recursively to further ancestors, such as a grandparent script where the grand children are earning XP and/or money. I would expect this feature to sum stats from all descendants, not just direct descendants. 

TLDR:
- Current behavior: script production stats track on a script and are included in a sum for the parent stats, no further
- Expected behavior: script production stats track on a script and are included in the sum for the stats of all of its ancestors

## Minimal Scripts to Reproduce
One parent script that execs a child and that child execs grand children (to the original script) that gain XP/money. This is a total of 3 scripts, which can be as simple as exec, exec, and hack. The parent scripts must remain alive, rather than exiting.

## Version
The latest Steam version (v2.2.1 c46cedd5), which appears to be slightly behind the Github dev build (v2.2.2dev 41451280).

## Screenshot
![image](https://user-images.githubusercontent.com/31703304/212565811-b48748de-0087-4ccd-996b-02eaaebfa8ad.png)
The top script is the original script, which spawns the bottom script. The bottom script spawns many children which perform growing/weakening/hacking (those grand children not pictured).

Cheers!

**Comment by Snarling** [comment]
Income is only counted in one place at a time (in this case, it looks like you are expecting to see targetManager being assigned all of the income from the scripts it spawns, but *also* having that same exact same income assigned to spawnManager. This is intentionally not the case - script income is assigned to one script at a time. Child scripts only propagate their income up to their parent when that child script dies and the parent script is still alive.

**Comment by maconard** [comment]
> Child scripts only propagate their income up to their parent when that child script dies and the parent script is still alive.

Ah, a grand misunderstanding on my part then, in the wild it was unclear that that was the time/cause of propagation. Cheers, I'll go ahead and close this then!
