### ISSUE TITLE
[Scripting] Getting TIX API cost

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#332]
Because of BN multipliers, the cost to purchase TIX API/data access can be modified away from the base cost (eg. BN7), however the stock API does not give any access to getting that cost so that scripts can be sure that the player has enough money before attempting to buy the API access and SF5 is needed to query the BN multipliers directly, which the player may not have prior to entering BN7.

- [x] Version of the game, e.g. Bitburner v2.2.1 (c46cedd5)

**Comment by Snarling** [comment]
SF5 gives you the ability to make your scripts work regardless of the bitnode without needing to manually change any variables. Not having SF5 here doesn't mean your script can't work in BN7, it just means if you want it to work in BN7 (or whatever node) then you need to manually adjust some variables in your script once per node to account for the bitnode multipliers you aren't able to get from the API yet.
