### ISSUE TITLE
Setting product sell price to 0 does not discard

### ISSUE THREAD

**Issue by Draco18s** [bitburner-official/bitburner-src#335]
Setting sell price to 0, instead of discarding, acts as if the product should not be sold at all, contrary to the documentation.

> If the sell price is set to 0, then the product will be discarded.

![image](https://user-images.githubusercontent.com/1750680/214132573-309332bd-55cc-4715-9da3-4d9af22c0607.png)
![image](https://user-images.githubusercontent.com/1750680/214132613-2fa0abe9-891f-43b9-817e-65f9436b5f22.png)
![image](https://user-images.githubusercontent.com/1750680/214132657-d4d65078-9473-478f-a583-dae1bb50806a.png)

- [x] Save file [bitburnerSave_1674372967_BN7x1.zip](https://github.com/bitburner-official/bitburner-src/files/10483070/bitburnerSave_1674372967_BN7x1.zip)
- [x] Version of the game, e.g. Bitburner v2.2.1 (c46cedd5)

**Comment by Mughur** [comment]
I seems that it works properly for materials but not products
