### ISSUE TITLE
array is not defined for unknown reason

### ISSUE THREAD

**Issue by lordudi** [bitburner-official/bitburner-src#336]
- [RUNTIME ERROR
MoneyMaker.js@home (PID - 4)

sources is not defined
stack:
ReferenceError: sources is not defined
    at Module.main (home/MoneyMaker.js:3:10)
    at M (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272253)] - Runtime error

- [[bitburnerSave_1674557003_BN1x1.txt](https://github.com/bitburner-official/bitburner-src/files/10488743/bitburnerSave_1674557003_BN1x1.txt)] - Save file

- [export async function main(ns) {
	sources = ["n00dles", "foodnstuff"]//, "nectar-net", "sigma-cosmetics", "joesguns", "hong-fang-tea", "harakiri-sushi", "max-hardware", "zer0", "neo-net"]
	while (true) {
		for (i in sources) {
			await ns.hack(i)
		}

	}
} ] - Minimal scripts to reproduce the issue
- [ run the script] -  Steps to reproduce

- [ 2.2.1(c46cedd5)] - Version

- [the error happened after I installed augmentation for the first time] - notes

**Comment by Mughur** [comment]
in the `sources = ["n00dles", "foodnstuff"]` line you need to have `var`/`let`/`const` in front of the `sources`. If it doesn't have one of them it doesn't declare that `sources` variable now exist, but tries to redeclare `sources` to be `["n00dles", "foodnstuff"]`, but if it doesn't exist yet it throws `is not defined` error

same with `for (i in sources) {` you need to have one of them in front of `i`

check out https://www.geeksforgeeks.org/difference-between-var-let-and-const-keywords-in-javascript/ for information as to what each of those three mean/work

**Comment by lordudi** [comment]
thanks but I have to ask how did this script worked when I used it in server before I installed the augmentation

**Comment by Zelow79** [comment]
So this issue could probably be closed right?

**Comment by Mughur** [comment]
> thanks but I have to ask how did this script worked when I used it in server before I installed the augmentation

It should've done so. My guess is that you ran some old version of that script, then edited it and when you ran it again it threw an error because it had reference error now.
