### ISSUE TITLE
Overlapping ranges are not allowed! in editor

### ISSUE THREAD

**Issue by redmo2003** [bitburner-official/bitburner-src#338]
Hi, found the following issue in the editor. 

![error](https://user-images.githubusercontent.com/91155384/214764032-3a775f30-0673-4427-8b55-3236618f886f.png)

If you add the code outside the main function and then click beatify, you should be able to recreate the error message.  

```
 /*  augs.forEach(augs => {
           if (!ownedAugs.includes(augs)) {
               //if the aug isn't on this list already.
               if (!tempArray.includes(augs)) {
                   //push the aug into a temp list
                   tempArray.push(augs);
                   //if city is not on list
                   if (!vistCities.includes(city)) {
                       //push city
                       vistCities.push(city);
                   }
               }
           }
           
       });
       */
```

my game version is Bitburner v2.2.1 (c46cedd5)

**Comment by Mughur** [comment]
```js
           }

       });
```
if you remove that empty line it won't throw an error.  Why this (bug and fix) happens I don't know

**Comment by TheMas3212** [comment]
Im going to close this as it looks like a external bug in Monaco, not really anything we can do to fix it. but i guess if someone wants they could try raising it with them
