### ISSUE TITLE
BUG : Can have multiple copies of the same program

### ISSUE THREAD

**Issue by rafael-f** [bitburner-official/bitburner-src#346]
Bitburner v2.2.1 (c46cedd5) (Steam)

So I was creating the FTP program, then I started doing contracts for Cybersec, then I returned to finish the FTPCrack.exe, but it finished without finishing...

![image](https://user-images.githubusercontent.com/14276684/215619713-9cfb1487-77a4-46fa-905b-d058a62c1d8b.png)

![image](https://user-images.githubusercontent.com/14276684/215619751-9e7fbd85-0272-432d-8d21-4df68de6922c.png)

Attached save file...

[bitburnerSave_1675041486_BN1x1.zip](https://github.com/bitburner-official/bitburner-src/files/10540832/bitburnerSave_1675041486_BN1x1.zip)

update: It was probably an issue deleting the temporary incomplete file at some point I guess. I manually removed the file and no error happened, the incomplete message was gone from the programs list and the finished exe worked ok.

**Comment by lossycrypt** [comment]
I still get this in both Bitburner v2.3.1 f55551c0c and Bitburner v2.3.2 aecdbe8

![doubleprogress](https://github.com/bitburner-official/bitburner-src/assets/14168854/4917b870-b3ad-4cff-8f10-9310ce90683f)

Can be reproduced with something like this:
```
/** @param {NS} ns */
export async function main(ns) {
  ns.tail()
  while(true){
    ns.singularity.createProgram('ServerProfiler.exe')
    ns.singularity.createProgram('ServerProfiler.exe')
    await ns.singularity.workForFaction('New Tokyo', 'hacking', false)
    await ns.sleep(50)
  }
}
```
