### ISSUE TITLE
In terminal arguments, numbers in quotes are interpreted as numbers instead of strings.

### ISSUE THREAD

**Issue by Exorbio** [bitburner-official/bitburner-src#349]
Per the documentation, wrapping a number in quotes is supposed to treat it as a string instead of a number, but they are converted to numbers.

Simple one line code to test: 
/** @param {NS} ns */
export async function main(ns) {
	ns.tprint(typeof ns.args[0]);
}

Running that script with the first argument as "5" for example, outputs "number".

On Bitburber v2.2.1

**Comment by LiamGeorge1999** [comment]
The function that parses the individual arguments would receive a version of any "in quotes" args with the quotes removed, which caused issues where the arg was parsable to a number when lacking the quotes. I simply added a flag to the parser that dealt with the list of args and handed it to the parser that deals with individual args, overriding the result.

I'm fairly new to contributing to open source stuff, so I apologise if there's a more elegant approach or I missed something -- but this will fix the issue insofar as I could tell.
