### ISSUE TITLE
CodingContract API gives insufficient info for some 2D grid contract types

### ISSUE THREAD

**Issue by Exorbio** [bitburner-official/bitburner-src#350]
For some (maybe all?) of the contracts involving a 2D grid, for example "Unique Paths in a Grid II", the ns.codingcontract.getData(...) function returns a linear list of comma separated values, with no indication of what the 2D grid's x and y extents should be.

For one example of "Unique Paths in a Grid II", running the contract from the terminal showed the grid like this:
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,

But using ns.codingcontract.getData(...) in a script returned this:
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

From the script there's no way to tell if this should be a 2x8, 4x4, or 8x2. The 8x2 and 4x4 would have different solutions.

I've seen one other contract type that had the same issue, but I don't recall what it was. And it may in fact be an issue with all contract types that provide a 2D grid as the problem input.

On BitBurner v2.2.1

**Comment by Draco18s** [comment]
The data given is an array of arrays. It isn't one long string of 0s.

`[[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]]`

is not

`[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]`

**Comment by Exorbio** [comment]
Ah, I see what I was doing wrong. When printing to the terminal I was trying to indent the data like so:
`ns.tprint("        " + ns.codingcontract.getData(file, s.hostname));`

Which apparently coerces the object to a flattened string and was printing this:
`list-contracts.js:         0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0`

But when I changed the print statement to this:
`ns.tprint("        ", ns.codingcontract.getData(file, s.hostname));`

I get the expected output:
`list-contracts.js:         [[0,0,0,0,0],[0,1,0,0,0],[0,0,0,0,0],[0,1,0,0,0],[1,0,0,0,1],[0,0,1,0,0],[0,0,0,0,0]]`


Sorry about that. Thanks!
