### ISSUE TITLE
programs are not being unlocked

### ISSUE THREAD

**Issue by Rainevan** [bitburner-official/bitburner-src#351]
I have hack lvl 249 however DeepscanV2.exe and HTTPWorm.exe are still locked and can't be created 
v2.2.1

**Comment by Mughur** [comment]
`DeepscanV2.exe` requires hack level 400 to create.
The create page tells you "Unlocks in: X hacking levels", not "Unlocks at: X hacking level". Meaning that you need X levels **more** than you currently have, not that you need **total** of X levels.
