### ISSUE TITLE
Set theme is not working both on steam version and web version.

### ISSUE THREAD

**Issue by lego7set** [bitburner-official/bitburner-src#363]
So, I'm on v2.2.1 and the `ns.ui.setTheme` function is not doing anything except fill up my logs. Reset theme and get theme are working but set theme is not. I tried the example in the script editor slightly modified but it isn't working. Here is my more advanced script that is also not working (with `ns.ui.setTheme`.)

Minimal steps to reproduce:
1. [Download this script ](https://github.com/bitburner-official/bitburner-src/files/10716114/Minimal.Steps.to.Reproduce.zip)
2. Unzip it.
3. Get the script into Bitburner and run the script.
4. Watch the terminal get filled with color-changing text but the theme isn't doing the same.

If this is not an issue with the game, please tell me why this is occurring.

**Comment by Snarling** [comment]
Yeah that's my bad, there was some backwards logic that never got caught.
Fixed by f16a4f1. At this time the fix is only live at https://bitburner-official.github.io/bitburner-src/
