### ISSUE TITLE
Steam save options don't consistently work as expected

### ISSUE THREAD

**Issue by Weazel7** [bitburner-official/bitburner-src#364]
I am using v2.2.1, the steam version.
If you begin to do hacking contracts for a faction, and then quit while doing the contracts, when you relaunch the game, you are no longer in that faction; however, if you wait about 10 seconds, you get an invite to join the faction you were doing work for, but with 0 reputation now.

**Comment by TheMas3212** [comment]
Is it possible you closed the game before autosave happened or did you join the faction a long time ago?

**Comment by Snarling** [comment]
What save-related options do you have enabled in the File menu?
![image](https://user-images.githubusercontent.com/84951833/218661942-268fa22e-b90f-4142-90a5-a75ebe85215e.png)

I would recommend for the time being disabling all of these options, at which point you will be using the normal save mechanic the internal game uses (and any backup save files you want to keep will need to be done via manual exporting). With all of these disabled, hitting the save button ingame and then closing the game window will not lose you any progress. Hitting the save button ingame always does the "ingame save" but I believe it only sometimes does a "hard save" creating a new file if you have the "auto-save to disk" option selected. If you then have "restore newest on load" selected, it will load your newest hard-save, which may be older than your actual ingame progress.

I haven't looked deeply into the electron-specific save file code, but I'm pretty sure this is the issue.

**Comment by Snarling** [comment]
#196 is another example of behavior that is probably related to electron-specific save code. Closing that issue and using this one as the main "Steam save options need some work" issue.

**Comment by Weazel7** [comment]
I believe that my issue was not saving the game properly. I apologize for opening a false issue.
