### ISSUE TITLE
API Server broken?

### ISSUE THREAD

**Issue by madhyas** [bitburner-official/bitburner-src#383]
VSCode extension "Bitburner VSCode Integration v1.3.3" works fine with BitBurner V1.7
With BitBurner V2.2.2 it is no longer possible to push files from VSCode to the game.

Steps to reproduce:
- BitBurner: 
  - enable API Server
  - copy Token
- Install VSCode:
  - install Extension "Bitburner VSCode Integration v1.3.3"
  - open new Folder
  - goto Extensions -> Bitburner VSCode ... -> Extension Settings:
    - paste Token under Auth Token
  - goto explorer
    - create new file "dummy.js"
    - write something in the file
    - from the file editor context menu chose: BitBurner: Push File To The Game

There is no error message and the file does not get pushed to the game.
Instead there is an error message displayed in the debug console:

![image](https://user-images.githubusercontent.com/126122387/220801844-459dbc02-41e2-4bd4-b113-efbc01246356.png)

**Comment by Snarling** [comment]
May be related to the security fix from #319 .

**Comment by NoCanDouCan** [comment]
Could it be a general Electron 21+ issue? There was a change in Electron and "Buffer" usage:
https://www.electronjs.org/blog/v8-memory-cage

And this looks like the same issue:
https://github.com/bytenode/bytenode/issues/10

**Comment by PiezPiedPy** [comment]
Same for me running the steam version v2.2.2 and Ext v1.3.3. Worked with v2.2.1

**Comment by NoCanDouCan** [comment]
seems that the error is located here:
https://github.com/bitburner-official/bitburner-src/blob/dev/src/Electron.tsx

`function initWebserver()`
`...`
`code = Buffer.from(code, "base64").toString();`

**Comment by Snarling** [comment]
Fixed by 211e2bc, we will try to get that fix out to the steam versions soon.
