### ISSUE TITLE
Deprecation of nFormat: missing 'formatMoney'

### ISSUE THREAD

**Issue by riking** [bitburner-official/bitburner-src#393]
# include (where relevant)

- [ ] Save file
- [x] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [x] Version of the game, Bitburner v2.2.2

Sample script:

```javascript
ns.tprint(`Money : ${ns.nFormat(ns.getServerMaxMoney(this.name), '$0.00a')} ...`);
```

Add a `formatMoney` function to replace the above use of nFormat.

**Comment by Snarling** [comment]
Formatting is specifically different for ram, percents, and regular numbers. Money isn't fundamentally different from numbers, so you can just use formatNumber. e.g.
```js
ns.tprint(`Money : \$${ns.formatNumber(ns.getServerMaxMoney(this.name), 2)} ...`);
```

We could still add a new function though.

**Comment by riking** [comment]
after rechecking the documentation and seeing it auto adds SI suffixes: yeah it's probably fine actually.
