### ISSUE TITLE
UI: Change name/description of Hacknet-related stats (also Netburner Augmentations)

### ISSUE THREAD

**Issue by MaWo2** [bitburner-official/bitburner-src#403]
I like to suggest to change the names/description of Hacknet-related player stats and the Netburner Augmentations.

It's always "Hacknet Nodes" (e.g. "Hacknet Node Production" in Player stats tab). 

The description for BN9 itself states that "Hacknet Mutliplier" are increased.
Maybe "Node" can be removed from the stats and augments.

**Comment by rayanth** [comment]
I think that `Hacknet Node Purchase Cost` should remain unchanged, as changing it to "Hacknet Purchase Cost" could be misleading. `Hacknet Node Level Upgrade Cost` may also fall into that "potentially misleading if renamed" bucket.

There's also a lot of places in Documentation and Achievements that reference the 'Node' that may need to be updated at the same time, if the proposed is performed.
