### ISSUE TITLE
Gang - "All upgrades Owned! Next at $..." doesn't scale for respect.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#415]
The more respect, the lower the cost of items in equipment.  And if there are still items to purchase that you can't yet afford, it tries to mention the next threshold to aim for (as you reach them).  But those values don't seem to scale by the user's current respect, always showing the same incorrect values to the user.  Which inflates them crazily high when looking at augments versus the actual cost needed.

Meaning the game says I need $50b to see/buy the next item, but the most expensive item currently is less than $3b (the Graphene Bone Lacings).  This is when you're slowly winning all the territory, and have enough respect to discount by -94.93%.

Thankfully the items WILL be shown before that incorrect value, but it'd be nice if it showed something much closer to the amount of money needed to see the next item.

I assume a good fix would be wrapping the value before printing in the same scaling function used for items.  Maybe rounding it up to make it prettier (or down...I'm not sure which direction makes sense).  It could aim for 1-2 significant figures and be tidy yet accurate.

Version: Steam v2.2.2 (6eb5b5ab)

**Comment by LiamGeorge1999** [comment]
Was a fairly good guess, but interestingly it turns out that the function that does this takes the whole upgrade, not the upgrade's cost 🤷 Either way, change made, pr made
