### ISSUE TITLE
TERMINAL: parser treats empty quotes as though non-existant, treats quotes with spaces as though 0

### ISSUE THREAD

**Issue by LiamGeorge1999** [bitburner-official/bitburner-src#419]
running any script with params `""` or params `"      "` (number of spaces between quotes appears not to effect behaviour) leads to empty strings being treated as though not present if they're the last argument and otherwise being converted to the number 0, and all non-empty, space-only strings being converted to the number 0.

Script contents irrelevant.

![image](https://user-images.githubusercontent.com/77801642/224338217-816b13fc-8bdd-4eae-83ef-fdc7a532b686.png)

found in bitburner v1.2.2 (6eb5b5ab)
recreated in Bitburner v1.3.0 (216bf616)

**Comment by LiamGeorge1999** [comment]
I plan to look at resolving this tonight if I have time

**Comment by LiamGeorge1999** [comment]
looking at Parser.ts, this will need a fair rethink. I propose instead of using trim and replace, starting by seeking unquoted spaces and splitting the arguments up based on these, then removing any members of that collection with length = 0 to handle double-spacing, instead of the current method of replacing any set of adjacent spaces with a single space.

I've not yet figured out why an empty string is 0 or why a string with spaces only is 0.

**Comment by Snarling** [comment]
This is fixed now.

With an even number of quote marks, they are grouped and the entire content within them is preserved. With an odd number of quote marks, the last quote mark is just considered to be a string on its own.

![image](https://user-images.githubusercontent.com/84951833/234289874-fcea2054-ad9b-43e3-9184-9a218025d923.png)
