### ISSUE TITLE
Closing file in editor sometimes asks to save changes when nothing has changed

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#42]
[macdjord]
Closing a script by clicking the 'X' button on its tab at the top of the screen will sometimes ask if you want to save changes, even though the tab was not showing the 'unsaved changes' asterisk. 

Note: Every time this has happened, it has been a file I *thought* I had already saved, so I believe the problem is that the editor is asking to save changes when there are none, but it's possible the files *had* changed and I'd forgotten, in which case the actual bug is 'editor not displaying unsaved-changes asterisk'.

Version: a3c599e6

**Comments From Original Issue**

[phyzical]
> @macdjord mind giving exact repo steps please?

[macdjord]
> @phyzical Don't have them; that's why I said 'sometimes'.

[phyzical]
> im sorry but there is only so much time one can dedicate to a plethora of bug reports, without enough information bugs get closed to reduce the load of trying to fix more important bugs.

[OriginalRobotWizard]
> This is super easy 100% reproducible:
> 1. nano test.txt
> 2. Close and save
> 3. Start over at 1 (popup to be asked to save will be displayed every time for .txt files) 

[phyzical]
> thx is it only txt files by chance?

[OriginalRobotWizard]
> Yes, it only happens with .txt files. Not with .js, .script, or .ns files.

**Comment by Snarling** [comment]
This was resolved with previous fixes to dirty file indicator. Verified by using reproduction steps listed - no dialog produced when file is not modified.
