### ISSUE TITLE
Argument Parsing - Minor documentation error

### ISSUE THREAD

**Issue by JonathanBerkeley** [bitburner-official/bitburner-src#431]
Argument parsing example given in documentation: https://github.com/bitburner-official/bitburner-src/blob/dev/doc/source/basicgameplay/terminal.rst#argument-parsing 

Doesn't work because the line:
`ns.tprint("Number of args: " + args.length);` 
Should be:
`ns.tprint("Number of args: " + ns.args.length);`

I would change it myself but I don't understand how the doc generation for this project works.

**Comment by Snarling** [comment]
So for the .rst files in the `doc` folder, changes can just be submitted directly on those files, they're not generated from anywhere.

For the markdown folder and the .md files inside, changes are made in NetscriptDefinition.d.ts file which is used to generate all the markdown.

**Comment by Snarling** [comment]
Fixed by 4934801
