### ISSUE TITLE
 HTTPWorm.exe is both 2.25% and fully unlocked at the same time

### ISSUE THREAD

**Issue by codegirl140** [bitburner-official/bitburner-src#433]
- [save.zip](https://github.com/bitburner-official/bitburner-src/files/11009495/save.zip)
- Old Save, Unknown steps to reproduce
- Bitburner V2.3.0 (b9b5a621) Steam Beta Branch

**Comment by Snarling** [comment]
Similar to known issue #346 , closing this one as a duplicate.
