### ISSUE TITLE
Error: somehow connected to a server that does not exist. spider (at "Terminal")

### ISSUE THREAD

**Issue by codernator** [bitburner-official/bitburner-src#439]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [x] Minimal scripts to reproduce the issue
- [x] Steps to reproduce

- Reproduction Script
test.js:
export async main(ns) {
   ns.renamePurchasedSever('foo', 'bar');
}

- Steps to Reproduce
> connect foo
> nano test.js
> write above script, and return to terminal
> run test.js

### Environment

* Error: Error: somehow connected to a server that does not exist. spider
* Page: Terminal
* Version: v2.2.2 (6eb5b5ab)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by Snarling** [comment]
Already fixed in 2.3 by #438
