### ISSUE TITLE
command line parser bugs on processing `-t` and  `--tail`

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#44]
[vladtepesch]
According to documentation the `run` command arguments `-t` and `--tail` have to be following directly to the script name. ( -->  https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html#run - at least `-t` is mentioned there)
But the parser also interprets them as special arguments if they are later in the arg list. this prevents them to be passed to the executed script.

for example starting a `runon` script (that is supposed to start a script on a remote server)
``` 
run runon.js pserv-5 somescript.js -t 500 --tail omnitek
```
where the script itself is supposed to process the `-t` and `--tail` parameter did not see them and itself gets executed with 500 threads

**Comments From Original Issue**

[mbrannen]
> I believe this might be a misunderstanding of the command and intended usage.
> 
> From the docs
> `run [file name] [-t] [num threads] [args…]`
> 
> Translating that to the command you wrote looks like this
> `run [file name = runon.js ] [-t] [num threads = 500] [args… = {'pserv-5', 'somescript.js', '--tail','omnitek'}]`
> 
> I would suggest somescript.js having arguments that you can then pass when `exec()` is run from runon.js
> Try taking out the `-t 500` and using just `500` instead.
> 
> So in runon.js you might find something like this:
> ```
> //exec(script, hostname[, numThreads=1[, args...]])
> exec(scriptToRun, serverToRunOn, threads,  serverToHack)
> ```

[vladtepesch]
> > I believe this might be a misunderstanding of the command and intended usage.
> > 
> > From the docs `run [file name] [-t] [num threads] [args…]`
> > 
> > Translating that to the command you wrote looks like this `run [file name = runon.js ] [-t] [num threads = 500] [args… = {'pserv-5', 'somescript.js', '--tail','omnitek'}]`
> > 
> > I would suggest somescript.js having arguments that you can then pass when `exec()` is run from runon.js Try taking out the `-t 500` and using just `500` instead.
> > 
> > So in runon.js you might find something like this:
> > 
> > ```
> > //exec(script, hostname[, numThreads=1[, args...]])
> > exec(scriptToRun, serverToRunOn, threads,  serverToHack)
> > ```
> 
> according to the docs the `-t` argument has to be passed right after the script name to be processed by the command line interpreter (I would expect the same for `--tail`).  This implies that if I pass `-t` not as the second argument it should be visible within the `ns.args` array but that is not the case.
> 
> I wanted my `runon.js` to parse for the optional `-t number` parameter and pass its number to the `ns.exec` call.
> 
> so at the end according to the docs the following should happen:
> (this obviously works)
> 
>     > run script.js -t 1000 123 foo bar
> 
> should run the script `script.js` with 1000 threads and the arg array `[123, 'foo', 'bar']`
> 
> but this does not work as described:
> 
>     > run script.js 123 foo bar -t 1000 
> 
> should  (according to the docs) run the script `script.js` with 1 threads and the arg array `[123, 'foo', 'bar', '-t', 1000]`. 
> But instead it has the same result as the first command.
> 
>

**Comment by Snarling** [comment]
This is just a documentation issue. The position of the tail flag shouldn't matter.

**Comment by Phlarx** [comment]
I spent some time fighting this today (I wanted `-t` as a short form of `--travel` for a script that may need to travel to another city to complete).

I would have much preferred if `-t` for threads and `--tail` must be *before* the script name, thereby allowing everything after to be considered an argument. I attempted to alias my own `run` command (like I've done for `cat` and a few others), but even that does not work, since even if `-t` is specified at all, anywhere, it is consumed (and there is no other way to run scripts from the command line).

**Comment by Snarling** [comment]
You can force the parser to consider -t to be a flag for your script (and not a flag for the run command) by passing the argument `--` before -t.

![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/37ae42c4-b9e1-4988-83bb-827565959e99)

**Comment by Snarling** [comment]
Maybe at initial release a better design would have been requiring --tail and -t to be before the script name, and we could then make sure the rest is considered arguments for the script, but at this point I think that would be too breaking of a change.

**Comment by Phlarx** [comment]
I agree it would probably too breaking.

Thanks for the tip about `--`, it hadn't occurred to me to try that.

**Comment by Hoekstraa** [comment]
This looks like a Won't Fix.
Hence I'm closing this issue. Feel free to reopen on new insights!
