### ISSUE TITLE
Support for && ?

### ISSUE THREAD

**Issue by noahyor** [bitburner-official/bitburner-src#445]
While I was playing Bitburner, I wanted to go home and clear the screen, like this:
```
home && clear
```
But instead of it doing what I expected, it gave me an error message:
```
Incorrect usage of home command. Usage: home
```
It's not a huge issue, but I just thought of it as a little weird.

**Comment by Snarling** [comment]
`home;clear` is the syntax you want for nearly the same functionality.

Part of the issue with trying to support && is that right now terminal commands don't actually have process exit codes / returns, so e.g. if the first command results in an error, the second command will still take place, which makes the existing functionality a bit different from && syntax.

**Comment by noahyor** [comment]
Very interesting, thanks!
