### ISSUE TITLE
The Recursion Level 1 bitnode multipliers wrong

### ISSUE THREAD

**Issue by ZachHaber** [bitburner-official/bitburner-src#455]
On "The Recursion" for my first attempt at it, the bitnode multipliers says that hacking level should be 98.039%, but the hacking level shown in the UI and acted upon is based on 100% hacking Level from the bitnode multiplier. The approach I've used using the calculateSkill formula by mutliplying the player and the bitnode multipliers together has been accurate for calculating the skill level until this bitnode, which has been consistently below.

Version: v2.2.2 (6eb4b5ab)

Script:
```js
const player = ns.getPlayer();
// ns.tprint(ns.formatNumber(player.exp.hacking, 3));
const bitnodeMults = ns.getBitNodeMultipliers();
const mult = player.mults.hacking * bitnodeMults.HackingLevelMultiplier;
ns.tprint(
  JSON.stringify(
    {
      withBitNodeMults: ns.formulas.skills.calculateSkill(player.exp.hacking, mult),
      withPlayerOnly: ns.formulas.skills.calculateSkill(player.exp.hacking, player.mults.hacking),
      playerSkill: player.skills.hacking,
      playerMult: player.mults.hacking,
      bitnodeMult: bitnodeMults.HackingLevelMultiplier,
      overallMult: mult,
    },
    undefined,
    2,
  ),
);
```

Output:
```
{
  "withBitNodeMults": 744,
  "withPlayerOnly": 758,
  "playerSkill": 758,
  "playerMult": 1.3907151636687434,
  "bitnodeMult": 0.9803921568627451,
  "overallMult": 1.3634462388909248
}
```

Steps: go to The Recursion bitnode and check the difference between skills based on the formulas vs the actual values.
[bitburnerSave_1680231014_BN12x1.zip](https://github.com/bitburner-official/bitburner-src/files/11117695/bitburnerSave_1680231014_BN12x1.zip)

**Comment by Snarling** [comment]
Fixed by d9ef53e (pinging #484 as well)
