### ISSUE TITLE
Long and short form for `ns.flags`

### ISSUE THREAD

**Issue by brunnerh** [bitburner-official/bitburner-src#477]
It would be nice if a single argument could support both a short and long form, e.g. `--purchased` would be equivalent to just `-p`.

Not entirely certain what the API should look like, maybe the single letter form could be automatically generated if there are no conflicts, i.e. the letter used in the command is only used at the start of one of the arguments and an "ambiguous argument error" could be thrown otherwise.

For manual definition maybe allow using an array, e.g.

```js
// kill-scripts.js
const { hacked, hacknet, purchased } = ns.flags([
	[['hacked', 'h'],  false], // --hacked, -h
	[['hacknet', 'n'], false], // --hacknet, -n
	['purchased',      false], // --purchased, -p (-p added by default)
])
```

This syntax also could support arbitrary other aliases, both whole words and single characters.

**Comment by Snarling** [comment]
This can already be accomplished inside your script, e.g.:
```js
export async function main(ns) {
  let flags = ns.flags([["p", false], ["purchased", false]])
  const purchased = flags.purchased || flags.p;

  ns.tprint(purchased);
}
```
![image](https://user-images.githubusercontent.com/84951833/232787305-1e7c08ce-2297-4a42-9f41-b169716b6372.png)

**Comment by brunnerh** [comment]
I am aware of this approach but would rather not re-declare everything multiple times and merge the resulting values when they really are just one argument. Some of my scripts have half a dozen such arguments.

**Comment by d0sboots** [comment]
You also could look at https://github.com/tj/commander.js if you want more full-bodied command-line processing, although you might have to tweak it slightly to avoid pulling in `process`.

**Comment by ABruel** [comment]
Just write a function that does it for you...

This doesn't include your idea of populating short aliases if there are no conflicts, because I didn't want to implement it (and it's probably a bad idea), but feel free to add it. It is also in typescript so you won't be able to just copy it into the game (you can however use typescript to code your scripts using vscode and the bitburner extension). Just remove every `: <type>` and it should work. 

```typescript
export async function main(ns: NS) {
  const flags = aliasFlags(ns, [
    [["hacked", "h"], ""],
    [["hacknet", "n"], ""],
  ]);

  ns.tprint(JSON.stringify(flags, null, 4));
}

const aliasFlags = (
  ns: NS,
  flags: [string | string[], string | number | boolean | string[]][]
) => {
  const flagsArg = flags.flatMap((f: any) => {
    const [maybeLargeFlag, defaultV] = f;

    if (Array.isArray(maybeLargeFlag)) {
      return maybeLargeFlag.map((flag) => [flag, defaultV]);
    }
    return [maybeLargeFlag, defaultV];
  });

  const flagsObj = ns.flags(flagsArg);

  flags.forEach((f) => {
    const [maybeLargeFlag, defaultV] = f;
    if (Array.isArray(maybeLargeFlag)) {
      const flag = maybeLargeFlag.find((f) => flagsObj[f] !== defaultV);
      if (flag) {
        maybeLargeFlag.forEach((f) => {
          flagsObj[f] = flagsObj[flag];
        });
      }
    }
  });
  return flagsObj;
};

```

**Comment by ABruel** [comment]
You'll probably want to improve the comparison `flagsObj[f] !== defaultV` to work with arrays. 

I don't know if `ns.flags()` returns the same reference for arrays or clones it. If it clones, you'll need to do a [deep compare](https://masteringjs.io/tutorials/fundamentals/compare-arrays) if it's an array.

**Comment by catloversg** [comment]
@d0sboots Can we close this? `ns.flags` is good enough to support normal cases. If the player wants to parse script arguments in a fancy way, they need to use a library.

**Comment by d0sboots** [comment]
I agree with the others here: Many things in BitBurner are "just good enough" to get by with, but basic enough that they leave you wanting a better solution. Unlike in the real world, we don't always improve those things so that they're great, but rather leave them as itches for players to scratch. I think this is one of those things.
