### ISSUE TITLE
infiltration resets tail window settings

### ISSUE THREAD

**Issue by Arthan-the-one** [bitburner-official/bitburner-src#483]
When one or multiple script tail windows are open, whenever an infiltration minigame is started, their position and status is reset (they appear in the center of the screen).
I would expect them to reappear where they were before the minigame was started.

To reproduce:
- open any script tail window, regardless of wether the script is active or not
- move the window from the initial position, resize it, minimize it
- initiate an infiltration minigame
- cancel/succeed/fail the infiltration
- the window is now:
  - in the initial size
  - at the initial position
  - not minimized
- Bitburner v2.2.2 (6eb5b5ab)

(Edit: duplicates #25 )

**Comment by Snarling** [comment]
Fixed by #769
