### ISSUE TITLE
Off by one in BitNodeMultipliers calc for BN12

### ISSUE THREAD

**Issue by thetaphi** [bitburner-official/bitburner-src#484]
https://github.com/bitburner-official/bitburner-src/blob/d3f9554a6eee229e66d3712eeecd3b941f43fdb7/src/BitNode/BitNode.tsx#L854

Entering BN12.1, it looks like we've got a 1.02 ** 0 here. Results in donation favor threshold of 150 when 153 would be correct, and all sorts of other shenanigans.

Suggested fix after discord discussion is in line 976.

**Comment by Snarling** [comment]
Same issue as #455, closing as duplicate.

Will take a look at that suggested fix, thanks

**Comment by thetaphi** [comment]
👍
