### ISSUE TITLE
Hacknet LevelBaseCost is using unintuitive constant.

### ISSUE THREAD

**Issue by hydroflame** [bitburner-official/bitburner-src#487]
The formula to [calculate the cost of upgrading hacknet levels](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/formulas/HacknetNodes.ts#L31) uses the overall `hacknets base cost / 2` instead of the [variable made specifically for it](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/data/Constants.ts#L5)

So LevelBaseCost should be set to 500 and [the formula](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/formulas/HacknetNodes.ts#L31) should be updated to use LevelBaseCost

Also don't forget to update [this line](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/formulas/HacknetNodes.ts#L27)

**Comment by Snarling** [comment]
Fixed by 4e07900
