### ISSUE TITLE
hostname in tail window titlebar obstructs the script name

### ISSUE THREAD

**Issue by Snarling** [bitburner-official/bitburner-src#488]
Script name is more important so it should be at the front. Probably will move the servername to the back of the string, something like:

`myScript true 1 "string" @hostname`

**Comment by unkwntech** [comment]
After seeing the suggestion on the PR, perhaps a better(?) option would be to add a function to change the tail window's title, something to the effect of `ns.renameTail(string, pid)` .   This would alleviate the root complaint from the comment in the PR, and perhaps open up some more options for using the tail windows to display information.

**Comment by brunnerh** [comment]
I would also suggest just not showing it for `home` as that is the default.
And for foreign servers the option to turn it off would be great.

**Comment by Snarling** [comment]
This has been reverted, and additionally you can set the title of a tail window to whatever you want with ns.setTitle
