### ISSUE TITLE
Contract: Generate IP Addresses 

### ISSUE THREAD

**Issue by MarkJKC** [bitburner-official/bitburner-src#493]
- [X] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [X] Version of the game, e.g. Bitburner v2.2.2 (6eb5b5ab)

Contract Data: 138221101245
Answered with 1 and failed

Attempted in both script and terminal.

[bitburnerSave_1682538254_BN1x2.zip](https://github.com/bitburner-official/bitburner-src/files/11336693/bitburnerSave_1682538254_BN1x2.zip)

**Comment by MaWo2** [comment]
You need to supply the IP address. Not the number of possible addresses.

I tested it with your file and it worked.
Next time, please indicate where to find the contract.

**Comment by Snarling** [comment]
Was just a usage error
