### ISSUE TITLE
save files should be zipped

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#5]
[hydroflame]
null

**Comments From Original Issue**

[phyzical]
> i think this one is closable too (unless we dont zip given certain conditions?)

[phyzical]
> (unless we are referring to export in settings?)

[Master-Guy]
> Just a basic ZIP reduces used storage by about 50%. In my case from ~160 MB to ~80 MB.
> In a game that is all about optimization, this seems to be a basic thing to do :)

**Comment by Snarling** [comment]
See #800
