### ISSUE TITLE
getCorporation() lacks issueNewSharesCooldown property

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#506]
Hi there,

Steam, BB version 2.2.2

here is my script:

```
const corp = ns.corporation;

const getCorpInfo = (verbose = false) => {
		const corpData = corp.getCorporation();
		const cConst = corp.getConstants();
		const cData = {
			divisions: corpData.divisions,
			ownedShares: corpData.numShares,
			isPublic: corpData.public,
			sharePrice: corpData.sharePrice,
			shareSaleCooldown: corpData.shareSaleCooldown,
			totalShares: corpData.totalShares,
			dividendRate: corpData.dividendRate,
			issueNewSharesCooldown: cConst.issueNewSharesCooldown,
			upgradeNames: cConst.upgradeNames,
			unlockNames: cConst.unlockNames, // one-time unlock upgrades
			researchNamesBase: cConst.researchNamesBase,
			researchNamesProductOnly: cConst.researchNamesProductOnly,
			materialNames : cConst.materialNames,
		}
		if (verbose) {
			ns.tprint(`Corporation info: \n\t sharePrice\t\t = ${ns.formatNumber(cData.sharePrice, 2)}` +
				`\n\t shareSaleCooldown\t = ${ns.tFormat(cData.shareSaleCooldown * 200)}` +
				`\n\t issueNewSharesCooldown\t = ${ns.tFormat(cData.issueNewSharesCooldown * 200)}` +
				`\n\t totalShares\t\t = ${ns.formatNumber(cData.totalShares, 3)}` +
				`\n\t divisions\t\t = ${cData.divisions}` +
				`\n\n\t materialNames\t\t = ${cData.materialNames}` +
				`\n\n\t Common researches\t = ${cData.researchNamesBase}` +
				`\n\n\t researchNamesProductOnly\t = ${cData.researchNamesProductOnly}` +
				`\n\n\t One-time upgrades\t = ${cData.unlockNames}` +
				`\n\t upgradeNames\t\t = ${cData.upgradeNames}\n`

			);
		}
		return cData;
	}
```

All other data changes, but issueNewSharesCooldown allways says 12 hours :)

I'm not a javascript programmer (yet), so please, be kind :)

**Comment by d0sboots** [comment]
What you're reporting isn't a bug; everything in CorpConstants is a *constant*, and thus does not change. CorpConstants.issueNewSharesCooldown is the length of the cooldown that is applied when you buy new shares.

However, you've highlighted something that *is* a failure of the current API, which is the lack of a corpData.issueNewSharesCooldown.

**Comment by AssenD** [comment]
If I may add, I would like to have something like bribeFactionCooldown, too.

BTW, Thanks for the cool game! It's a lot of fun learning javascript that way!

**Comment by AssenD** [comment]
Sorry, I just now realise bribing factions has money threshold.

**Comment by AssenD** [comment]
Two patches and one major version later and it's still here?
@Hoekstraa , please change the label to bug.

**Comment by AssenD** [comment]
@Hoekstraa  Also similar is the lack of `makesMaterials`  in Division data which is found in IndustryData.
Could be in separate issue, but I think they are related.
