### ISSUE TITLE
Script blobs not disposed before dropping reference to script.

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#51]
[alainbryden]
https://github.com/danielyxie/bitburner/blob/176ddd4f0b30a9d69dda35b2dfabc972ac069d3e/src/Server/BaseServer.ts#L201

In the implementation of `rm` (a.k.a. `BaseServer.RemoveFile`) we remove a script by slicing it out of our array - but before we do so we should go:
```
URL.revokeObjectURL(this.scripts[i].url);
```
So that the blob associated with this script can be garbage collected.

**Comment by Hoekstraa** [comment]
I'm reading the code of `dev` today, and it seems like we're not doing this yet.

**Comment by d0sboots** [comment]
We do revoke URLs properly. I'm on mobile so I can't cite the exact line number, but the current impl revokes URLs immediately after they are loaded, so there is no chance of a leak.
