### ISSUE TITLE
Reload and Kill Running Scripts also resets zoom level

### ISSUE THREAD

**Issue by Person-93** [bitburner-official/bitburner-src#523]
To reproduce the issue, zoom in, then reload + kill all scripts using the menu buttons at the top.

This happens in the steam version
Bitburner v2.2.2 (6eb5b5ab)

**Comment by myCatsName** [comment]
https://www.electronjs.org/docs/latest/api/web-contents#contentsforcefullycrashrenderer

https://www.electronjs.org/docs/latest/api/web-frame

https://www.npmjs.com/package/electron-config

menu.js and utils.js

Some of that might be helpful for a bug fix in future
