### ISSUE TITLE
Corp: Software Materials incorrect?

### ISSUE THREAD

**Issue by jmccarty3** [bitburner-official/bitburner-src#524]
Is it expected that the Materials produced by and required for products in the Software Industry overlap with the production multipliers?  Looking through the the Industry data, Software is the only one with this type of overlap which makes it inconsistent. The overlap in materials also appears to cause conflicts when scripting buy rates to boost production while also using the Smart Supply configuration.

Disabling smart supply for Hardware does work around this issue it is just inconsistent which makes it seem unintentional.

**Comment by d0sboots** [comment]
It is intentional, that is one of the quirks of running a Software division.

That said, software is not the best division to use (in 2.2.2) unless you're doing some esoteric strategies, so it also doesn't come up much.
