### ISSUE TITLE
Major Update 2.3.0

### ISSUE THREAD

**Issue by Blueduckraider50** [bitburner-official/bitburner-src#528]
Getting "An error occured while updating Bitburner (missing executable)"
steamapps\common\Bitburner\bitburner.exe
(Error pops up when I launch the game)
When I open local folders I see steamapps\common\Bitburner\bitburner-win32-x64\bitburner.exe
I can still play normally if I launch the exe manually, but can't launch through steam anymore.

**Comment by Blueduckraider50** [comment]
Aaaand, you fixed it. Nice. Thanks

**Comment by Snarling** [comment]
Yeah sorry about that!
