### ISSUE TITLE
Alias requires different syntax now for quoted string

### ISSUE THREAD

**Issue by Starlit6967** [bitburner-official/bitburner-src#531]
- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce: _attempt to create an alias._ 
- [x] Version of the game: **Bitburner v2.3.0 (8d2d8ab9e)**

Maybe I'm just being stupid, all of this is pretty new to me, but I think there might be a problem with the alias command. While trying to create a new alias the terminal kept giving me the "Incorrect usage of alias command" error. After double checking my formatting and everything and continuing to receive the error, I decided to test out the command on something I already knew worked: the nuke alias given as an example for the alias command. Despite copy/pasting the prompt it still gave me the same error as before. I'm including a screengrab of my "experiment" in case that helps. 

As I said at the opening, I'm very new to coding & Bitburner so I could just be making a stupid mistake, and if that's the case sorry for wasting your time, but for the life of me I'm not sure what I could be doing wrong (hence,this report).
![Alias](https://github.com/bitburner-official/bitburner-src/assets/134721913/c5c09c82-3b54-4add-b4a1-00165d2c0c4f)

**Comment by Rekori** [comment]
@Starlit6967 The "alias" command somehow got change to: alias [-g] ["aliasname=value"]

**Comment by Snarling** [comment]
Yeah this was an unintentional effect of the way terminal command parsing changed. For now `alias "nuke=run NUKE.exe"` should work, but I will probably try and make some changes later on so the previous way works again

**Comment by Snarling** [comment]
The original usage has been restored by #545
