### ISSUE TITLE
Recovery mode activated after loading old save

### ISSUE THREAD

**Issue by thePalindrome** [bitburner-official/bitburner-src#532]
Not sure if this is an issue that is actionable, but the game suggested I upload something anyway!
The save is from around Feburary of 2022, and was renamed from .json because github refused it otherwise

[RECOVERY_BITBURNER_1685130768.txt](https://github.com/bitburner-official/bitburner-src/files/11579575/RECOVERY_BITBURNER_1685130768.txt)

Version: v2.3.0 (3e14a0839)

**Comment by d0sboots** [comment]
I'll take a look at this one later today.

**Comment by d0sboots** [comment]
When I try to import that savegame, I see the following toast:
![image](https://github.com/bitburner-official/bitburner-src/assets/459704/98d670df-df05-43aa-a325-c176e9a12ed5)

I think I know what's going on here, hopefully it should be easy to fix.

**Comment by d0sboots** [comment]
I'm (seriously) so happy you uploaded this, as it's proving to be a great stress test of our savegame upgrade routines, which seem to have not been exercised as well as they should have. 😄

**Comment by d0sboots** [comment]
Alright, I've made a few fixes and it loads in my dev client now. Let me polish this up and see if we can get it included in the release.
