### ISSUE TITLE
ns.fileExists is now case sensitive for all files (NUKE.exe, FTPCrack.exe, etc)

### ISSUE THREAD

**Issue by RayceBannon** [bitburner-official/bitburner-src#533]
BitBurner 2.3.0

ns.FileExists(nuke.exe) and similar now returns false. Need to update to ns.FileExists(NUKE.exe) to get the same effect.

Suggest updating the function xml to reflect this change.

**Comment by Snarling** [comment]
Reverted by 8bf13b6, program names in fileExists are now case insensitive again
