### ISSUE TITLE
Killing a script with multiple copies running causes UI bug

### ISSUE THREAD

**Issue by kylebenji** [bitburner-official/bitburner-src#534]
-v 2.3.0
It seems that if you have two copies of the same script running and you kill one using the trash can kill button on the active scripts page, the script will properly be killed, but will not be removed from the UI. It will instead freeze and become unresponsive, although sometimes can cause the other copies of the script to open or close if you attempt to expand or minimize the dropdown.

**Comment by d0sboots** [comment]
Is this two copies with the same arguments (I.e. taking advantage of the new "script arguments don't have to be unique" feature), or in other circumstances too?

I want to be sure I can repro it properly.

**Comment by kylebenji** [comment]
I went to double check and I couldn't make it happen again with the same scripts that were causing the issue before. I'll reopen if I figure out exactly how to reproduce, I don't want you chasing down ghosts. Thanks for the quick response
