### ISSUE TITLE
Problem with Find All Valid Math Expressions

### ISSUE THREAD

**Issue by jowler1** [bitburner-official/bitburner-src#535]
It seems like v2.3.0 may have introduced an error in the Find All Valid Math Expressions coding contract.
When given the problem:  "5105", 92
My answer is: []  (empty array)
I've tried several ways of returning an empty response with scripts and manually, but nothing seems to work.
Same thing with: "9987", 68

 Bitburner v2.3.0 (ef8b153c8)

-jowler

**Comment by Snarling** [comment]
I have heard that passing `null` is required here, I am not sure why. But yes definitely a bug.

**Comment by jowler1** [comment]
Thanks, I'll try that.

**Comment by Snarling** [comment]
Fixed by ae8f26f
