### ISSUE TITLE
Error calculating ram usage for script using Corporation API.

### ISSUE THREAD

**Issue by codernator** [bitburner-official/bitburner-src#550]
# Minimal scripts to reproduce the issue
I haven't been able to work out the minimal script. When I try, the error goes away.  This suggests a potential syntax or semantic error in my script, but I'm not seeing that either.

Save file is attached.

# Steps to reproduce
[bitburnerSave_1685411333_BN5x2.zip](https://github.com/bitburner-official/bitburner-src/files/11594994/bitburnerSave_1685411333_BN5x2.zip)

From the attached save file, in terminal 
[home ~]: `run corpo/corposvc.js`
or
[home ~]: `mem corpo/corposvc.js`

note that corpo/corposvc.js shares common components with corpo/create.js

# Version
2.3.0 (43a3515e0)

**Comment by codernator** [comment]
I just encountered the same issue using the Gangs API, and it seems to be related to imports that are used by multiple scripts rather than a particular API, though again I can't reliably reproduce with minimal code.

**Comment by Snarling** [comment]
Your error is a syntax error in your own code. If you open the file in nano ingame, you can see "Syntax error" at the bottom as the ram calculation. The game cannot calculate the ram cost of files with syntax errors.

Digging further, it is a syntax error in corpo/lib/divisions.js (temporarily removing that import removes the syntax error). The error is on line 77 where you redefine a constant `warehouse` that is already defined in the same scope as one of the parameters for the function `checkWarehouse`.

**Comment by codernator** [comment]
Wow, I've never noticed that "RAM: Syntax Error" box before!  I apologize for opening a dumb ticket, but I'm glad to learn something new about the interface.  Thank you!

Not to split hairs, but I do believe this is a semantic error, not a syntax error, which is why it wasn't caught by the Nano editor.  Well spotted, though.

**Comment by Snarling** [comment]
According to the browser, this is a SyntaxError:
![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/46b15550-8e82-40f7-b672-05af150ac201)

At some point hopefully we will be able to improve the error detection for Import / syntax errors so it'll tell you specifically what the error is. Unfortunately right now to troubleshoot you basically need to temporarily delete sections of code to see what causes the error to clear, and just dial it in from there (that's how I managed to find the double declaration error).
