### ISSUE TITLE
Script tail windows don't work very well in Bitburner v2.3.0.

### ISSUE THREAD

**Issue by aalku** [bitburner-official/bitburner-src#552]
- Step 1. I have a script that calls ns.tail() and then whatever.
- Step 2. I run the script and the tail window pops up.
- Step 3. I kill the script and the tail window reflects it.
- Step 4. I launch the script again from the terminal.

After that the tail window still considers the script stopped but a new tail window does not open.
If I check the running scripts it's running but it didn't reuse the tail window nor opened a new one.

You can use this script to test it.

```
-- test.js --

/** @param {NS} ns */
export async function main(ns) {
	ns.tail();
	while (true) {
		ns.print("ZZzzz....");
		await ns.sleep(1000);
	}
}
```

You can do:

- run test.js
- kill test.js
- run test.js

And you will see.

**Comment by aalku** [comment]
I tried to call ns.closeTail() before ns.tail() but it doens't close the old window either that way nor reuses it nor opens a new one. I could close it `atExit` but I don't want to. I want to reuse my tail window as I did before.

**Comment by d0sboots** [comment]
I'm 95% sure this is already fixed in 2.3.1 (dev version), but the fix wasn't in time for 2.3.0.

**Comment by d0sboots** [comment]
Oh, one thing to note: Because you can launch multiple copies of a script with the same args, the fixed version still won't act exactly the same. The code you have will cause new tail windows to accumulate; there is no way to "reuse" the existing window (short of pressing the rerun button in the tail window itself).

**Comment by aalku** [comment]
Thanks. Sounds good.
