### ISSUE TITLE
Script editor tabs don't look good with many scripts open

### ISSUE THREAD

**Issue by codernator** [bitburner-official/bitburner-src#554]
When opening 7 or more tabs in Nano, the last tab will be cut off, such that the functions (refresh and close) are obscured or hidden. How much a tab is cut off seems to depend on file name length.

# Steps to reproduce
1) Open 6 scripts in Nano.  The tabs will look good.
2) Open a 7th script in Nano. The tabs will be resized and the text adjusted. The last tab will cut off.

While I have regularly observed this, I'm not entirely sure if it always the 7th tab that breaks. Of particular note, I had the window in Maximized Window mode (using Windows 11) with a 2560x1440 resolution, so there was plenty of room for more tabs. I've also observed it on my 1080p monitor with Maximized Window mode.  If the window is not maximized, then any tab could be cut off depending on the size of the window.

# Version
Bitburner v2.3.0 (43a3515ed) - and at least a few versions before.
on Windows 11 and Windows 10, if that is relevant.

**Comment by bezrodnov** [comment]
One of the approaches could be to remove the max width calculation for script tabs (total tab container width divided by tab count) and use an invisible horizontal scroll (which is already there but not used xD). If this approach was used we could then add some scroll left/right buttons when needed in the beginning and end of the tab container (fixed or even on hover).

Also, mouse wheel support could be added, but as per my experience it's not that easy - that's only possible to achieve with JS and different browsers count wheel ticks differently. However, it seems to work fine in VS Code which is an electron app as well.
So maybe repeating VS Code approach would be the best solution here unless keeping chrome-like shortened-when-necessary tabs is a desired behavior.
wdyt?

**Comment by bezrodnov** [comment]
One of the scroll approaches could be to place an active tab in the middle of the screen - refer to an example here (right above the States section): https://m2.material.io/components/tabs#scrollable-tabs

https://kstatic.googleusercontent.com/files/b5c47dfc7ed04a063dc68b1c9f6e4ffb8136ba62e0f1495cdeff833a69f0d07a446ec883079d167735d0f1743da0f9b8aa57da919415a9807a28a1dc252c72ff

VS Code approach is just to make sure that whichever tab is clicked/activated is fully visible on the screen... but the next tab is not, so without scrolling or closing previous tabs you can't really view the next ones

**Comment by bezrodnov** [comment]
a bit more complex solution would be to support both current behavior and the one with scrolling and let user decide which one they like more (via game settings)
it's also not clear how important this ticket as there's no statistics on how often people open many script tabs in the editor.
