### ISSUE TITLE
Getting Quality: NaN for corporation produced material

### ISSUE THREAD

**Issue by Gorfiend** [bitburner-official/bitburner-src#559]
Running latest steam version (79bd057aa)

This has happened several times, and causes various issues, most notably causing a sell amount of "MAX" to fail and constantly pop up an error. Reloading will reset the quality to 0, but it will often happen again.

I think it happens for produced materials when storage is max, though seems inconsistent. Happens even with no scripts running.

It happens consistently to me in this save:
[bitburnerSave_1685671477_BN3x1_NaN2.zip](https://github.com/bitburner-official/bitburner-src/files/11631245/bitburnerSave_1685671477_BN3x1_NaN2.zip)

Simply load it, and go to Corporation/robo/Aevum, and after several seconds Robots quality will become NaN.

**Comment by Snarling** [comment]
Should be fixed by #578
