### ISSUE TITLE
"Use same 'Sell Amount' for all cities" toggle for products not working anymore

### ISSUE THREAD

**Issue by JeremyJass** [bitburner-official/bitburner-src#561]
Bitburner v2.3.0 (79bd057aa) on Steam

To Reproduce:
- In the corporation tab, create a Software division
- Develop at least one product by selecting "Develop Software", investing 0
- Expand to all 6 cities
- When setting the Sell price for a product, selecting the "Use same 'Sell Amount' for all cities" toggle no longer causes the new quantity and price to apply to the other cities

This did work correctly up until quite recently. I believe it started with the update that added "Intern" employee type (not implying it's related, just happened at the same time).

**Comment by d0sboots** [comment]
Thanks for the specific repro steps. I've seen people reporting this one on Discord too.

**Comment by JeremyJass** [comment]
No problem, love the game!

Potentially related, I just also noticed that setting the sell quantity to '0' is functioning the same as 'MAX'. This is true for both materials and products.

**Comment by d0sboots** [comment]
That's a legacy thing that we should probably think about removing.
