### ISSUE TITLE
isRunning, getRunningScript, and 2.3.0: add getRunningScripts?

### ISSUE THREAD

**Issue by svgPhoenix** [bitburner-official/bitburner-src#572]
The docs for these functions explain that it's possible for multiple instances of the same script with the same args to be running simultaneously, but there is no way to check if there are in fact more than one instance running with the same args. 

I think it would be useful to have a new function called getRunningScripts that returns an array of PIDs for every instance of a script.

**Comment by d0sboots** [comment]
You can use `ps` to find if there are multiple running.
