### ISSUE TITLE
Broken link in doc/source/gamefrozen.rst

### ISSUE THREAD

**Issue by Tafkae** [bitburner-official/bitburner-src#577]
https://github.com/bitburner-official/bitburner-src/blob/dev/doc/source/gamefrozen.rst

In the "Game Frozen or Stuck?" documentation, the link to launch Bitburner with no scripts is for https://bitburner-official.github.io/bitburner/?noScripts, which leads to a 404 page.

**Comment by amuck-gorilla** [comment]
Fixed in #593
