### ISSUE TITLE
Allow Recursive Functions

### ISSUE THREAD

**Issue by RuboGubo** [bitburner-official/bitburner-src#589]
When you create (and use) a recursive function, the game fails to evaluate the ram usage of a script.

### The function
```js
async function recursive_scan(ns, servers) {
  let found_servers = []
  servers.forEach(function(current_server) {
    if (
      ns.getServerNumPortsRequired(current_server) < 2
    ) {
      found_servers.push(current_server)
      found_servers = found_servers.concat(await recursive_scan(ns, ns.scan(current_server)))
    }
  })
  console.log(found_servers)
  return found_servers
}
```

### Main Function
Edited for brevity
```js
export async function main(ns) {
  const SERVERS = ["home"]

  servers += await recursive_scan(ns, SERVERS)
}
```
### Game Version
v2.3.1 - Steam

**Comment by ABruel** [comment]
Recursion is working fine for me, same game version.

The function you provided seems like it will never halt.

You start with `['home']`. You scan home. Scan will return `n00dles`, next call will have `['n00dles']`. You scan `n00dles`. Scan will return `home`. Next call will have `['home']`...

**Comment by ABruel** [comment]
Now, it seems like what you want to do is get all servers with `getServerNumPortsRequired < 2`. I'd advise you to perform this operation after getting the complete list of servers, in order to make the recurse function easier to understand.

```javascript
/** @param {NS} ns */
export async function main(ns) {
  const r = sc(ns, new Set(), ns.getHostname());

  const weakServers = [...r].filter(e => ns.getServerNumPortsRequired(e) < 2);
  ns.tprint("weakServers: ", JSON.stringify(weakServers));
}
/** @param {NS} ns 
 * @param {Set<string>} servers
 * @param {string} current
*/
const sc = (ns, servers, current) => {
  servers.add(current);
  ns.scan(current).filter((e) => !servers.has(e)).forEach(e => {
    sc(ns, servers, e);
  });
  return servers;
}
```

**Comment by RuboGubo** [comment]
Yeah you are right,
Thanks so much

Am Sa, 10. Jun 2023 um 14:19:51 -0700 schrieb Arthur Bruel 
***@***.***>:
