### ISSUE TITLE
"exec: Ram usage could not be calculated for script"

### ISSUE THREAD

**Issue by amuck-gorilla** [bitburner-official/bitburner-src#590]
# Details of bug

When trying to use `exec()` to run a specific file,  I get the message, `exec: Ram usage could not be calculated for constant-hack.js`.

## constant-hack.js

```javascript
/** @param {NS} ns */
import {getHackTarget} from "get-hack-target.js";
import {nukeServer} from "/utilities/nuke-server.js";

export async function main(ns) {
	const port = ns.getPortHandle(1)
    // Defines the "target server", which is the server
    // that we're going to hack.
    let target;
    if (!port.empty) {target = port.peek();}
    else {target = await getHackTarget(ns);}

		ns.tprint(target);

    // Get root access to target server
    if (!ns.getServer(target).hasAdminRights) {
        if (!nukeServer(target)) {
            ns.tprint("Error: " + hostname + " targeted but could not be nuked");
            ns.toast("Error: " + hostname + " targeted but could not be nuked", "error", 5000);
        }
    }

    // Infinite loop that continously hacks/grows/weakens the target server
    while(true) {
        if (!port.empty) {target = port.peek();}

        if (ns.getServerSecurityLevel(target) > ns.getServerMinSecurityLevel(target) + 5) {
            // If the server's security level is above our threshold, weaken it
            await ns.weaken(target);
        } else if (ns.getServerMoneyAvailable(target) < ns.getServerMaxMoney(target) * 0.75) {
            // If the server's money is less than our threshold, grow it
            await ns.grow(target);
        } else {
            // Otherwise, hack it
            await ns.hack(target);
        }
    }
}
```

I've attached the imports, as well as `arsenal.js`, the file that I'm trying to run that is executing `constant-hack.js`.

## To reproduce

1. Connect to `home`
2. In the Terminal, run `run arsenal.js`
3. Go to Active Scripts
4. Open `home`
5. Open the log for `arsenal.js []`

### Game details
I'm playing on Bitburner v2.3.1 (100030008). I've attached my save file.

### Zip of all attachments

[attachments.zip](https://github.com/bitburner-official/bitburner-src/files/11712911/attachments.zip)

Sorry that they're all together. Github won't allow attaching `.js` or `.json`.

**Comment by Snarling** [comment]
You're copying constant-hack to the target servers, but you are not copying the imports that it requires. constant-hack running from n00dles needs those same imports to exist on n00dles.

**Comment by amuck-gorilla** [comment]
> You're copying constant-hack to the target servers, but you are not copying the imports that it requires. constant-hack running from n00dles needs those same imports to exist on n00dles.

Oh. Thanks.
