### ISSUE TITLE
Add formulas function to calculate grow threads given a max money and user inputted starting money.

### ISSUE THREAD

**Issue by J-Aric** [bitburner-official/bitburner-src#594]
It would be good to add a formulas function to be able to calculate the number of grow threads needed to grow a server from a given current money to the given current max. 
The current growThreads function pulls server.moneyAvailable, which makes doing predictive threading difficult when staggering grows and hacks.

**Comment by d0sboots** [comment]
This is what `growThreads` exists for. Set `moneyAvailable` to whatever you want before calling it.
