### ISSUE TITLE
Corporation Market TA.II doesn't work

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#595]
Steam, last version.

When set the market TA.II for the product it is producing zero/sec.
After removing check for TA.II it starts to produce/sell the product.

We all know that the path to hell is paved with good intentions, 
but please, next time test your code (a little more) BEFORE put it in production :)

I'm a fan of corporations and the last update was terrible about corporations...

[bitburnerSave_1686484301_BN7x2.json.log](https://github.com/bitburner-official/bitburner-src/files/11714521/bitburnerSave_1686484301_BN7x2.json.log)

BTW, I'm willing to participate in beta testing pre-releases.

**Comment by Snarling** [comment]
Your lack of production in some cities does not seem to have anything to do with Market TA 2. You're not producing in some cities because your warehouses are filling up.

Is there any division/city you can point me to where you believe the issue is something other than your warehouse size?

**Comment by AssenD** [comment]
Hmm, I saw that too, but it was strange:
when I deactivated the TA.II - production/sell started again - with the same warehouse storage??
So, yes, the issue is connected to storage space, but it happens only when TA.II is activated.
Frankly, I'm confused...

But I really want to help :)

**Comment by Snarling** [comment]
https://github.com/bitburner-official/bitburner-src/assets/84951833/251f6573-5f51-47f7-bdef-abcf047db4cd

Not what I'm seeing. Let me know if there's a different division/city where disabling market TA affects your production negatively. I'm pretty sure you're just looking at the sell price.

**Comment by AssenD** [comment]
Ha-ha, sometimes I feel really stupid! 

But showing price when nothing is produced/sell seems as a (little) bug, or at least it's confusing.
And sell price is only showed when deactivating TA.II.

Thank you for all your efforts and sorry for wasting your time!

(you can close this misunderstanding)
