### ISSUE TITLE
Allow unknown flags when parsing with `ns.flags`

### ISSUE THREAD

**Issue by ABruel** [bitburner-official/bitburner-src#597]
I have a script that runs a given script on a given list of servers or all servers.

After doing some processing to decide what args to pass to the script, it eventually runs it with:

```javascript
ns.exec(
  script,
  server,
  threads,
  ...[...args, "--host", server, "--threads", threads.toString()]
);
```

The problem is that when `script` doesn't include `host` and `threads` in it's call to `ns.flags`, `ns.flags` throws an exception due to being fed an unknown flag. So now I have to include these two flags on every script, even when not needed.

This feature is already [supported](https://github.com/vercel/arg#permissive) by the parsing library used.

**Comment by G4mingJon4s** [comment]
Can you share the flags you use and give a bit more context?
If I understand correctly, you have some flags set up and now you need to pass them to every script you call?

**Comment by ABruel** [comment]
- I have script `A`
- Script `A` receives script `B` and `TARGET`
- Script `A` calculates the maximum amount of threads of `B` that can be run on `TARGET`
- Script `A` runs script `B` on `TARGET` passing in `--host TARGET` and `--threads THREADS`.

It does a bit more than that, but that's the gist of what's causing me problems.

Here's a simplified version of `A`, with hard coded script and targets:

```javascript
const servers = ["n00dles", "foodnstuff", "sigma-cosmetics", "joesguns"];

const script = "hack-analysis.js";

export async function main(ns) {
  servers.forEach((server) => {
    const scriptRam = ns.getScriptRam(script);
    if (!scriptRam) {
      return;
    }
    
    const threads = Math.floor(
      (ns.getServerMaxRam(server) - ns.getServerUsedRam(server)) / scriptRam
    );
    
    if (threads < 1) {
      return;
    }

    ns.exec(
      script,
      server,
      threads,
      ...["--host", server, "--threads", threads.toString()]
    );
  });
}
```

My problem is that script B (in the above example, `hack-analysis.js`) **needs** to include `['host', ''], ['threads', 1]` in it's call to `ns.flags`, when something like `threads` makes no sense for this particular script.

**Comment by G4mingJon4s** [comment]
Okay, can you also provide the script B, just the part with the flags is enough.

**Comment by G4mingJon4s** [comment]
Okay, I think I understand what you are asking.

You have some script that just launches scripts with these two flags. Now, in your case, the called script does not include the passed flags in its set flags.

Well, flags are not really meant to be used in that way. Flags are meant to allow the player to override defaults for a given script.

One could argue if unknown flags should be allowed. I myself think unknown flags should be an error, as you probably did something wrong if you have some. (like typos or in your case passing too many flags)

**Comment by ABruel** [comment]
```javascript
export async function main(ns) {
  const flags = ns.flags([
    ["help", ""],
    ["host", ""],
  ]);
}
```

This results in a runtime error.
![image](https://github.com/bitburner-official/bitburner-src/assets/30672118/ff8dd565-ddc6-4912-81ad-59c9c61a2ef5)

**Comment by d0sboots** [comment]
So I feel like the better question is: `A` is *explicitly* designed to calculate the threads for `B`. So why would you try to use it with something that doesn't use threads?

**Comment by ABruel** [comment]
@d0sboots it's designed to run the max amount of a script on a given list of servers and also do some argument processing. 

I don't really mind if it runs 10 threads when the script would be fine with 1, I just don't want it to run 1 thread when the script would be better with 10.

Say I want the current player cash. Just run `run run-on-servers --script a.js --server ALL -- --pMoney PLAYER.money` Or maybe the server security `--sSec HOST.hackDificulty`. That way I can get a script that has access to quite literally any information it wants without increasing the RAM usage.

I've removed most of the unnecessary fat from the script posted here since it isn't required to reproduce the problem at hand.

Anyway, I've implemented it myself and put it into an util function. The entirety of the arg lib is under 200 lines. I have more code than that on my logger😆

**Comment by d0sboots** [comment]
My solution to this is eval.js:
```js
/** @param {NS} ns */
export async function main(ns) {
  // Bloat RAM size by 2.5GB so we can eval some ns functions.
  ns.buyStock;
  ns.tprint(eval(ns.args[0]));
}
```
Then your example of "find player money" is `run eval.js 'ns.getServerMoneyAvailable("home")'`. Printing info about a server is generally `run eval.js 'ns.getServer("home")'`.

This is not to say this is the best, or only way of doing things. Just that you can certainly accomplish this without complicated args parsing.

**Comment by ABruel** [comment]
@d0sboots I know, that's what I'm doing. Without having to find functions that are reference but not used and have the same RAM requirements of every function I would want to use. And also having access to information only available to the script, like the current host being targeted.

```js
/** @param {NS} ns */
export async function main(ns) {
  ['n00dles', 'joesguns', 'foodnstuff'].forEach(e => {
    const HOST = ns.getServer(e)
    ns.tprint(eval(ns.args[0]));
  })
}
```

`$ run eval.js "HOST.moneyMax"`

**Comment by ABruel** [comment]
As for the "parsing".

```js
args
  .skipWhile(e => e !== '--')
  .skip(1)
  .map(e => e.startsWith('-') ? e : eval(e));
```

**Comment by d0sboots** [comment]
My point was that there's no need to set up HOST at all. You can just specify it directly as part of the command to be evaluated, and then there's no need for parsing. Again, just a different way of doing things.

My script would do your example as `run eval.js "['n00dles', 'joesguns', 'foodnstuff'].map(x=>ns.getServer(x).moneyMax)"`

**Comment by ABruel** [comment]
Well, ignoring the fact you basically wrote an entire script as an argument to avoid having to declare a variable, that sill wouldn't execute the script on the server. you'd basically have to at least do:

`run eval.js "['n00dles', 'joesguns', 'foodnstuff'].map(x => { const sMoney = ns.getServer(x).moneyMax; ns.exec(script, threads, '--host', x, sMoney)})"`

And you'd still need threads and script in your eval, unless you create yet another variable inside this eval argument. Which would be basically writing an entire script as an argument to avoid having to declare some variables before the eval.

The code posted here is the totality of this "parsing" you want to avoid. Apart from this, the only other thing required for this to work is the declaration of a couple of variables that can be accessed by the eval, ie `const HOST = ns.getServer(server); const PLAYER = ns.getPlayer();`

https://github.com/bitburner-official/bitburner-src/issues/597#issuecomment-1587200940

It really seems like you're arguing that it's preferable to use entire scripts as arguments an use eval on those scripts with only `ns` as a global variable (plus the weird juggling to avoid the dynamic RAM calculations), than use simple property accesses as arguments with some 5 fixed global variables. And honestly I really can't see how that is preferable.

**Comment by d0sboots** [comment]
I think we're talking about entirely different things.

> Say I want the current player cash. Just run `run run-on-servers --script a.js --server ALL -- --pMoney PLAYER.money` Or maybe the server security `--sSec HOST.hackDificulty`.

From this, I assumed you just wanted to get the player's cash, or the current security on a host. These are easy tasks to do that don't need the specific infrastructure you've made.

But from the later conversion, I think what you are actually describing is what we call "RAM dodging": using a throwaway script to absorb the cost of certain `ns` functions, so your main script doesn't need to.

Your arg-parsing version of this is limited by the fact that it can only do this once, at script startup. For instance, if you get the player's money this way, money will change, and now you have to get the new value somehow. If you do the direct call, you've negated the purpose of your infra.

All of this would be easier to discuss in real-time, instead of in a bug thread XD
