### ISSUE TITLE
Multithreading description not mentioning .share

### ISSUE THREAD

**Issue by Noxebo** [bitburner-official/bitburner-src#606]
[link](https://bitburner-official.readthedocs.io/en/latest/basicgameplay/scripts.html#multithreading-scripts)
The current explanation of multithread makes you assume .hack .grow and .weaken are the only scripts you can multithread.
It fails to mention the possibility of others like .share. and possibly others I have not found yet.

**Comment by Noxebo** [comment]
Wanted to Label this as Documentation but i am still figuring out github...

**Comment by Snarling** [comment]
You probably don't have access to put labels on issues, I tagged it for you

**Comment by Snarling** [comment]
Fixed by #734
