### ISSUE TITLE
Editor gives import error when connected to other server

### ISSUE THREAD

**Issue by Noxebo** [bitburner-official/bitburner-src#611]
If this is actually intended behavior because it makes sense to look for files on another server if you are connected to different one...
The error given needs a little more clarity because it took a shamefully long time to figure this one out.

function.js
```
/** @param {NS} ns */
export function importFunction(ns) {
  ns.Print("I got imported");
}
export default importFunction;
```

script.js
```
import importFunction from "function.js"
/** @param {NS} ns */
export async function main(ns) {
  importFunction();
}
```

Steps to reproduce
- Open script.js in editor
- Goto Terminal
- Connect to other server
- Go back to editor

- Bitburner v2.3.1 (100030008)

**Comment by Snarling** [comment]
Fixed by #612
