### ISSUE TITLE
Need more cache levels

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#617]
I would like to have more cache levels for hacknet servers.

The only argument I have is that the speed of spending hashes is dangerously close to the game tick speed, imho.

As you can see in the picture, I'm on about 14 per second at the moment => 71.4 millis for execute ns.hacknet.spendHashes().

![2023-06-16 12_42_35-Bitburner v2 3 1 (100030008)_Cache_level](https://github.com/bitburner-official/bitburner-src/assets/20597249/39386a98-9e23-47da-8b37-4674f6ffc1f3)

**Comment by d0sboots** [comment]
Have you tried having less hash? XD

I don't think maxing all the hashnet servers is something you're expected to do, aside from going for the achievement. You've reached node-breaking money *and* hash so very far before that point...

**Comment by AssenD** [comment]
I'm after intelligence and this was side effect :)

I'm testing a new (for me) algorithm for farming intelligence by Bladeburner, so far without success...
But the numbers got really big for several days.

![2023-06-16 16_40_00-Bitburner v2 3 1 (100030008)_BB](https://github.com/bitburner-official/bitburner-src/assets/20597249/92d14d9b-fbe7-4b83-be6c-9d3ad36659d8)

I don't need those hashes, the Corporation, as resource for money, is enough. 
But maybe this part of the game needs rebalancing a little?

**Comment by d0sboots** [comment]
What seems imbalanced?

Numbers going to huge is just part of the game. It's only unbalanced if you can get that particularly quickly, or with particularly low effort, or if something breaks in a fundamental way.

**Comment by AssenD** [comment]
> What seems imbalanced?

What I mean is that if I want to buy something that cost 25m hashes, I cannot, even if production is more than 500m h/s:

![2023-06-17 21_31_09-Bitburner v2 3 1 (100030008)_4](https://github.com/bitburner-official/bitburner-src/assets/20597249/5a03c8f3-eb90-45d1-b71a-c2d86f80c4f8)

**Comment by d0sboots** [comment]
But what costs that much? You are definitely able to afford all the upgrades to all hashnet servers. I think that's well beyond the hash needed to upgrade *every* server to minimum security/maximum money, as well.

**Comment by AssenD** [comment]
If you feel offended, don't be :)
I really can and highly appreciate your work.

I'm just a curious tomcat that will try to play with everything in reach - to the limit or until broke it. 
And this seems to me as a constraint that shouldn't be there.

**Comment by d0sboots** [comment]
Dw I'm not upset at all. :) Just trying to dig down to if there's an actual gameplay issue here, or if it's just a case of "things get funny when you max everything out." Since it seems like the latter, I'm not particularly concerned.

(For reference, there are some ways to break things that cause actual infinite money, and that leads to other issues. It's also pretty low priority, because it takes literal months to do.)

**Comment by Caldwell-74** [comment]
i dont understand the timing stuff you mean
you have 200ms to spend the 20m hashes
because every 200ms you gain hashes and everything above the cap is automatically turned into cash

**Comment by hydroflame** [comment]
Nobody fix this but don't close it either. I have a student that I want to give this task to.

**Comment by catloversg** [comment]
@d0sboots I think we can close this. Max cache is only "small" when the player has a ridiculous amount of money from Corporation or deep BN12's multipliers. There is no reason to balance a feature around these use cases.
