### ISSUE TITLE
singularity.donateToFaction is cheaper than manual donating

### ISSUE THREAD

**Issue by lossycrypt** [bitburner-official/bitburner-src#618]
Version 2.3.1 (Github release, non-steam zip, firefox)

I tried to figure out how much money it costs to gain a fixed amount of reputation. I'm currently in BN4x1 Singularity Level 1 (my first non-starter bitnode). I tried two approaches: Calculating from known constants, and calculating from a real donation.

`test.js`
```
const NODEGAIN = {4:0.75}
function calcDonationForRep(ns,rep){
  const p    = ns.getPlayer()
  const div  = 1e6 //DonateMoneyToRepDivisor (hardcoded)
  const mult = p.mults.faction_rep // 3.62285413582752 (All Normal Augs, No special faction, NeuroFlux L83)
  const gain = NODEGAIN[p.bitNodeN] //BitNodeMultipliers.FactionWorkRepGain
  ns.tprint('calcDonationForRep: ', (div) / (mult * gain))
  return (rep * div) / (mult * gain)
}

//how much does 1 rep cost?
function getRepCostFactor(ns, rep, faction = 'BitRunners'){
  const amount = 1e3
  const rep1 = ns.singularity.getFactionRep(faction)
  ns.singularity.donateToFaction(faction, amount)
  const rep2 = ns.singularity.getFactionRep(faction)
  const costPerRep = amount/(rep2-rep1)
  ns.tprint('getRepCostFactor: ', costPerRep)
  return costPerRep * rep
}

export async function main(ns) {
  try {
    ns.tprint(calcDonationForRep(ns,eval(ns.args[0])))
    ns.tprint(getRepCostFactor(ns,eval(ns.args[0])))
  } catch (err) {
    ns.tprint(err)
  }
}
```

However the terminal output gave weirdly different output, which i at first thought was a bug in my code.
`[home /]> run test.js 1e6`
```
test.js: calcDonationForRep: 368033.95426484034
test.js: 368033954264.8404
test.js: getRepCostFactor: 276025.3243434725
test.js: 276025324343.4725
```

However i noticed that the numbers are **both correct**! When i manually donate `368033954264.8404` to i.e. BitRunners i gain exactly 1.000m reputation, however if i automatically donate 
`ns.singularity.donateToFaction('BitRunners', 276025324343.4725)` 
i also gain exactly 1.000m reputation! The difference is exactly `0.75` which I believe is the `BitNodeMultipliers.FactionWorkRepGain` for Singularity Level 1 (I don't have API access to BitNodeMultipliers yet)

**Comment by bezrodnov** [comment]
for singularity rep is calculated as follows:
```ts
const repGain = (amt / CONSTANTS.DonateMoneyToRepDivisor) * Player.mults.faction_rep;
```
for UI/manual:
```ts
const repGain = (amt / CONSTANTS.DonateMoneyToRepDivisor) * person.mults.faction_rep * BitNodeMultipliers.FactionWorkRepGain
```

working on the fix
