### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#620]
Got this error:

`RUNTIME ERROR
corp-all.js@home (PID - 3)

Invalid product name: 'REST-1686948772336-21.884e96-2.188398337409068e+97'
stack:
Error: Invalid product name: 'REST-1686948772336-21.884e96-2.188398337409068e+97'
    at x (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:946738)
    at file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:949922
    at Proxy.l (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:867524)
    at sellNewProduct (home/corp-all.js:166:8)
    at Module.main (home/corp-all.js:301:6)
    at async N (file:///D:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1033032)`

But the product name seems OK as seen in the picture:

![2023-06-17 00_05_19-Netflix_ERROR](https://github.com/bitburner-official/bitburner-src/assets/20597249/5657daf3-c407-4837-bb01-3bcea092b1d1)

..and the "strange" part:
 I am using greenshot for taking pictures of the screen and usually it gives names like `2023-06-15 16_04_32-Bitburner v2.3.1 (100030008).png`,
but this time the name was `2023-06-17 00_05_19-Netflix.png`

How is Netflix involved is a mistery :)

**Comment by Snarling** [comment]
This is the internal code that generates that error:
![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/5371685f-196e-4401-857b-bb44c4904a46)

Are you certain that you were looking at the correct division? e.g. if you are referencing a different division, then `division.products.get(productName)` will be undefined, leading to the error.

**Comment by AssenD** [comment]
> Are you certain that you were looking at the correct division? e.g. if you are referencing a different division, then `division.products.get(productName)` will be undefined, leading to the error.

Thank you!
The division name was correct, but found other problem in my code - a variable (productName) wasn't reseted properly...
