### ISSUE TITLE
Error with ns.corporation.hireEmployee

### ISSUE THREAD

**Issue by bobingabout** [bitburner-official/bitburner-src#623]
using ```while (c.hireEmployee(division, city)) { }``` to hire employees is standard code I've been using for a while. The intention is to hire employees into the unassigned position.

A new variable was added to hireEmployee, position. Tooltip says it's optional, and if not specified, defaults to the unassigned position.

Omitting it causes an error.
![image](https://github.com/bitburner-official/bitburner-src/assets/13473775/25d36d2b-5e16-4d29-9ef0-93a4c8f4e7e9)

**Comment by Snarling** [comment]
Sorry for the late fix, fixed by 61a27fb
