### ISSUE TITLE
Integrate documentation into the game

### ISSUE THREAD

**Issue by Hoekstraa** [bitburner-official/bitburner-src#624]
hydroflame on Discord, today:
Would be cool to add a markdown renderer in a new tab under Help and move most of readthedoc in-game. 

It might complicate the build of the game somewhat, but it could have a few benefits (_**all depending on implementation!**_):
- Documentation would be linked to the version, and so accurate to that version.
- Documentation would be available to players without internet access

Downsides:
- In-game documentation can't be changed without publishing a new version of the game

**Comment by lossycrypt** [comment]
I too would love this as I play offline alot and think it would fit the theme! When I first started I was infact a bit suprised/disappointed that I couldn't really play the game without first googling the basics out-of-game.

I've tried to use wget/httrack to get it working offline with mediocre success. The "basic" (readthedocs) doc I got working with wget (the built in zip-download has a bug where you can't click the chapter text to expand to subchapters). But basic doc has no info aboutextra apis (singularity, etc). I got the github markdown pages working with `wget --mirror --page-requisites --convert-links` but they do not render correctly no matter what I try (looks like the css doesn't load).

**Comment by Hoekstraa** [comment]
ReadTheDocs documentation has been integrated in #667, so closing this one.
Secondly, I opened #707 for specifically integrating API docs.
