### ISSUE TITLE
Change alias to not substitute the same alias recursively

### ISSUE THREAD

**Issue by Hoekstraa** [bitburner-official/bitburner-src#630]
As of now (dev build included), `alias` doesn't behave like POSIX spec says.
It naively repeats substitution 10 times if a recursive loop is found.
POSIX spec however mentions:
> To prevent infinite loops in recursive aliasing, if the shell is not currently processing an alias of the same name, the word shall be replaced by the value of the alias; otherwise, it shall not be replaced.

[source](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03_01)

The current implementation can create a situation like the following (thank you, Noxebo on Discord):

![image](https://github.com/bitburner-official/bitburner-src/assets/19653491/5ef43890-4a88-4803-ad61-e0c886bc09d6)

How to resolve:
keep track of the last used alias, and if the same alias is used again directly after, don't substitute.

**Comment by Snarling** [comment]
This was partially addressed by #635 but we may want to do more of a rewrite to provide full recursion-detection (instead of just checking the most recent alias substitution)
