### ISSUE TITLE
Duplicate augmentations

### ISSUE THREAD

**Issue by Tinox79** [bitburner-official/bitburner-src#633]
Each augmentation appears multiple time in each faction's augments list. This started occurring after I installed augmentations around two days ago, and has persisted through a BN destruction since.

This started occurring under v2.3.1 and has continued under v2.3.2.

Steps to reproduce:
- Load the save

![TEMP](https://github.com/bitburner-official/bitburner-src/assets/8889254/4a80c5b5-b2f9-430a-a0a8-8983b6b1b7ed)
[bitburnerSave_1687204608_BN9x3.txt](https://github.com/bitburner-official/bitburner-src/files/11792734/bitburnerSave_1687204608_BN9x3.txt)

**Comment by Snarling** [comment]
My bad there, issue was introduced in #608 and I didn't catch it. This should be fixed by aecdbe8 now
