### ISSUE TITLE
Invisable producer makes money

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#637]
I'm after -$1b achievement and not a single script running - as shown by ps command.
BUT, my money is going up instead of down, with 8 sleeves working on gym and the player too...

I had a script that spended hashes for money, but killed it long before.

I suspect that the script is still working, but it's somehow hidden and invinsible :)
[bitburnerSave_1687279002_BN1x4.json.log](https://github.com/bitburner-official/bitburner-src/files/11803567/bitburnerSave_1687279002_BN1x4.json.log)

**Comment by d0sboots** [comment]
I haven't got a chance to look at your save yet, but you can narrow it down by looking in stats at the detailed breakdown of money gain/loss by category. See where it's still gaining.

Note that if you have any hashnet servers, you'll have to deal with them: overflowing hashes are autosold.

**Comment by Snarling** [comment]
![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/905fc9b0-0cf0-4ecb-b67b-01ef943560c3)
![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/589ab0db-ff52-46bf-b204-496862ccb4f5)

The producer is visible

**Comment by Snarling** [comment]
(Hacknet servers automatically sell their hashes for money when they are full)

**Comment by AssenD** [comment]
Thanks! Didn't know.
Where in documentation is that info, if any?
