### ISSUE TITLE
Add design and advertising investment amount to getProduct return data

### ISSUE THREAD

**Issue by Snarling** [bitburner-official/bitburner-src#639]
No reason we can't provide the investment amounts to the player, and there are a few cases where a player would want to have that info. If no one adds this before then, I will probably do a quick PR to add this on 6/21 or 6/22.

Data would be added to the actual function's return:
https://github.com/bitburner-official/bitburner-src/blob/4560fb7250900afc103a419a14a9b8cc0dda592b/src/NetscriptFunctions/Corporation.ts#L322-L345

And to the ns API type definition:
https://github.com/bitburner-official/bitburner-src/blob/4560fb7250900afc103a419a14a9b8cc0dda592b/src/ScriptEditor/NetscriptDefinitions.d.ts#L7533-L7567

**Comment by AssenD** [comment]
I'm using product names to save this information, so both thumbs up!
If I may suggest - consider adding release time of the product, too, pls.

**Comment by Snarling** [comment]
> If I may suggest - consider adding release time of the product, too, pls.

Not currently stored internally, so it probably will not be added. This is different from the investment amounts, which are stored internally on the product and just not provided to the player.

Timestamps are also not provided for when you started other related mechanics (e.g. what time did I start this corp, or what time did I start division X, or what time did I expand division X into city Y, or what time did I buy a warehouse in city Y of division X, etc), so it also isn't a consistency thing that should be added. To track that kind of info (for products and for all the other stuff I just listed), you would need to track that yourself.

**Comment by AssenD** [comment]
OK, I'll continue using the name of the product (as temp storage) for timestamp.
It needs uniqueness anyway :)

**Comment by JacobsThierry** [comment]
I am the guy who asked on discord how to get these values. The reason I wanted them is so I could calculated the markup of a product : shouldn't we also have access to the markup in Product ?
