### ISSUE TITLE
Script Editor ignores Style Editor settings

### ISSUE THREAD

**Issue by SoraHjort** [bitburner-official/bitburner-src#641]
[ v2.3.1 Steam]

Title is pretty self explanatory.

The nano Script Editor doesn't follow the settings in the Style Editor. Whether it's fonts or the line height. 

I'm not too worried about the Line Height, especially since the editor is built up with a bunch of <span>. The font on the other hand is a bit more important. 

For an example, I prefer [Fira Code](https://github.com/tonsky/FiraCode) as my preferred coding font, with it's ligatures for various programming symbols, such as >= visually transforms into ≥ while maintaining monospace of both characters.

But as is, the editor ignores the font setting, and is hardcoded in the parent div's style to use `"Lucida Console", Consolas, "Courier New", monospace;`

Also a side note on the ligatures, it seems Fira Code would have issues even if I were to work, since it's ligatures are disabled by the `calt` being set to `0` in `font-feature-settings`. Which, then I would also like to request an toggle option in the style editor to enable/disable contextual alternates ligatures.

**Comment by Snarling** [comment]
The ScriptEditor has its own `options` page:

![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/a822198b-8fc8-41a8-a3de-499b0ee6c18b)

**Comment by SoraHjort** [comment]
I'll be honest, I completely didn't notice the options menu. So that's on me. 
Sorry about that.
