### ISSUE TITLE
getMoneySources().hacknet triggers flag for ram cost of ns.hacknet

### ISSUE THREAD

**Issue by Eond** [bitburner-official/bitburner-src#646]
# include (where relevant)
![BitBurnerIssueHacknetRamCost](https://github.com/bitburner-official/bitburner-src/assets/86714/50c81557-65fe-4057-97bb-96e82cd58ded)

- [ ] Save file
Not required. The issue can easily be reproduced in a new save file.

- [x] Minimal scripts to reproduce the issue
```
export async function main(ns) {
	hacknet;
}
```

- [x] Steps to reproduce

1. Launch the application.
2. Create a new script.
3. Add the line `ns.getMoneySources().hacknet` in the main function.
4. Click the "RAM" button at the bottom of the editor.
5. Notice that 4 Gb was added to the cost for using the hacknet API.

- [x] Version of the game
Bitburner v2.3.1 (100030008)

- [x] Additional notes
The RAM usage actually only needs to see the word "hacknet" by itself anywhere in the script to cause the issue, but the use illustrated in the steps is the most likely way a user might encounter this issue.

**Comment by lossycrypt** [comment]
I got hit by this when trying to store some custom data. Had to use a different key.
```
export async function main(ns) {
  const mydata = {hacknet : 0}
  mydata.hacknet++
}
```

**Comment by d0sboots** [comment]
We really should kill off the hacknet namespace costing RAM, since that also makes it trivial to bypass...
