### ISSUE TITLE
UX: Make the tutorial "continue" button have a textual description

### ISSUE THREAD

**Issue by jpaugh** [bitburner-official/bitburner-src#652]
Just downloaded the game via Steam on Windows (v2.3.1, 100030008). I can't figure out how to get to the second step of the tutorial. I can see the following message in the tutorial window, which describes how to skip the tutorial, but does not describe how to continue the tutorial.

> Welcome to Bitburner, a cyberpunk-themed incremental RPG! The game takes place in a dark, dystopian future... The year is 2077...
>
> This tutorial will show you the basics of the game. You may skip the tutorial at any time.
>
> You can also collapse this panel to temporarily hide this tutorial.

![How the tutorial screen appears on my machine](https://github.com/bitburner-official/bitburner-src/assets/1366014/d91ea51d-3978-4dd2-8690-fba5baaeeeab)

**Comment by d0sboots** [comment]
The next button is the big greater-than sign. I agree, that's not the most clear...

**Comment by jpaugh** [comment]
You mean, the terminal prompt symbol? That's really a bad idea... Anyone familiar with the command line is likely to get tripped up by that.

That's a UX bug in the tutorial, and definitely should be fixed.

**Comment by Snarling** [comment]
Would a tooltip on the iconbutton be fine, or should we just use text buttons?

**Comment by d0sboots** [comment]
Imo we should be using text here, or icon + text

Edit: Different styling could also help. The issue is that, especially on its own it doesn't look much like a button. But text would still probably be the most clear.

**Comment by myCatsName** [comment]
I mocked up a potential layout change.
- ">" no longer looks like a terminal or text prompt, but stays for style, and draws attention to prompts.
- 2 text button options relate to the dialogue
- Personally I would add tooltip, just repeating the button text, seems like an expected behavior.
- aligning the ">" icon with the prompt buttons decreases space required, potentially buttons can be larger.

**Comment by myCatsName** [comment]
Follow up on this: The Tutorial UI and UX is poor. Making any change to this one issue is overlooking how messy the entire system is. This is not even the worst part of the tutorial.

I had some design ideas for overhauling the tutorial entirely, but will at least suggest no one waste their time making small changes if they only affect this specific button.

**Comment by pjz** [comment]
Also got bitten by this!  I had to come here to learn that '>' is the 'Next' button.  Maybe make it have the same green-on-grey that the 'skip tutorial' button has?  It'd've been clear that they were both the 'same kind of thing' (eg. buttons) that way.
