### ISSUE TITLE
NS: Make resizeTail and moveTail work while the tail is closed

### ISSUE THREAD

**Issue by paulcdejean** [bitburner-official/bitburner-src#656]
2.3.1

Would be nice if you could run those functions before running tail, so that user would just see the tail window open where they want, rather than seeing it jumping around the screen.

**Comment by Snarling** [comment]
If you resize/move synchronously right after ns.tail() it should never render on your screen with the wrong location/size

**Comment by paulcdejean** [comment]
@Snarling it does 🤷‍♂️ 

```js
/** @param {NS} ns */
export async function main(ns) {
  ns.clearLog()
  // Cleans up react element after exit
  ns.atExit(() => {
    ns.clearLog()
    ns.closeTail()
  })

  ns.tail()
  ns.resizeTail(750, 500)
  ns.moveTail(350, 450)

  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition, no-constant-condition
  while(true) {
    await ns.asleep(2000)
  }
}
```

This code looks like this when I run it:
![image](https://github.com/bitburner-official/bitburner-src/assets/1987879/0d65098d-69cb-4a33-b0b5-3a245628ab77)

Then it jumps down to the bottom right, when it hits the ns.asleep. Test the code yourself and let me know if you get the same results or if something if funky with my machine.

**Comment by JDawg4DeyFo** [comment]
I ran your code, got the same results as you. Just confirming it isn't just your machine.

**Comment by svgPhoenix** [comment]
manipulating a tail without awaiting ns.sleep(20) or ns.asleep(0) after spawning it causes very unpredictable behavior. This is in the docs for moveTail() and resizeTail().

I imagine it would be easier to implement calling tail(position, size) than manipulating the tail before it exists.
