### ISSUE TITLE
Unable to assign sleeves to any faction work task

### ISSUE THREAD

**Issue by matt-chaney** [bitburner-official/bitburner-src#666]
I'm unable to assign any sleeves to any faction work task. The option is shown on the Sleeves UI, and I'm able to select any faction and task but clicking 'Set Task' doesn't seem to do anything. I'm able to assign them to any other task. This behavior started mid-bitnode: it was working and them stopped without switching nodes or creating a gang.  Trying to use setToFactionWork also does nothing, and doesn't return anything to indicate what's going on.
Not seeing anything in the debug console when attempting either method to assign them.

Version: 351a7fc5f
[Sleeve_Faction_Assignment_bitburnerSave_1688935504_BN9x2.zip](https://github.com/bitburner-official/bitburner-src/files/11996068/Sleeve_Faction_Assignment_bitburnerSave_1688935504_BN9x2.zip)

**Comment by j-zehnder** [comment]
line in debugger: `const workType = getEnumHelper("FactionWorkType").fuzzyGetMember(_workType);` is setting workType to undefined

I don't know enough about the problem to help with a fix

**Comment by Snarling** [comment]
Fixed by 993f234
