### ISSUE TITLE
ns.growthanalyzesecurity()

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#67]
[copsi1]
Hello,
i use Bitburner 1.6.4.

in NS.growthAnalyzeSecurity() method the discription of parameter "hostname": is limit to hack the maximum? in my test i think it is grow to maximum. becouse if a server lost 200k money and i test to grow with double the money, the result of growthanalyzesecurity ist very low.
sry for my bad english.

![grafik](https://user-images.githubusercontent.com/104488252/168662797-32066526-aa64-40eb-9000-b2e61757e1d4.png)

**Comments From Original Issue**

[N1cc3]
> `NS.growthAnalyzeSecurity()` seems to be broken and always return 0.
> 
> EDIT: It returns the amount of security increased when growing _right now_ with the _current money_ on the server. So if the server currently has full money amount and you call `ns.growthAnalyzeSecurity` with lots of threads as parameter, it will still return 0. I doubt this is supposed to work like this. It makes it pretty useless, at least for my use cases.
> 
> Apparently issue seems to be known: https://github.com/danielyxie/bitburner/issues/2755

[cmetz]
> I think that's the correct behavior, as it is an optional parameter, but the documentation is wrong here, its the same like in hackAnalyzeSecurity and should may say something like this:
> ```
> @param hostname — - Hostname of the target server.
> The number of threads is limited to the number needed to grow the
> servers to a maximum amount of money.
> ```
> Just do not use the optional hostname parameter and you should be fine, as far as i know the security increases are the same on all servers. In my scripts it's working without the hostname parameter.

**Comment by Snarling** [comment]
Fixed by 75481aa
