### ISSUE TITLE
"Proper 2-Coloring of a Graph" missing a node

### ISSUE THREAD

**Issue by dlustre** [bitburner-official/bitburner-src#674]
- [ ] Coding Contract "Proper 2-Coloring of a Graph" presents a graph with a node missing, forcing user to guess the number for the missing node. (contract-546442-Netburners.cct )
- [ ] Bitburner v2.3.1

**Comment by d0sboots** [comment]
That's not enough information to reproduce. What's the actual graph?

**Comment by HiEv** [comment]
A "node" missing?  Do you mean a vertex?

If you're talking about a vertex being missing from the array of edges given, then you can color the vertex whatever color you want, since nothing connects to it.

That's not really a bug, so much as it's an unusual, but valid, case.

**Comment by dlustre** [comment]
@HiEv Ah that makes sense, it was just confusing to me since the graph is only presented in the form of edges. There were 11 vertices (the game called it nodes I think) but there wasn't an edge that included '3' and didn't consider the case of it actually existing and having no edges to it. I don't think the contract mentioned there possibly being a graph with vertices that aren't connected to anything so thanks for the clarification
