### ISSUE TITLE
[Enhancement] - Allow user to rename purchased server

### ISSUE THREAD

**Issue by MartinLecat** [bitburner-official/bitburner-src#678]
# How
Through a script, using the `ns` namespace.

Example:
```js
/** @param {NS} ns */
export async function main(ns) {
  let success = ns.renameServer("oldName", "newName");
  if ( success ) {
    // Server renamed
  } else {
    // Server could not bne renamed (wrong oldname, script already running on said server, newname already in use etc...)
  }
}
```

So a definition such as: `NS.renameServer(oldname: string, newname: string): string`

# Cost
Renaming a server should not cost anything. However, the player should have to create/buy a program, such as `ServerRenamer.exe` at around hacking level 150.

# Why
During our firsts runs, we may plan to use a server for a specific use but become quickly limited for this use, and thus giving the server a new purpose.

Even if you can upgrade a purchased server through `NS.upgradePurchasedServer`, we may not always need to upgrade said server, and only give him a new life.

We are also limited to the number of servers we can own, which is nice but can be limiting to organise ourselves.

*Thanks for reading, love the game :D*

**Comment by d0sboots** [comment]
Already in the game:
https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.renamepurchasedserver.md

**Comment by MartinLecat** [comment]
Oh... I feel stupid about this... It doesn't show in the auto completion and didn't find anything while searching... Thanks

**Comment by d0sboots** [comment]
![image](https://github.com/bitburner-official/bitburner-src/assets/459704/550f638b-68bf-4020-a8a9-09748d10def7)

You need the /** @param {NS} ns */ boilerplate for suggestions to complete properly. (It gets auto-added for main, but not for other functions, or you might have deleted it.)

dw about it, there are plenty of rough edges both in the game and in JS. Glad you're enjoying it so far!

**Comment by MartinLecat** [comment]
I do have the jsdoc tag and it doesn't show up

Also, it does show with the TS boilerplate, but erh, it works so it's good.
