### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') (at "Augmentations")

### ISSUE THREAD

**Issue by OldManDanky** [bitburner-official/bitburner-src#679]
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'name')
* Page: Augmentations
* Version: v2.3.1 (100030008)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/2.3.1 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by Snarling** [comment]
Were you trying to load a savegame from the dev version into the main release version? Version 2.3.2 removed a lot of extra information from the save file, but version 2.3.1 was still relying on that information being available.

If this was the issue, you should not have any problems in 2.4.0.

**Comment by Snarling** [comment]
This should be fixed, but let me know if it is still an issue and needs to be reopened.
