### ISSUE TITLE
Duplicate sleeve not benefiting from Bladeburner bonus time during Bladeburner activities.

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#68]
[Vic1970]
Bitburner V1.7.0
Sleeve bladeburner activities do not benefit from bonus time. 

I have bonus time in Bladeburners.  My player activities are speeded up at about 5:1 as per normal behaviour during bonus time.  A duplicate sleeve is also doing bladeburner activities, but is not speeded up.

Intentional balance decision or error?  

**Comments From Original Issue**

[hydroflame]
> I ... didn't think of that ... I'll think on it.

**Comment by Mughur** [comment]
Sleeves have their own bonus time, which is separate from Bladeburners bonus time, so no error there

**Comment by Snarling** [comment]
Not a bug
