### ISSUE TITLE
Changes in insertion point location not maintained when switching tabs in Nano editor

### ISSUE THREAD

**Issue by PriosPrios** [bitburner-official/bitburner-src#682]
Bitburner version 3.2.1

When switching between tabs (open scripts) in the nano editor, changes in the insertion point location are seemingly not "remembered."

For example, say I switch to the foo.js tab and find that the insertion point is in the middle of the script. I scroll up and click near the top of the script, placing the insertion point near the top. Then I switch to the bar.js tab, then back to foo.js again. The insertion point will almost certainly be back in the middle of foo.js again, instead of near the top where I left it. I'm not sure what causes the game to determine where the insertion point is. I've tried saving the script, and switching away from the editor entirely and back; neither of these methods keeps the insertion point where I put it.

This is inconvenient when e.g. trying to copy pieces of one script to another script.

I've attached a copy of my latest save file just in case. Hopefully I did it right.

[bitburnerSave_1690468857_BN2x1.json.gz](https://github.com/bitburner-official/bitburner-src/files/12190858/bitburnerSave_1690468857_BN2x1.json.gz)

**Comment by Hoekstraa** [comment]
This may have to do with the way Monaco (the in-game editor) works, so this might be a potential won't fix.
Someone will have to dig into the editor related code to see.

**Comment by HiEv** [comment]
The insertion point is set to whatever point in the code was last changed, even if the code wasn't saved.

So, whatever is triggering the insertion point to be changed when you edit the code, that same thing just needs to also be triggered when you're about to go to a new tab or exit the editor window.
