### ISSUE TITLE
Error in Warehouse.ts:65 -> warehouse size exceeded the limit

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#683]
I'm trying to automate buying boosts for a division.
And came to this error:

![2023-07-28 15_27_47-ERROR](https://github.com/bitburner-official/bitburner-src/assets/20597249/c4998abd-0c9c-4f13-8e6e-15b746cef9fa)

It happened after/during buying boosts in a cycle like that:

```
// should consider warehouse size (and qty already stored in the warehouse)
	for (let city of division.cities) {
		let wh = corp.getWarehouse(divName, city);
		let freeSize = wh.size - wh.sizeUsed;
		for (let [boost, prc] of pctBoostsDist) {
			mat = corp.getMaterial(divName, city, boost);
			let marketPrice = mat.marketPrice;
			let qty = mat.stored;
			let matSize = corp.getMaterialData(boost).size;
			let boostBudget = Math.floor(budgetPerCity * prc); // ensure we stay in the budget
			let qtyToBuy = boostBudget / marketPrice;
			if (freeSize * 0.5 > qtyToBuy * matSize) { // reserve 50% of the warehouse space
				corp.bulkPurchase(divName, city, boost, qtyToBuy);
			}
		}
	}
```

I found my error in above code - should refresh warehouse size after each purchase, but still :)

**Comment by AssenD** [comment]
Could someone explain, please, how the boosts work:
a) based on `size` they occupy in the warehouse or
b) based on `quantity` bought
or maybe it's something more complex?

Found it in the sources - it's a) "boosts" material`.stored` in the wh...

**Comment by Hoekstraa** [comment]
The game should at least handle the warning/error differently. Thanks for the report!
