### ISSUE TITLE
(Should be fixed, verifying) Bitburner 2.4.0 Crashes Immediately on Launch on Steam + MacOS

### ISSUE THREAD

**Issue by moorecp** [bitburner-official/bitburner-src#685]
Version of the game: Bitburner 2.4.0 Steam MacOS

Steam updated Bitburner to 2.4.0 this morning and the game now fails to launch. The crash log seems to imply a lack of `libffmpeg.dylib` in the package, and I have verified it is not there on my system. I tried validating game files in Steam and that didn't seem to fix anything.

    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000

    Termination Reason:    Namespace DYLD, Code 1 Library missing
    Library not loaded: @rpath/libffmpeg.dylib
    Referenced from: <4C4C445D-5555-3144-A125-3BAA0D1BFAD4> /Users/USER/Library/Application Support/Steam/*/bitburner.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
    Reason: tried: '/Users/USER/Library/Application Support/Steam/steamapps/common/Bitburner/bitburner.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib' (no such file), '/Users/USER/Library/Application Support/Steam/steamapps/common/Bitburner/bitburner.app/Contents/Frameworks/libffmpeg.dylib' (no such file), '/Users/USER/Library/Application Support/Steam/steamapps/common/Bitburner/bitburner.app/Contents/Frameworks/libffmpeg.dylib' (no such file), '/usr/local/lib/libffmpeg.dylib' (no such file), '/usr/lib/libffmpeg.dylib' (no such file, not in dyld cache)
    (terminated at launch; ignore backtrace)

There is no Libraries subdirectory in `bitburner.app/Contents/Frameworks/Electron Framework.framework/` and there is no `libffmpeg.dylib` in `/bitburner.app/Contents/Frameworks/`.

**Comment by todorowww** [comment]
I can confirm having the exact same issue on MacOS after the update this morning.

**Comment by Snarling** [comment]
Can you verify if this is still happening? I uploaded some new binaries which I believe should fix the issue.

**Comment by todorowww** [comment]
I can confirm it's working now for me.
