### ISSUE TITLE
Modules are shared by processes

### ISSUE THREAD

**Issue by psznm** [bitburner-official/bitburner-src#686]
When importing a module, its state gets persisted across script runs and is shared by all processes importing the module, even across different servers. In regular javascript expected behaviour is that each script run should be completely isolated.

This enables easy cross-process communication, but it also creates very enexpected bugs and removes the possibility of using library module with global state that is unique to a process.

Is this difference in behavior intended?
```
// test1.js
import {getGlobalVar, incrementGlobalVar} from "/test2";

export async function main(ns) {
    incrementGlobalVar();
    ns.tprint(getGlobalVar());
}
```

```
// test2.js
let globalVar = 0;
export const incrementGlobalVar = () => globalVar++;
export const getGlobalVar = () => globalVar;
```

If I run test1.js, I expect the output to always be 1 according to how javascript works.

Real output:
```
[home /]> ./test1.js
Running script with 1 thread(s), pid 6670 and args: [].
test1.js: 1
[home /]> ./test1.js
Running script with 1 thread(s), pid 6672 and args: [].
test1.js: 2
[home /]> ./test1.js
Running script with 1 thread(s), pid 6674 and args: [].
test1.js: 3
```

**Comment by Snarling** [comment]
Each script execution is a separate call to the main function of that script, not a unique module in your browser.

For the browser to run-run your top-level code every single time you run a script, it would need to make a new module for every single script execution. You would run out of memory very quickly, especially with meta gameplay strategies that run many thousands of scripts at once.
