### ISSUE TITLE
Remove vscode extension

### ISSUE THREAD

**Issue by hydroflame** [bitburner-official/bitburner-src#687]
https://marketplace.visualstudio.com/items?itemName=bitburner.bitburner-vscode-integration

This extension is very outdated. We use something more flexible now

**Comment by d0sboots** [comment]
Is it just outdated, or broken? I ask because if it's just the former, we might be breaking folks.

**Comment by davad** [comment]
It's working for me at the moment. I'm able to make file changes and have them sync one-way to Bitburner.

**Comment by hydroflame** [comment]
It's deprecated.

**Comment by d0sboots** [comment]
Sure, but there's a difference between "deprecated" and "needs to be removed."

Is this causing a support burden somehow? Is there a pressing *need* to delete it?

**Comment by AssenD** [comment]
> This extension is very outdated. We use something more flexible now


![image](https://github.com/bitburner-official/bitburner-src/assets/20597249/2f586c53-016e-4658-a9c9-8d7b66d443c4)

Would you, please, give us an alternative?

**Comment by Caldwell-74** [comment]
> > This extension is very outdated. We use something more flexible now
> 
> ![image](https://user-images.githubusercontent.com/20597249/257743502-2f586c53-016e-4658-a9c9-8d7b66d443c4.png)
> 
> Would you, please, give us an alternative?

on the official side
https://github.com/bitburner-official/typescript-template/blob/main/BeginnersGuide.md

on the unofficial side
https://github.com/Tanimodori/viteburner-template

**Comment by AssenD** [comment]
@zerbosh Thank you!

But both alternatives are a way too complicated for a normal player.
I suppose they are required for a contributor.
I, for example, don't want to flood my `home PC` with javascript tools, VS Code is more than enough :)

@hydroflame 
So, please, consider the lesser players too, not only contributors.

When I started playing the game, I had almost zero knowledge about javascript. 
Now I start to understand some of other players' code and wrote a lot myself :)
But if you are pushing me to go to full stack javascript developer, I will probably quit.

**Comment by Hoekstraa** [comment]
Alternate solutions:
- Change the [marketplace](https://marketplace.visualstudio.com/items?itemName=bitburner.bitburner-vscode-integration) and [github page](https://github.com/bitburner-official/bitburner-vscode) to mention the plugin is deprecated in a big header at the top, use at personal risk, etc.

- Replace it with a new VSCode plugin based on Filesync code as an easier to use, non-deprecated alternative

THIS MESSAGE DOES NOT IMPLY ANY INTENT!

**Comment by rayanth** [comment]
2.4.0 In-game documentation > Tools & Resources still mentions this VScode Extension as well.

**Comment by Snarling** [comment]
See issue #1034
