### ISSUE TITLE
Misleading/incorrect documentation/UI for Stanek's Gift

### ISSUE THREAD

**Issue by Gorfiend** [bitburner-official/bitburner-src#689]
Just started BN 13 (steam version 2.4.0), and noticed an issue with how charges work vs. how they are explained/displayed.

The help popup says "Note that it is no more effective to charge a fragment many times with few threads than to charge few times with many threads, so there is no need to distribute charging jobs across multiple scripts.", and the "Charge: 10.000" display agrees, showing the total number of threads that have charged it. However, the resulting effect from that fragment depends on how exactly it was charged: charging fewer times but with more threads will end up having a greater effect than charging many times with few threads.

For example, charging a "hacking skill" fragment 1 time with 10 threads will make it "Charge: 10.000" and "Effect: +7.50% hacking skill", while charging 10 times with 1 thread each will also make it "Charge: 10.000" but have "Effect: +2.44% hacking skill"

Separately, some of the fragments don't say all the stats they effect, e.g. the "hacking skill" fragments also increase hacking exp (same for all the physical stats as well), and the "crime money" fragment also increases crime success chance.

**Comment by d0sboots** [comment]
It's still the case that "It is no more effective to charge a fragment many times with few threads than to charge few times with many threads, so there is no need to distribute charging jobs across multiple scripts." It just also happens to be *less* effective, as well. XD

But yes, sounds like some tweaks should be made.
