### ISSUE TITLE
SoA - Knowledge of Apollo broken

### ISSUE THREAD

**Issue by Triple-Factorial** [bitburner-official/bitburner-src#690]
Screenshot:
https://drive.google.com/file/d/12UDaLppgc1MSa-zb2RhZTh0pP2YtVcWN/view?usp=sharing

Save:
https://drive.google.com/file/d/12N4zWIWZYxLIXCSdkoRFD1Lnx-qyEU7U/view?usp=sharing

v2.4.0 (fc86895c3)

In short, the Apollo augmentation, which is supposed to show which wires are wrong, doesn't seem to function right. Simply infiltrate a company with that aug installed (I've tried multiple) and keep going until you get the wire minigame. It feels very likely to be wrong, like it's getting a prior or future set instead. This basically makes infiltrating impossible to efficiently do since it can become a pure guessing game about which "bad" wire is actually good.

**Comment by Snarling** [comment]
My bad, there is some confusion in that file due to wires being referred to using their wire index in the array (starts at 0), not their wire number (starts at 1), there was an off-by-one in the SoA aug display. Should be fixed by e5b1fd6
