### ISSUE TITLE
Changelog still links to readthedocs

### ISSUE THREAD

**Issue by brunnerh** [bitburner-official/bitburner-src#691]
> v2.4.0 - Death to readthedocs

https://github.com/bitburner-official/bitburner-src/blob/a85efbc4da58fd8e12b759ff8cd227827903e118/src/GameOptions/ui/GameOptionsSidebar.tsx#L258-L263

[A search](https://github.com/search?q=repo%3Abitburner-official%2Fbitburner-src+readthedocs.io&type=code) also shows a few other instances.

**Comment by Hoekstraa** [comment]
https://github.com/bitburner-official/bitburner-src/pull/702

**Comment by Snarling** [comment]
Addressed in #702
