### ISSUE TITLE
Faction augmentatons reputation not updating correctly

### ISSUE THREAD

**Issue by ztitchez** [bitburner-official/bitburner-src#695]
as the title says when I enter the UI to buy augments from any faction, the reputation doesn't doesn't update in the UI accordingly, if you are doing a task for the faction to increase reputation faster it will show up on the Overview interface but on the "faction augmentations - faction" reputation keeps the same value and on the section where it's showing the money/reputation price the values will stay in red instead to change to white when you have the required repuration to buy an augment as previous version, if you change page and return it will update all values accordingly, also the buy button will update if you have the required money and reputation

- enter the UI to buy an augment from a faction,  leave and return will update
- Version of the game, e.g. Bitburner v2.4.0 (fc86895c3)

**Comment by rayanth** [comment]
I have fixed this in a fork of 2.4.0 dev branch by simply adding `useRerender(200);` right after `const rerender = useRerender();` in `Faction\ui\AugmentationsPage.tsx` - got the idea by simply copying it from FactionPage, but I'm not certain if this is the best solution. I couldn't comment out the existing line as it breaks other references, so I'm thinking I should test the fix a bit more and look into the other places that are using the `rerender` declaration.

```
...
export function AugmentationsPage({ faction }: { faction: Faction }): React.ReactElement {
  const rerender = useRerender();
  useRerender(200);
...
```
