### ISSUE TITLE
Documentation has not been completed fully, still areas with placeholder text

### ISSUE THREAD

**Issue by MatthewG25** [bitburner-official/bitburner-src#696]
When playing on version v2.4.0f  (fc86895c3) on the steam version of the game it is noted that certain sections of the internal documentation still has placeholder text to be filled. The pages affected are:
 
- BladeBurners only having placeholder where the documentation should be
- Corporations, that has nothing on its page, not even its title, 
- Gang, which as one line then has placeholder after the first line

The rest of the docs have something in them but a pass from the old read the docs to make sure all information is brought over would have to be done to make sure that it is up to date and has the right information. 

![image](https://github.com/bitburner-official/bitburner-src/assets/25006383/a39d5725-876d-4194-94fc-2e7e2cc05b6d)
![image](https://github.com/bitburner-official/bitburner-src/assets/25006383/95d23579-35f7-495b-9cfe-8fe18750cad2)
![image](https://github.com/bitburner-official/bitburner-src/assets/25006383/9b04f25c-14fa-4143-85a5-5c52b03efad5)

Here are images as of writing this to show the docs as they are in game with respect to each of the topics as discussed above.

**Comment by hydroflame** [comment]
Yeah. I'm lazy and will lets users write it.

**Comment by d0sboots** [comment]
Maybe leave this one open until that actually gets done?

**Comment by hydroflame** [comment]
I'll split it.
