### ISSUE TITLE
Infiltration Wire Cut Augmentation Glitched

### ISSUE THREAD

**Issue by CWestray** [bitburner-official/bitburner-src#703]
The augmentation for the Wire Cutting minigame during infiltrations is not working correctly.
Having the augmentation should (and used to) make _bad_ wires a teal color, and leave the correct wires to cut as their normal colors.

This does not work at all, and it almost seems like the colors of good/bad wires are random, making the challenge impossible without guessing the correct wire(s) when their color (and not number) is involved.

I typically play on Chome @ https://bitburner-official.github.io/, however even after clearing cookies/cache, using Edge or FireFox, and even trying the save on the Steam version — the issue persists.

I've attached the save .json in case there is simply something wrong with it.
Was using previous version where this problem began, but I've forgotten its version. Currently playing on v2.4.0.

[bitburnerSave_1690992704_BN1x1.zip](https://github.com/bitburner-official/bitburner-src/files/12242330/bitburnerSave_1690992704_BN1x1.zip)

**Comment by CWestray** [comment]
Here is an example image of the problem:

![image](https://github.com/bitburner-official/bitburner-src/assets/141083219/b80b4328-0adb-4a35-ae59-cd9314c06b2b)

**Comment by Bryan-Downing** [comment]
It looks like commit e5b1fd6 might have the fix for this.

**Comment by CWestray** [comment]
> It looks like commit [e5b1fd6](https://github.com/bitburner-official/bitburner-src/commit/e5b1fd6b587ce7fb8b7fe53739d16e73fcc4890a) might have the fix for this.

Thank you for letting me know, glad to know it was spotted!
I'll wait for release, just wanted to make sure it was known.
