### ISSUE TITLE
Corp Job requirements missleading

### ISSUE THREAD

**Issue by VictorS** [bitburner-official/bitburner-src#708]
When applying for Corp job, the reputation requirement is misleading,
Both in tooltip and in the error message the reputation requirement will say 40000.
In the Corp info it will say 38.678k 

Reputation requirement should be formatted the same way the info is formatted: 40.000k

Steps to reproduce:
1. apply for a software job in a corp you never worked for
2. work a bit
3. go back to the job screen, hover over "apply for Software Job" button
4. see the tooltip requirement says reputation 8000 required. Should say 8.000k required
5. click the "apply for Software Job" button
6.  see the error message requirement says reputation 8000 required. Should say 8.000k required

Bitburner v2.4.0 (fc86895c3)

![job_requirements_1](https://github.com/bitburner-official/bitburner-src/assets/176763/18342a26-9b58-450b-a28e-e7c840a45d5a)
![job_requirements_2](https://github.com/bitburner-official/bitburner-src/assets/176763/7dd78296-8212-4e56-95a1-72123116dad9)

**Comment by Snarling** [comment]
I wouldn't say "misleading", it's just not formatted consistently.

But yeah for consistency we should format the reputation in these two locations where it's not formatted.
