### ISSUE TITLE
documentation page incorrect title

### ISSUE THREAD

**Issue by VictorS** [bitburner-official/bitburner-src#711]
The page for formatNumber() has title of formatRam()
https://bitburner-official.readthedocs.io/en/latest/netscript/basicfunctions/formatNumber.html

The description, parameters and examples look correct.

![doc_formatNumber](https://github.com/bitburner-official/bitburner-src/assets/176763/697b8322-5ccf-4103-b57d-a466d0714a26)

**Comment by VictorS** [comment]
This is correct though:
https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.formatnumber.md

**Comment by d0sboots** [comment]
The readthedocs pages are going away very soon now, so this will no longer be a concern.
