### ISSUE TITLE
ns.getScriptLogs() -- call with pid

### ISSUE THREAD

**Issue by Zerazera** [bitburner-official/bitburner-src#714]
Hello,

Is it possible to allow ns.getScriptLogs() to accept pid as an argument? Currently to get logs by pid requires calling ns.getRunningScript() at a RAM cost of 0.3 vs 0 for ns.getScriptLogs().

**Comment by myCatsName** [comment]
I would guess PID could be added as an option there. I think the question is if these RAM costs were a design and balance choice, which I think they might be -

 It sounds like you can get your logs "free" if you know the PID you need, and it is costing you 0.3 to get a PID now. That might be a way to encourage you to think of other ways to find or store PIDs. For example, some players assign every new script to a unique port, and I believe ns.exec() will return a PID if you launch scripts that way - there might be other techniques too.

**Comment by d0sboots** [comment]
I don't see this as a huge issue? You should not be using logs to communicate between scripts - ports should be used for that. Off the top of my head, I can't think of *any* reason to get another script's logs, but 0.3GB is a very small price to pay if you do have that edge case.

**Comment by Snarling** [comment]
![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/1bc59a03-2cb4-4cf8-bcd8-92dff3646b33)

Functionally it should already accept a pid (that's what the scriptIdentifier helper is doing), it looks like it's just the documentation that needs to be updated.
