### ISSUE TITLE
Obsolete?/changed? ns functions results in ns.getFunctionRamCost Runtime Errors

### ISSUE THREAD

**Issue by s-venter** [bitburner-official/bitburner-src#717]
Iterate through ns objects, identify those that are functions and call getFunctionRamCost on each.

Runtime Errors:
1. Invalid function passed to getRamCost: getServerRam
2. Invalid function passed to getRamCost: singularity.getAugmentationCost
3. Invalid function passed to getRamCost: sleeve.getSleeveStats
4. Invalid function passed to getRamCost: sleeve.getInformation
5. Invalid function passed to getRamCost: corporation.assignJob
6. Invalid function passed to getRamCost: corporation.getEmployee
7. Invalid function passed to getRamCost: corporation.getExpandCityCost
8. Invalid function passed to getRamCost: corporation.getExpandIndustryCost
9. Invalid function passed to getRamCost: corporation.getIndustryTypes
10. Invalid function passed to getRamCost: corporation.getMaterialNames
11. Invalid function passed to getRamCost: corporation.getPurchaseWarehouseCost
12. Invalid function passed to getRamCost: corporation.getResearchNames
13. Invalid function passed to getRamCost: corporation.getUnlockables
14. Invalid function passed to getRamCost: corporation.getUpgradeNames
15. Invalid function passed to getRamCost: formulas.work.classGains

**Comment by Snarling** [comment]
Yeah there's a function (`removedFunction`) that generates an error message when you try to use one of those functions. Looks like those properties are still iterable, so you are discovering the names for functions that no longer exist when iterating keys/entries on ns or its sub-layers.

Based on some of the behind the scenes stuff with each ns object actually being a Proxy, I am not sure how easy this will be to address but I'll look into this over the next couple days to try and make those removed functions non-iterable.

**Comment by d0sboots** [comment]
It should be doable, in particular JS *already* has the concept of non-enumerable properties of an object so this should just be a tweak to the `getOwnPropertyDescriptor` handler

Edit: This might also fix the bug with warnings shown when serializing/iterating `ns`

**Comment by HiEv** [comment]
You can create a custom [iterable protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) and thus have it give whatever you want back when people iterate the `ns` object.
