### ISSUE TITLE
Manual neuroflux generator purchases give wrong neuro levels

### ISSUE THREAD

**Issue by RickEdinson** [bitburner-official/bitburner-src#723]
When manually purchasing Neuroflux Generators, the Neuro level of generator received is always one level behind what it should be. Buying a singular generator and installing keeps you at your original Neuro level. I haven't tested this with using scripts. This is for BitBurner Steam v2.4.0 (fc86895c3).

![Pic1_Augmentation_Screen_Before_Purchase](https://github.com/bitburner-official/bitburner-src/assets/141604606/b60dfcb9-ee0f-430f-9c8e-973b73c30476)
![Pic2_Faction_Screen_Before_Purchase](https://github.com/bitburner-official/bitburner-src/assets/141604606/0f7a1c2d-bae8-48f2-b1ed-6b959a832d5a)
![Pic3_Faction_Screen_After_Purchase](https://github.com/bitburner-official/bitburner-src/assets/141604606/ef650317-63ae-4491-ba5d-bc8cba6650d5)
![Pic4_Augmentation_Screen_After_Purchase](https://github.com/bitburner-official/bitburner-src/assets/141604606/4d53b8ed-1ac2-4a3e-b467-00a886315339)
![Pic5_Installation_Message](https://github.com/bitburner-official/bitburner-src/assets/141604606/b52228f5-9ea9-48fa-9e08-e6ae461cb703)
![Pic6_Augmentation_Screen_After_Installation](https://github.com/bitburner-official/bitburner-src/assets/141604606/b2d8340e-b3f3-4993-899c-23e51a41a058)

**Comment by Snarling** [comment]
Should already be fixed in 2.4.1 dev by #718 , let me know if this is a separate bug and we can reopen
