### ISSUE TITLE
Corporation Stock Price one billion times higher than it should be (Bug?)

### ISSUE THREAD

**Issue by Krate8** [bitburner-official/bitburner-src#727]
Version: Bitburner 2.4:

The game sets the stock price to high by 9 orders of magnitude.

Steps: 
1. Start corporation paying full150B.
2. Create any division that turns a profit (profit probably optional)
3. IPO
4. Buyback **ALL** shares.

Result: Stock price will increase endlessly for hours.

Why? 
getTargetSharePrice() is coded as follows: 
`   this.valuation / (2 * (this.totalShares - this.numShares) + 1);`

Owning all of the shares in your own corporation turns this into valuation / (2 * (1B - 1B) + 1) i.e. valuation / 1;

So, if the valuation for your corporation is 10B, then the stock price will trend toward 10B per share (!!!) 

If I had to guess I think this code is supposed to be like so:
`   this.valuation / (2 *  this.totalShares - this.numShares);
`
If the player doesn't own any shares, both result in the same result of valuation / 2B. 
If the player owns all the shares, the existing code results in valuation, this version results in valuation/1B (a billion times less). 

I do think it's a bug, and I think it's kind of important. I was able to turn 150B into 150000Q in less than 24 hours on a bitnode with a 50% penalty to corporate valuations.  Even a player is bad at corporations they would be able to use this method to make absurd money in a day or two, making the a lot of the game irrelevant since you have virtually infinite money and faction reputation. 

Also: Note that when you IPO the game calculates the share price like so:
`const initialSharePrice = corp.valuation / corp.totalShares;`

So if your company is public and you own all the shares, its worth one billion times more than if your not public and you own all the shares. This is another indicator to me that the publicly traded share price when you own all the shares is unintended.

**Comment by d0sboots** [comment]
I don't think it's a bug. You can get that level of money faster with corps through regular play, or even through non-corp means (hacking+hash will get to that level in less than 24 hours with that proper scripts).

It's a simple strategy, but the forced slowness of it is self-balancing.

**Comment by Krate8** [comment]
1. There other strategies that might be able to make this kind of money, but those require some source files and scripts and skill. This requires none of those things, you just need 150B and access to corporations.

2. The game is setting the price of one single share to the valuation of the whole company. That doesn’t make a lot of sense to me. It makes sense that it would increase the price some (2x in my example) but not 1,000,000,000x.

**Comment by jjclark1982** [comment]
See also this [discussion on Reddit](https://www.reddit.com/r/Bitburner/comments/165gprd/corporations_are_dumb_make_1024_in_two_days/).
