### ISSUE TITLE
Simultaneous Neuroflux Governor don't work

### ISSUE THREAD

**Issue by tfchdj** [bitburner-official/bitburner-src#735]
Version: Bit Burner 2.4.0 (fc86895c3)

Issue: Buying more than one Neuroflux in one run doesn't install properly.

Context/Reproductability:
Joined CyberSec
Bought 3 augment: (in this order, from this faction, no other faction joined, got an invit from Something Burner)
- Synaptic Enhancement Implant
- Neuroflux Governor 1
- Neuroflux Governor 1?

Augment tab does have a red [3] in a circle.
The screen only show 2 upgrades, but the % are indeed showed to be changed by rougly 2%.
After the rest however, the stats are only reduced from 1%.

Joined is the savefile before reset/installing the augments.

**Comment by elidoran** [comment]
@tfchdj Hello. This has been fixed. See comment in #723 about the fix in #718.
