### ISSUE TITLE
Hacknet level base cost is 500 but first level purchase is 520, 1 multiplier ahead.

### ISSUE THREAD

**Issue by s-venter** [bitburner-official/bitburner-src#746]
As opposed to first ram and core purchase being their base costs of 30k and 500k respectively.

**Comment by JamesWilcox-git** [comment]
Please assign this to me :)

**Comment by d0sboots** [comment]
K, it's yours XD
(We don't really assign bugs like that, but if you want to tackle this no one else is gonna grab it at the same time.)

**Comment by JamesWilcox-git** [comment]
Thanks lol
