### ISSUE TITLE
Remainder operator always returning 1

### ISSUE THREAD

**Issue by MatthewLAllen** [bitburner-official/bitburner-src#750]
- [ X] Save file
- [ X] Minimal scripts to reproduce the issue
- [ X] Steps to reproduce
- [ X] Version of the game: 2.4.0 playing from https://bitburner-official.github.io

Execute the following from a script
/** @param {NS} ns */
export async function main(ns) {
  let x = 25;
  let y = 3;
  let z = x % y;
  ns.tprint(z);  // z == 1 here instead of the expected 4
}

[bitburnerSave_1693072948_BN1x1.json.txt](https://github.com/bitburner-official/bitburner-src/files/12446462/bitburnerSave_1693072948_BN1x1.json.txt)

**Comment by myCatsName** [comment]
>instead of the expected 4

Not to be rude, but I think you misunderstand what modulo does.

https://divisible.info/Modulo/What-is-25-mod-3.html

**Comment by MatthewLAllen** [comment]
Sorry, in the past other languages have used Modulo and the Remainder operator interchangeably.  The % operator in the languages I have encountered so far operate as the remainder operator.  I have updated the title to reflect this.  Since bitburner is a superset of javascript I would expect the operator behaviors to be unchanged.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder

**Comment by MatthewLAllen** [comment]
Closed because the operator works better if you feed it the original value and divisor instead of the result of the math.floor with the divisor.  25 was also a bad example just because it has too many valid or near valid factors.  My confusion all around.

**Comment by d0sboots** [comment]
I'm glad you figured it out. `%` *does* return the remainder... and the remainder after dividing by 3 must be less than 3, and thus cannot be 4.
