### ISSUE TITLE
Array.sort has no effect

### ISSUE THREAD

**Issue by j-freimuth** [bitburner-official/bitburner-src#751]
Array.sort has no effect in version v2.4.1dev 

Minimal script:
```js
export async function main(ns) {
  let foo = [1,53425,23,3234,24,5,232652]
  foo.sort((a,b) => a < b)
  ns.tprint(foo)
}
```
Output: 
foo.js: [1,53425,23,3234,24,5,232652]

Corresponding script run in browser
```js
let foo = [1,53425,23,3234,24,5,232652]
foo.sort((a,b) => a < b)
console.log(foo)
```
Output:
Array(7) [ 232652, 53425, 3234, 24, 23, 5, 1 ]

**Comment by myCatsName** [comment]
I could be wrong here, but I think you are expecting the wrong behavior. 

For example you can see sort in action and reverse with `console.log(foo.sort((a,b) => a-b))` and
  `console.log(foo.sort((a,b) => b-a))` . I assume that is what you want to accomplish.

.sort(a,b) evaluating a>b is maybe not returning what you expect, and however it is evaluated is equivalent to returning zero or undefined, ie. not changing the order or sorting it by an inconsistent, browser-specific method. 

Shown in VS code you see these statements do not change order 
![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/c1267f7b-3c02-4343-9675-399c54ea8cf5)

resource - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description

**Comment by j-freimuth** [comment]
@myCatsName 
You're totally right. Uff, stupid of me. And I confirmed it also works in the game... Interesting, so my browser understood false as 0 and true as 1, but the game (node?) does not... But anyway, this issue is closed. Thank you.

**Comment by d0sboots** [comment]
The game is also the browser. False and true are like 1 and 0...depending on the context. This gets into "truthy" and "falsy", one of the most annoyingly complex subjects in JS. Suffice to say, it's easy for things to work (or not work) based on seemingly irrelevant code differences.
