### ISSUE TITLE
Problem with grafting since version 2.4.1 or 2.4.0

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#766]
It's strange, because it happens (or it seems) at random.
After the first graft (I aim for QLink obviously), player stat are reduced about 3 times (300%)
and grafted augmentation doesn't seem to work.

After reset - QLink starts to work as expected. 

I'm sorry I cannot give exact steps to reproduce.

It looks as regression in last (probably one before) patch.

**Comment by AssenD** [comment]
It happend again, but this time I experimented more.
I saved a game then restored previous one and then restored the last.
All this because I wanted to take pictures of the stats before and after grafting.
For my surprise, after last reload, everything looked as supposed to be.

So, IMHO, the problem could be with some missing/lost refresh/recalc after grafting.

Here are the pictures:
Before:
![2023-09-02 11_01_05-Before](https://github.com/bitburner-official/bitburner-src/assets/20597249/c15b8964-8a23-4854-946f-572aac62a729)


After:
![2023-09-02 10_58_41-After](https://github.com/bitburner-official/bitburner-src/assets/20597249/aae1b1bf-7d0e-42bd-b3ba-9a000896e85b)

**Comment by d0sboots** [comment]
I am confused. *Both* pictures show QLink being installed. What, precisely, is the before/after here?

**Comment by Caldwell-74** [comment]
i guess its that the hack lvl is so differently (9k and 1.4k) wich without knowing the exp values is hard to judge but might indicate that qlink wasnt applied correctly?

**Comment by AssenD** [comment]
@d0sboots - You're right, it's confusing.
The After picture is after grafting, but before reloading - the one with 'broken' stats.
The Before picture show the stats (as they was) before finishing the graft, 
but since I didn't had a save I took the picture after reloading from save file.
Sorry for misleading you.  
The point is - the stats were more than 4 times higher BEFORE grafting finished.
After save/import - they are OK.

@zerbosh Tell me if I can provide more info, pls.
The problem is not only with QLink, `nickofolas Congruity Implant` also reduced the stats.
I found workaround, but it's manual action, not sure if I can automate it.

**Comment by AssenD** [comment]
I added a timestamp in Overview panel to help with timing.
New pictures:
Just Before:
![2023-09-07 07_15_11-Before](https://github.com/bitburner-official/bitburner-src/assets/20597249/d93b0568-3a28-4657-ba0a-54318c3f9a00)

After:
![2023-09-07 07_15_47-After](https://github.com/bitburner-official/bitburner-src/assets/20597249/74c8e33a-c64c-429a-a6e9-fb49376e0bd0)

@zerbosh Here is the save just before starting the first graft:
[bitburnerSave_1694059379_BN12x85_before.json.log](https://github.com/bitburner-official/bitburner-src/files/12545400/bitburnerSave_1694059379_BN12x85_before.json.log)

**Comment by Caldwell-74** [comment]
can confirm it doesnt update properly when Congruity Implant isnt yet grafted
after that it works as expected

**Comment by TheAimMan** [comment]
This is fixed with https://github.com/bitburner-official/bitburner-src/pull/816
