### ISSUE TITLE
changes to a server minimum security not preserved on reload

### ISSUE THREAD

**Issue by giocri** [bitburner-official/bitburner-src#768]
version v2.4.1(de5ebc993)

reduction of minimum security through hacknet is not preserved when loading the save.

i reduced ecorp minimum security to 1 using the hacknet but opon loading the file the next day it was back to the defaul

**Comment by Caldwell-74** [comment]
are you sure you saved after manipulating the minimum security?
i tried different ways to save/load and couldnt reproduce the issue

**Comment by giocri** [comment]
I am sure it was saved because the amount of purchases persisted instead.

Anyway I have since reduced the security again so if today I get the same problem I will post the save file

**Comment by giocri** [comment]
this time didn't give any issues maybe it has something to do with having weaken scripts running when i saved idk

**Comment by Hoekstraa** [comment]
Closing as it doesn't seem to be reproducible. Feel free to reopen if you can repeat it reliably!
