### ISSUE TITLE
sleeve bladeburner tasks have missing members in `SleeveTask` interface 

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#78]
[vladtepesch]
Currently `SleeveTask` has no members for Bladeburner actions, so its not possible to read out a sleeves task and restore it later.

**Comment by TheAimMan** [comment]
This one appears to no longer be an issue

{"type":"BLADEBURNER","actionType":"Contracts","actionName":"Tracking","tasksCompleted":33420,"cyclesWorked":4,"cyclesNeeded":5,"nextCompletion":{}}
