### ISSUE TITLE
Problem with `ns.getResetInfo()` function's return value

### ISSUE THREAD

**Issue by guy-732** [bitburner-official/bitburner-src#781]
Bitburner v2.4.1 (de5ebc993)

The return value of `ns.getResetInfo()` has 2 empty maps (`ownedAugs` and `ownedSF`)
![image](https://github.com/bitburner-official/bitburner-src/assets/81652178/80af7b0b-1e30-4d3b-9cfc-28ad877da6ce)

I decided to just print the result to see what there was and saw that the fields were empty.
I do have source files (obviously, I wouldn't be in BN 3 if I didn't)
![image](https://github.com/bitburner-official/bitburner-src/assets/81652178/2a315922-8e45-4e0b-a565-910a0dcf42c2)

And I do have augments (20 unique in the stats page)
![image](https://github.com/bitburner-official/bitburner-src/assets/81652178/fdce370c-cd93-4ae5-89ae-1d24e5d33b7f)

And yet, the maps remains empty for some reason

The script I used is named **owned-sf.js**
(I just wanted to print the source files initially but noticed it was empty, so I decided to print the whole thing)

Here is the save file in case your `getResetInfo()` works (which it probably does, considering what the implementation does)
[bitburnerSave_1693945083_BN3x1.json.txt](https://github.com/bitburner-official/bitburner-src/files/12528136/bitburnerSave_1693945083_BN3x1.json.txt)

The weirdest part is, when trying to debug... the variables are valid for the sourceFiles (I can't get the other, the watch just says that `Player`  is not available)
![image](https://github.com/bitburner-official/bitburner-src/assets/81652178/d7a357a2-7896-451c-857c-8de1f3855058)

**Comment by d0sboots** [comment]
Those aren't empty maps. Those are objects with no enumerable properties. Maps do not store their entries as object properties, so this is the expected result from converting then to a string. Yay, JS.

There is a PR to change the behavior of tprint to print the contents of maps and sets.

**Comment by d0sboots** [comment]
(If you write some more code to iterate over the contents of the map, or console.log the map value, you should see it.)
