### ISSUE TITLE
ns.growthAnalyze is giving invalid number of threads

### ISSUE THREAD

**Issue by dpedroz** [bitburner-official/bitburner-src#785]
- [ X] Save file https://drive.google.com/file/d/1aZvfZEbQnB-h1RkhDYjNOFhbXdE4_tDi/view?usp=drive_link
- [ X] Version of the game, e.g. Bitburner v2.4.1 (de5ebc993)

- [X ] Steps to reproduce

1. Have a server, in my save file it's phantasy, that has 50% of money (or bring it above 50 %)
2. When I run a hacking script and perform `ns.growthAnalyze('phantasy', 2.0, 1)` it gives me result of 671 threads
3. When I run `weaken.js phantasy -t 671` the result is 
> grow: Available money on 'phantasy' grown by 85,707830%. Gained 6,442k hacking exp (t=671).

That is - Server should be brought to 100% but it's not.

The above can be easily presented by running `run example.js`, on my save file. What can be seen is that ns.growthAnalyze gives some number of threads to run to grow to 100% and it's not growing that much.
> INFO  phantasy from 300,113m to 600,000m  :mult:1,999 - threads:671

and then

> INFO  phantasy:  $ 556,861m / 600,000m 

Give it few cycles if you don't see same results...

What is strange is **that it's not always happening**. I checked if all the scripts are finishing, I checked if splitting on different hosts at the same time has any effect on grow. There are only 1-core hosts...

Unless I don't understand some game mechanics, of course...

**Comment by Caldwell-74** [comment]
one problem of growthAnalyze is that it gives an result based on current stats
so if you calculate when the server is at min security and then the grow finishes when the server has higher security then it wont be correct because higher security weakens the effect of grow

could it be this what makes it happen sometimes but not always?

**Comment by dpedroz** [comment]
> one problem of growthAnalyze is that it gives an result based on current stats so if you calculate when the server is at min security and then the grow finishes when the server has higher security then it wont be correct because higher security weakens the effect of grow
> 
> could it be this what makes it happen sometimes but not always?

Yes, I think it might be the reason. Indeed this was the mechanics I didn't thought about
