### ISSUE TITLE
 Invalid string length at JSON.stringify

### ISSUE THREAD

**Issue by Caldwell-74** [bitburner-official/bitburner-src#799]
we had it a couple times that players where unable to save and or the engine crashed (so no progress ingame)
when the savegame became to big through files or running scripts with long names
just want to have an issue open if anyone finds a good way to improve the situation 
even if saving isnt possible the game should notify the player about the problem (not just in the dev console)
and the engine should finish updating

**Comment by d0sboots** [comment]
Just did a little research on this. This is a V8 limitation (So Chrome, dunno what/if any limit Firefox has) of 512Mi UTF16 chars in a string - So 512MiB in practice.

It can potentially happen anywhere we try to JSON.stringify, which *should* only be in the savegame stuff. There should already be code to pop a toast when game saving fails, not sure why it's not working.

**Comment by Caldwell-74** [comment]
yeah i think the toast pops up but that doesnt tell the player much about why the save cant happen
i just think the situation could be improved for the player even if the core problem cant be solved

and just to make sure its not missunderstood 
with engine i didnt mean v8 but the engine.tsx
iam not sure if a try catch or a restructure or something else could be done but when saving failes then the engine.tsx doesnt finish the processing of the mechanics => time stand still
