### ISSUE TITLE
Savegame compression

### ISSUE THREAD

**Issue by d0sboots** [bitburner-official/bitburner-src#800]
Currently, our savegames are raw base64-encoded json. This is simple, but can lead to large savegames, especially in some semi-common circumstances.

The purpose of this FR is to scope out a design for adding compression. It might be that this feature is deemed too complicated for the benefit, which is fine - this then will serve as a central place to explain why.

A major trickiness is that JS does not have built-in support for compression *that is exposed as an API*, even though support for deflate is mandatory in various web standards. There are packages that implement deflate in JS, but their error-handling (and performance) is often less than great. Still, for handling working files of reasonable size that is an option, and we already have a dependency on jszip.

The other route is to compile zlib into WASM. I've done this, it works, is high-quality, fast, and (when done properly) can have a very small library size, but means more infrastructure work.

There's also work to be done with versioning. Probably the existing JSON structure would need/want to be kept for compatibility and the quick stats view during loading, but only a stub of info would be kept there, with the bulk of the data being in a compressed JSON payload after.

**Comment by Hoekstraa** [comment]
> A major trickiness is that JS does not have built-in support for compression that is exposed as an API

Is this not a compression API, available in seemingly all modern browsers?
https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API

There's a small demo of it available here:
https://developer.chrome.com/blog/compression-streams-api/

**Comment by d0sboots** [comment]
Oh, very neat! It looks like support for that only landed in Safari and Firefox a few months ago, but it's something to look forward to for the future.

**Comment by evanjs** [comment]
Seems like we're almost at ~90% coverage according to [caniuse](https://caniuse.com/mdn-api_compressionstream).

I wonder if this is worth investigating now

**Comment by LJNeon** [comment]
Are we unable to use npm packages in the game code itself? I guarantee there are high quality and actively maintained packages for compression.

Also this seems like a replacement of #5?

**Comment by d0sboots** [comment]
Actively maintained, yes. High quality? Enh. As I said in the base post, I've surveyed the available options, and they tend to lack in error-handling or performance (or both).

Edit: Yes, this is basically a replacement of #5.

**Comment by LJNeon** [comment]
If we're able to use the nodejs API (idk if webpack lets you just bundle it in) then isn't this as simple as just using the provided [zlib](https://nodejs.org/api/zlib.html)?

**Comment by d0sboots** [comment]
We can't use that API though, for one thing it would only work for Electron.

The correct answer is probably to just use the web API that is now built-in for compression, it probably has wide enough support by now if we actually want to support this.

**Comment by LJNeon** [comment]
Ah, I saw use of npm packages in code that would also run in browser and incorrectly assumed nodejs packages could also be bundled. I googled compression packages and this one came up right away: [fflate](https://www.npmjs.com/package/fflate). It seems to be compact, performant, and actively maintained?

**Comment by LJNeon** [comment]
Also as another option it looks like we already use jszip for the download command, we could reuse that for save file compression as well?

**Comment by d0sboots** [comment]
Yes, I did already mention that in the base post too. ^_^;;
