### ISSUE TITLE
Nuking servers without required hacking level

### ISSUE THREAD

**Issue by RuntsTor** [bitburner-official/bitburner-src#801]
Bitburner v2.4.1 (216bf616)

I'm sort of surprised this hasn't been found out by now.

If you wrap a nuke in a try statement it seems to still succeed on gaining root access to servers that you don't have the required hacking level for. I don't know if it still required the requisite number of ports or not. I wont be able to test that till next run, since when I was < 300 managed to root every single server, with all 5 ports open.

My script the did it.
`/** @param {NS} ns */
export async function main(ns) {
    ns.run('get-servers.js');
    await ns.sleep(100);
    let servers = ns.read('serversall.txt').split(',');
    servers.forEach((s) => {
        if (ns.fileExists('brutessh.exe')) {ns.brutessh(s);}
        if (ns.fileExists('ftpcrack.exe')) {ns.ftpcrack(s);}
        if (ns.fileExists('httpworm.exe')) { ns.httpworm(s);}
        if (ns.fileExists('sqlinject.exe')) { ns.sqlinject(s);}
        if (ns.fileExists('relaysmtp.exe')) { ns.relaysmtp(s);}
        try {ns.nuke(s);} 
        catch { }
    });
}`

**Comment by Caldwell-74** [comment]
thats a feature not a bug :3
you just need enough ports open for nuke, the hack lvl doesnt matter
you dont even need the try catch if you check that enough ports are open

**Comment by RuntsTor** [comment]
@Caldwell-74 Fair enough. However the if check adds a whole 2GB of ram where the try catch is ram free.

**Comment by Caldwell-74** [comment]
its always a hot topic on the discord 
"bad style" (using try catch for logic) vs ease of use

**Comment by RuntsTor** [comment]
Well the try catch is really only an advantage if you would be checking to make sure something wont fail and crash the script. and really unless it's on something you're going to multi-thread that 2GB+ isn't really consequential
