### ISSUE TITLE
Bonus time is not shown on gangs or BitBurners unless there is some accumulated

### ISSUE THREAD

**Issue by ficocelliguy** [bitburner-official/bitburner-src#803]
If a user logs on once or twice a day for a few minutes to check on things, they will not make much progress with some mechanics, because of the way Bonus Time is handled. Perhaps bonus time should stay on the screen on e.g. gang page for users to be able to read about even if the current amount is low?

Side note: the getBonusTime() method returns results betwee. 0 and 2 seconds all of the time, because of how gang ticks are handled. probably it should just return 0 in these cases?
https://discord.com/channels/415207508303544321/415213413745164318/1147819706275868753

**Comment by catloversg** [comment]
@d0sboots We can close this.

**Comment by d0sboots** [comment]
@catloversg I think I'm lacking the context on why this is fixed, or obsolete.

**Comment by catloversg** [comment]
@d0sboots I discussed it with @ficocelliguy on Discord (https://discord.com/channels/415207508303544321/459097632896188436/1236347075759964354). Based on the discussion there, I assume that the current situation is good, so there is no need to change anything.
