### ISSUE TITLE
ACHIEVEMENTS: Gains! achievement granted for going to university

### ISSUE THREAD

**Issue by VictorS** [bitburner-official/bitburner-src#804]
Gains! achievement granted for going to university.
Gains! description is "Workout at a gym"

Steps:
1. start new game
2. skip tutorial
3. click City - go to university
4. start Algos course
5. wait
6. receive Gains! achievement

version v2.4.1

[save.zip](https://github.com/bitburner-official/bitburner-src/files/12612152/save.zip)
![achievement_bug](https://github.com/bitburner-official/bitburner-src/assets/176763/e97ab05a-1d8a-4397-bf4d-9cab4c71db0b)

**Comment by d0sboots** [comment]
There's a limit of 100 steam achievements, so I think we're being pretty picky about new achievements (saving then for new BNs etc.)
