### ISSUE TITLE
mass backdoor installation

### ISSUE THREAD

**Issue by RuntsTor** [bitburner-official/bitburner-src#811]
I don't know if this is a bug or a feature, but if  inside a script I do the following:

1. have an independent file that simply runs ns.singularity.installBackdoor(), on a passed string.
2. Make a list of target servers to install backdoors on.
3. Create a Path in an array to that target server from the closest server that already has a backdoor installed.
4. Move through that array using ns.singularity.connect() to hop server connections. (installing backdoors along the way. on any target servers. 
5. launch the backdoor installation as an independent process with ns.run() and use a short ns.sleep() to add a brief delay.

I do not have to wait for the backdoor installation to finish before I move to the next target server and launch a backdoor process for that.

I'm not sure if this is a bug or a feature because if I'm manually running backdoor in the console I have to cancel the backdoor install with ctrl+c  to use the terminal before it's done, similar to manual hack grow or weaken.

- [ ] Version of the game, e.g. Bitburner v2.4.1 (216bf616)

**Comment by d0sboots** [comment]
> launch the backdoor installation as an independent process with ns.run() and use a short ns.sleep() to add a brief delay.

That "brief delay" is letting the backdoor finish in time. If you took it out, then what you're doing wouldn't work. It *is* possible to backdoor every server simultaneously, but you need to have enough RAM to run all the backdoors at the same time. (In much the same way as you can run multiple hacks at the same time by using multiple processes.)

**Comment by RuntsTor** [comment]
> > launch the backdoor installation as an independent process with ns.run() and use a short ns.sleep() to add a brief delay.
> 
> That "brief delay" is letting the backdoor finish in time. If you took it out, then what you're doing wouldn't work. It _is_ possible to backdoor every server simultaneously, but you need to have enough RAM to run all the backdoors at the same time. (In much the same way as you can run multiple hacks at the same time by using multiple processes.)

@d0sboots  Except that's not the case. When I say brief I mean about 500 ms, and they are not finishing in time. Otherwise I wouldn't end up with **a dozen or more 'backdoor.js' running as active scripts, and have all the servers they were targeting now have active backdoors once they finish.**

From what it's sounding like, defiantly bug not feature. applying backdoors this way is like applying hack or grow through a script. If you did it manual you would have to wait till it finishes. But if you hack/grow in a series of scripts you run multiple at once. installing backdoors in the fashion I describe is working the same way.

**Comment by d0sboots** [comment]
Looks like you deleted this comment, but:

> But if you hack/grow in a series of scripts you run multiple at once. installing backdoors in the fashion I describe is working the same way.

Yes, exactly. Running multiple scripts at the same time allows you to do multiple actions simultaneously, if you have sufficient RAM. This is very much an intended game mechanic.
