### ISSUE TITLE
Documentation Website Needs To Be Updated

### ISSUE THREAD

**Issue by Youssef-Beltagy** [bitburner-official/bitburner-src#824]
# Documentation Website Needs To Be Updated

If you search for bitburner documentation, this website is usually at the top of the list:  https://bitburner.readthedocs.io/en/latest/

But it is using this archived and deprecated repository: https://github.com/danielyxie/bitburner/tree/master

Can you please change the website to point to this (the new) repository? So users can get the latest documentation easily and without getting confused.

Right now, the website has a lot of broken links and missing data which can be dissuading for a new player.

**Comment by d0sboots** [comment]
This is the result of moving to in-game documentation, but not having addressed all the clean-up tasks with that yet. We're moving away from using readthedocs in favor of using markdown directly, but I'm not sure if the top-level navigation pages exist yet, and if they do readthedocs should be redirected to point to them.
