### ISSUE TITLE
Bladeburner auto level not updated on time

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#831]
It's probably just cosmetics, but maybe level update could be a little better/faster:

![2023-09-26 09_29_30-BUG](https://github.com/bitburner-official/bitburner-src/assets/20597249/cc3311fe-0a1c-447e-b3f5-7bb57650ec2d)

After a while the level was correct again.

I know it's so minor, even not a problem, but I saw it and couldn't stop myself to report it, sorry ;)

**Comment by myCatsName** [comment]
Even at high successes, the tooltip should re-render on the same frame as the successes. I'm able to test and watch them work in sync from 0, and starting around the same level and successes as what you shared. 

I _thought_ the tooltip stuck one time, but when I reviewed my screenshot, it seems fine. I'll keep looking at this and I'm sure you don't need to say sorry for reporting, AssenD !

**Comment by Snarling** [comment]
Could not reproduce issue
