### ISSUE TITLE
Bladeburner error in returned chances

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#832]
@myCatsName 
When (estimate) population is 0.000 (chaos was ~200.00) and continue with operations (Sting),
 the chances (for all operations and contracts) looked like this:

![2023-09-27 14_13_35-BUG](https://github.com/bitburner-official/bitburner-src/assets/20597249/5bb2f91a-b330-4726-afa4-b9786e094511)

and the operation fail even with ~240B stamina.

The BlackOps were even stranger:
![2023-09-27 14_20_54-BUG](https://github.com/bitburner-official/bitburner-src/assets/20597249/915d456a-a1c7-45b6-9e42-b6a7b787d310)

After several Field Analysis in a row, all returned to normal.

**Comment by myCatsName** [comment]
@Caldwell-74 I think has this fixed with PR #761

**Comment by AssenD** [comment]
@myCatsName 
Yes, it's seems so, I'll close it as duplicate. 
Waiting for the patch, though :)
