### ISSUE TITLE
Bug while infiltrating VitaLife

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#84]
[WiseMack]
### Environment

* Error: Error: Trying to do infiltration on invalid location.
* Page: Infiltration
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=es-419 cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
[RECOVERY_BITBURNER_1656124055.zip](https://github.com/danielyxie/bitburner/files/8983734/RECOVERY_BITBURNER_1656124055.zip)

### Script
https://pastebin.com/7DuFYDpJ

###Target
VitaLife

**Comments From Original Issue**

[WiseMack]
> Two possible causes
> - If a script attempts to change location while infiltrating.
> - If a script tries to soft reset while infiltrating.
> 
> Not sure which.
> 
> ###
> Using 
> https://github.com/alainbryden/bitburner-scripts

**Comment by Snarling** [comment]
Still need to test the two proposed issue cases:
* If a script attempts to change location while infiltrating.
* If a script tries to soft reset while infiltrating.
