### ISSUE TITLE
Faction Augments screen does not update with current reputation value

### ISSUE THREAD

**Issue by ezrajrice** [bitburner-official/bitburner-src#843]
Version: Bitburner v2.4.1 (de5ebc993)

Augment purchase screen doesn't update with the current Faction Reputation value. I have to back out and then go back in for the "Buy" option to recognize that I have enough rep.

Steps:
- Start gaining rep for any faction
- Go into that faction's "Augments" screen
- Notice that the Reputation value does not increase while in this screen
- Back out to "Factions" screen
- Notice that the faction's reputation is increasing on this screen

**Comment by Snarling** [comment]
This was fixed by #744
