### ISSUE TITLE
Shadows of Anarchy sending spam

### ISSUE THREAD

**Issue by RangerRioter** [bitburner-official/bitburner-src#846]
As far as I've tried, every time I complete an Infiltration, Shadows of Anarchy asks if I want to join, even though I've already joined.
I've tried both moving to another city, and closing/restarting the game, I still receive the faction invitation.
I just loaded the game for the first time in a few months,  but I'm using the most recent patch (v2.5).

GitHub didn't accept the .json save file, so I had to rename it as a .txt, sorry.
[bitburnerSave_1696380350_BN1x2.txt](https://github.com/bitburner-official/bitburner-src/files/12798225/bitburnerSave_1696380350_BN1x2.txt)

**Comment by Snarling** [comment]
Fixed by 3007f0b which was included in a hotfix. Thanks for the report!
