### ISSUE TITLE
ns.singularity.destroyW0r1dD43m0n allow completetion before installing The Red Pill

### ISSUE THREAD

**Issue by TheAimMan** [bitburner-official/bitburner-src#854]
when calling `ns.singularity.destroyW0r1dD43m0n` the code in 'Singularity.ts' that checks requirements for that function is below

```
 const hackingRequirements = () => {
        if (Player.skills.hacking < wd.requiredHackingSkill) return false;
        if (!wd.hasAdminRights) return false;
        return true;
      };
```
      
It is only checking to see if the player has enough hacking skill to backdoor the server and if the server has been nuked.  The Red Pill is not needed to nuke a server, so all the player needs is a high enough hacking skill to destroy the bitnode.  The admin rights check should be changed to checking if the player has The Red Pill installed.

**Comment by d0sboots** [comment]
You can't (or shouldn't be able to) interact with W0r1dD43m0n before you have The Red Pill. If you can, that's the true bug.

Edit: What I mean by that is that there's no opportunity to get admin rights.

**Comment by jjclark1982** [comment]
I agree, it seems like the root cause is that port-opening netscript functions can succeed even when there is no network path to the target.

One approach would be to check for network connectivity in all 5 port-opening functions:

```js
    if (server.serversOnNetwork.length === 0)) {
      helpers.log(ctx, () => "No network path to this server.");
      return false;
    }
```

**Comment by TheAimMan** [comment]
Submitted https://github.com/bitburner-official/bitburner-src/pull/855 to fix
