### ISSUE TITLE
Mismatched promotion requirements for IT Job and Software Job

### ISSUE THREAD

**Issue by cigarmemr** [bitburner-official/bitburner-src#856]
Step to reproduce:
1. Apply for IT Job for a mega-company.
2. Repeat promotion until certain Job Title is obtained.
3. Check the hint of promotion requirements.

Result:
  Hint shows the basic applying requirements of IT Job:
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/ce8ced63-1ec3-414f-b1db-687f5d319f8a)

  However the actual requirements are shown in the hint of Software Job:
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/d919f032-95ee-43eb-ab86-837efa5909bd)
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/e9a87611-d1cc-429f-82f7-2fe1b1fd4702)

Version: Bitburner v2.5.0 (b87b8b4be)

**Comment by Sphyxis** [comment]
After Head of Engineering, it changes from it's current job type to a software job.
