### ISSUE TITLE
Provide custom keybinding interface for keyboard shortcuts

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#86]
[ilkecan]
After https://github.com/danielyxie/bitburner/pull/3605, [keyboard shortcuts](https://bitburner.readthedocs.io/en/latest/shortcuts.html) don't work as expected when the physical keyboard and the keyboard layout is different (e.g. dvorak layout on qwerty keyboard).

https://github.com/danielyxie/bitburner/blob/6f017bf4f60cbe264556456c69450d7a160856fd/src/Sidebar/ui/SidebarRoot.tsx#L275-L324
I am not sure how to handle this. Maybe another option could be added to choose between `event.code` (physical) and `event.key` (layout)?

**Comment by Snarling** [comment]
Not sure if this issue is still relevant, but there were downsides to both event.code and event.key. The only way to provide good user experience for all is custom keybinding interface.

**Comment by Snarling** [comment]
Related issue #420 which will remain open and this one will be closed.
