### ISSUE TITLE
Bitnode AugmentationMoneyCost not applying to Augments

### ISSUE THREAD

**Issue by gekotrav** [bitburner-official/bitburner-src#863]
Version = v2.5.0
BitNode = 12.10
SF11 = 0

Issue:
Expected BitNodeMulti for AugmentationMoneyCost = 121.899% per the stats page and ns.getBitNodeMultipliers()
Results instead returning 100%

SourceCode:
1. getBaseAugmentationPriceMultiplier = CONSTANTS.MultipleAugMultiplier * [1, 0.96, 0.94, 0.93][Player.sourceFileLvl(11)];
2. getGenericAugmentationPriceMultiplier = Math.pow(getBaseAugmentationPriceMultiplier, Player.queuedAugmentations.length);
3. moneyCost = aug.baseCost * getGenericAugmentationPriceMultiplier() * currentNodeMults.AugmentationMoneyCost;

Testing:
While testing I calculated BasePrice and worked through the above source code.
In the Augment screen my price multi says: Price multiplier: x 714.209k
So GenPriceMulti is correct and BaseCost is correct leaving BitnodeMult as the difference.
Dividing the Calculated cost and the Function returned cost I am showing 1 for the Function instead of 1.219
I have not tested this in any other SF yet so possible only an issue for the infinite node

Script Test Results:
scripts/purchaseAugments.js: sf11Lvl:0
scripts/purchaseAugments.js: AugmentPurchaseCount:21
scripts/purchaseAugments.js: basePriceMultiplier:1.9
scripts/purchaseAugments.js: sf11Muli:1
scripts/purchaseAugments.js: baseMultiplier:1.9
scripts/purchaseAugments.js: GenPriceMulti:714209.4956933726
scripts/purchaseAugments.js: BitAugMulti:1.219
scripts/purchaseAugments.js: BasePrice:TestBasePriceGet:457.123m | TestBasePriceCalc:457.123m | Difference:0.000
scripts/purchaseAugments.js: Cost:TestPriceGet:326.482t | TestPriceCalc:397.979t | Difference:-71.498t
scripts/purchaseAugments.js: NoBase:TestPriceGet:714.209k | TestPriceCalc:870.617k | Difference:-156.408k
_**scripts/purchaseAugments.js: BitMult:TestPriceGet:1.000 | TestPriceCalc:1.219 | Difference:-0.219**_

**Comment by TheAimMan** [comment]
I'm not seeing an issue.  I launched 2 instances.  1 in BN1 and the other in BN12.10
Have 21 augs lined up to install.
Left is BN1, right is BN12.10

![image](https://github.com/bitburner-official/bitburner-src/assets/147098375/0bce35cb-4910-454d-bc75-2163893b9855)

The difference in price is 124.337

**Comment by gekotrav** [comment]
There was a flaw in my logic. Getting baseCost already has the node calc in it.
getAugmentationBasePrice = aug.baseCost * currentNodeMults.AugmentationMoneyCost
