### ISSUE TITLE
Corporation: player is incentivised to skip morale / energy and interns

### ISSUE THREAD

**Issue by BanovMiroslav** [bitburner-official/bitburner-src#877]
**Version**: 2.5

**Edit**: ignore all of this. This is badly misunderstood math on my part.

> The way that morale / energy works right now. Up to 8 employees, it trends up no matter what and will become 100%. At 9 employees+, it starts being affected by interns. Then when autobrew and autoparty get developed, it is maxed.
> 
> But if you look at the formulas, at 2 interns out of 9, there is zero difference compared to 0 / 9. This holds true regardless of employees number. 4 / 18 interns give you zero improvement to energy / morale. Even if half are interns, it is still trending down on average, you need 2 out of 3 employees to be interns to have this trend up on average. That's too many. The other benefit of interns is experience growth, but that's of dubious value as well. So the effective way to deal with this is to script party / brew. Then for the brew you need to spend half a mil per employee every 10 cycles, so if you have 9 employees in 6 cities, that's 27 mil every 100 seconds. I think for party you can do it cheaper, let's say 100k per employee every 10 cycles. So in total 32.4mil. And having more employees is also not always good because of diminishing returns for a lot of positions, market saturation and other hassles. That's very true for the Agricultural sector which is the recommended start. So really the incentive is to not go higher than 8 employees, then buy autobrew + autoparty, and maybe then we can go higher in employee number.
> 
> I guess we want to buff interns and make the morale / energy game harder to avoid completely, it should be reasonable to deal with using interns, but not optimal. I would make it so at 4 employees at the latest (and maybe even at employee 1), you would need to start doing something about morale / energy.

**Comment by Caldwell-74** [comment]
i cant confirm that there is 0 difference between 0 out of 9 and 2 out of 9
Math.pow(1 + 0.002 * Math.min(1 / 9, 0 / 9 - 1 / 9) * 9,10) = 0.9801790433519494
Math.pow(1 + 0.002 * Math.min(1 / 9, 1 / 9 - 1 / 9) * 9,10) = 1
Math.pow(1 + 0.002 * Math.min(1 / 9, 2 / 9 - 1 / 9) * 9,10) = 1.0201809633680774

0 out of 9 adds another drain factor to it
1 out of 9 is what you need to not get an extra drain factor 
1 out of 9 + 1 to get an uptick through interns if that is an uptick overall depends if you are in debt and or make profit?

the drain/intern is to make the whole thing more interactive way way before there was only a drain if you where in debt and made no profit
interns are also intendet to be the "manual player" solution giving up 1 out of 9 of your employees is not great in the long run
the goal is to get players to script it, thats still a investment at an inefficient corp but an efficient corp wont be hurt by the cost to keep these up

**Comment by BanovMiroslav** [comment]
I think I was misreading this badly. I mistook Math.min for Math.max, and I guess I didn't consider the 9 multiplier as well. I am closing this one.

One other thing I am confused about is the marketCycles. It probably doesn't matter, but I thought it is 1 based on [Corporation.ts](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Corporation/Corporation.ts#L108) and you gave 10 here.

**Comment by BanovMiroslav** [comment]
At 2+ out of 9 you get mult 1.002
At 3 out of 18 you get mult 1.001
At 1 out of 9 you get mult 1
At 0 out of 9 you get mult 0.998

then you have
 (1 - 0.002 * Math.random()) * mult
 
 Assuming math random is always 0.5, you get almost stability at 3 out of 18:
 0.999 * 1.001 = 0,999999

Bottom line is at 2 out of 9 you get the original trend up situation (assuming not in debt), same as you had at below 9 employees. So it is reasonable, but suboptimal, just as intended.

**Comment by Caldwell-74** [comment]
yeah got confused with the gameCycles there but in the end doesnt change that much
