### ISSUE TITLE
Accessibility: Support disabling animation of "corrupted text" effect

### ISSUE THREAD

**Issue by jjclark1982** [bitburner-official/bitburner-src#892]
The game "Disable text effects" setting and the system "prefers reduced motion" setting don't do anything to make `<CorruptedText>` less distracting.

**Comment by Caldwell-74** [comment]
https://github.com/bitburner-official/bitburner-src/blob/dev/src/ui/MD/a.tsx#L7
disable text effect could be added here at the end in the condition

for prefers reduced motion not sure if it should behave the same as disable text effect or have a new/different CorruptedText effect

**Comment by Hoekstraa** [comment]
We could maybe use a subset of random weird unicode characters to make it look corrupted in a static way.
