### ISSUE TITLE
Bladeburner Populations should have a base growth number along with percentage growth

### ISSUE THREAD

**Issue by TheAimMan** [bitburner-official/bitburner-src#896]
Current random events in BladeBurner only grow a cities population by a percentage of its current population.  This creates the possibility for a player to completely eradicate a city, causing the growth to never increase again.

While in fits the nature of the game and the objective behind the entire Blade Burner lore, its not an enjoyable game mechanic to kill all the synths and be stuck with no way to progress.

**Comment by Sphyxis** [comment]
Proposed fix in my PR #897
