### ISSUE TITLE
ns.getPlayer().location returns a Company instead of a City

### ISSUE THREAD

**Issue by ValdarXY** [bitburner-official/bitburner-src#917]
minimal script printCurrentCity.js:

> /** @param {NS} ns */
> export async function main(ns) {
> 	ns.print(ns.getPlayer().location);
> 	ns.singularity.travelToCity("Aevum");
> 	ns.print(ns.getPlayer().location);
> }

run printCurrentCity.js --tail prints:

> Clarke Incorporated
> singularity.travelToCity: Traveled to Aevum
> Clarke Incorporated
> Script finished running

I'd expect it to print **Aevum** instead of **Clarke Incorporated**

Version: Bitburner 2.5.0 (b87b8b4be)

**Comment by trambelus** [comment]
You might want to check `ns.getPlayer().city` for info on the player's current city.

**Comment by ValdarXY** [comment]
I just noticed that too...

**Comment by d0sboots** [comment]
We could use better documentation on the meaning of those fields, though.
