### ISSUE TITLE
Server stuck at $0 money available

### ISSUE THREAD

**Issue by Frenoss** [bitburner-official/bitburner-src#923]
grow() at large amounts of available money should cap safely at the server's max amount. grow() at zero available should increase the money available to a non-zero amount.

I ran 5,000 threads of grow() targeting global-pharm. It had been gaining money available. Eventually, it gained 0%. I figured it was at max money available. I ran hack() and received $0. I looked at the server, and it showed no money available. Eventually some hack() returned money, and grow() started reporting that it was increasing the amount on the server again. Since then, however, my queries of the money available show nothing. grow() reports amazing results, in the billions of times if I read the output correctly, probably something related to a near-zero amount comparison.

Image showing grow() results and current server money at 0.
https://1drv.ms/i/s!AgESo09i_nifiIolfKR_4J1QwvkgVg?e=RP2aAN

Save file in this state.
https://1drv.ms/u/s!AgESo09i_nifiIokLsW3kRjOF68tYw?e=nxY0BY

I don't know how easily this can reproduce. It's the first time I've run scripts at this scale.

**Comment by d0sboots** [comment]
As your tests themselves have shown, `grow()` caps at max money and is capable of adding money to a server at $0. If your server is stuck at 0, it's because your scripts keep hacking away the available money (which is a pretty easy thing to do by accident).
