### ISSUE TITLE
No Karma information available

### ISSUE THREAD

**Issue by Schlumpf** [bitburner-official/bitburner-src#931]
Bitburner v2.5.0 (b87b8b4be)

----

The only mention of "karma" is at the tooltip of the "Create Gang" button. It tells me, that I need -54000 karma to unlock. But there is no information about players current karma level anywhere. This should be displayed at Stats page and should be accessible through the Player interface (https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.player.md).
And at the Gang documentation should use the term "karma" in the "Starting and Recruiting" section to make the topic more clear.

**Comment by Caldwell-74** [comment]
there is an intentionally  undocumented function to get the karma
ns.heart.break()

**Comment by Kelenius** [comment]
`ns.singularity.getCrimeStats().karma` also returns crime karma.

**Comment by TheAimMan** [comment]
While I'm aware that it was intentionally hidden.. was there a reason why?

**Comment by Caldwell-74** [comment]
thats before my time would have to ask hydro most likely 
if he doesnt know then its lost in time

**Comment by cigarmemr** [comment]
On the contrary, I think a more implicit message on the button would be better, more immersive like "You are not evil enough for now / You yet stand too far away from darkness. Try to do something really bad"

**Comment by TheAimMan** [comment]
IMO, at this point, it should probably just be documented.  Seeing that its tied to an entire mechanic, I don't see the point in hiding it.  Anyone that has completed BN2 will be asking about how to create a gang outside of BN2, which just leads to this api call being spread far and wide.

**Comment by cigarmemr** [comment]
Fair enough. For the current situation, the chain that guides the player what to do indeed breaks at some point:
1. I want to create a gang -> It says I need more karma. Good.
2. I want more karma -> The only `karma` I can find is in `CrimeStats`. Good, I will do more crime.
3. **How tf do I know my current karma?**
4. I got `heart.break()`. Good.

Guess that most players will be stuck in 3 for some time until they get aid from outside the game, or do they accidentally tried `Object.keys(ns)`.
To fill the gap, either to make 1 and 2 more implicit or to make 4 more explicit is an option.
An idea I come up with now is padding this text on the Create Gang button tipbox: "Touch your own `heart` in NetScript to know where you are" lol
