### ISSUE TITLE
ns.gang.nextUpdate() is documented, but doesn't work

### ISSUE THREAD

**Issue by scmbradley** [bitburner-official/bitburner-src#935]
The documentation includes reference to a `nextUpdate` function for the gang mechanic. However, it doesn't appear in the autocomplete options in the editor, and it doesn't appear to work: I get `ns.gang.nextUpdate` is not a function.

- [x] Version of the game: Bitburner v2.5.0 (b87b8b4be)

**Comment by scmbradley** [comment]
I'm in bitnode 2, not sure if that's relevant.

**Comment by d0sboots** [comment]
When you say "the documentation," what precisely are you referring to? The exact link and/or method you got there.

(The reason being that `nextUpdate` is indeed not in the game yet, it will be added in the next release. The bug here is what led you to docs for the in-development version.)

**Comment by scmbradley** [comment]
This page: https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.gang.md is what you get to if you click Documentation at the bottom of the editor window, and navigate to the gang interface. (Click `Gang` in the Type column of the properties at the top of that page).

**Comment by Caldwell-74** [comment]
yeah the problem here is that the editor points to the dev branch not the stable
nextUpdate did not yet find its way to stable
