### ISSUE TITLE
Scrolling up while running backdoor is impossible

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#94]
[kotenok2000]

When i run backdoor on n00dles and scroll up terminal resets down when progress bar moves.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game:1.7.0

**Comment by Snarling** [comment]
The progress bar needs to be moved into its own React element, which can then be periodically rerendered and should make the Terminal itself no longer need to rerender every time the progress bar updates.

**Comment by Draco18s** [comment]
Doesn't affect just backdoor, any of the command line "awaitable" functions have this issue.
