### ISSUE TITLE
Expose maxClearanceLevel on InfiltrationLocation interface

### ISSUE THREAD

**Issue by draughtyan** [bitburner-official/bitburner-src#942]
Would be cool information to add to getInfiltration().

**Comment by cigarmemr** [comment]
Agreed. I see there are two properties `startingSecurityLevel` and `maxClearanceLevel` in `location.infiltrationData`. No clue why they are not in the interface.

**Comment by catloversg** [comment]
@d0sboots Do you think we should expose `location.infiltrationData` in `getInfiltration()`?

**Comment by d0sboots** [comment]
I don't have any opinion about this specifically, but my default feeling is "everything should be exposed unless there's a compelling reason not to."
