### ISSUE TITLE
Last 3 sleeves are less effective

### ISSUE THREAD

**Issue by hollowleviathan** [bitburner-official/bitburner-src#955]
Sleeves 6, 7 , and 8 are slightly less effective than the other sleeves. You can easily reproduce this by starting a new node on an account with 8 sleeves and watching the Shock go down slower for them, or assign all sleeves to the same crime* and the success chance will be lower for the last three sleeves despite identical stats.

```
export function main(ns) {
  for (var iter = 0; iter < ns.sleeve.getNumSleeves(); ++iter) {
    ns.sleeve.setToCommitCrime(iter, "Mug");
  }
}
```

This is on v2.5.0 (b87b8b4be)

**Comment by Kelenius** [comment]
Could it be because you bought them later and so they have less intelligence?

**Comment by hollowleviathan** [comment]
Sleeves have a hidden Intelligence stat as well?

Yes, I see the intelligence stat via ns.sleeve.getSleeve(). Well, that explains it.

**Comment by hollowleviathan** [comment]
Perhaps Sleeves should display their intelligence stat if the player has Source-File 5?

**Comment by Snarling** [comment]
> Perhaps Sleeves should display their intelligence stat if the player has Source-File 5?

@hollowleviathan Added via #1030
