### ISSUE TITLE
Sleeves nerfed to death

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#96]
[Herzfinsternis]
Bitburner v2.0.1 (a8bef50e)

Sleeves are now earning much less experience. Workout at Powerhouse Gym with 84.395 shock gives only 1.115 experience per second. When the player does workout, the sleeves earn nothing. It is now much faster to commit crimes to gain experience. Heck, even working for factions gives them more exp. The changelog does not mention anything about this, so I guess, it is a bug.

**Comments From Original Issue**

[smeehrrr]
> +1 on this one, this is pretty brutal.

[borisflagell]
> Actually, the sleeve/workout interaction works fine. A shockless sleeve gain as much xp as a player. And mults are properly applied.
> (Workout xp gain's rate, as a whole, may be skewed though. But that's another issue)
> 
> 
> ~~Crime/Sleeve interaction is  the bugged one: xp multipliers and crime money mults are not getting applied.~~ (FIXED in DEV)
> 
> 
> Sleeves never gained experience when player did. Sleeves only gain xp from other sleeves. => No issue there.
> 
> ___________
> 
> I've reviewed sleeve's xp gains compared to previous version. (and fixed some little bug)
> 
> Currently (in the dev branch), all Sleeve's work give _at least_ as much xp as before.
> Faction work _does_ give way more than before. Which make it kind of awkward. 
> 
> But right now, Sleeve are in a mostly bug free state. And by no means less powerful than before. (especially now that Z.O.E works properly :D)
> 
> ==> IMHO, that issue can be closed.

**Comment by Snarling** [comment]
No longer an issue per existing comments
