### ISSUE TITLE
Able to nuke servers when my hacking level is below required skill

### ISSUE THREAD

**Issue by Cryosonic** [bitburner-official/bitburner-src#964]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
[bitburnerSave_1701897487_BN1x1.json](https://github.com/bitburner-official/bitburner-src/files/13591697/bitburnerSave_1701897487_BN1x1.json)
- [ ] Minimal scripts to reproduce the issue
as long as you have programs, created or bought, to open ports, you can run scripts to open the ports then nuke the server via script.
- [ ] Steps to reproduce
refer to attached save export, I have access to the-hub, and omega-net with hacklevel 190
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
Bitburner v2.5.1 (0c2997d32)

**Comment by d0sboots** [comment]
This is not a bug, but rather a rather confusing part of the game. `hack` is controlled by hacking level, but port openers and nuke are not.
