### ISSUE TITLE
Number of augs required to join Daedalus revealed by rumor system differs from fl1ght

### ISSUE THREAD

**Issue by cigarmemr** [bitburner-official/bitburner-src#979]
### Description
Aside from fl1ght.exe, the rumor system introduced another way to check the requirements of joining Daedalus.
However the "Number of Augmentations" stays as default 30 in those Bitnodes which was originally requiring another special number, namely BN6/7/12.

### Steps to reproduce
1. Enter BN6/7/12 and gear up to reach the requirements of joining Daedalus.
(Tested in BN6, should be the same in 7 or 12)
2. Run fl1ght.exe to trace the progress.
3. Check the rumors of Daedalus.
4. Install/graft 30 augs.

### Result
fl1ght.exe says we need to install 35 augs for joining Daedalus:
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/afd63eaa-359b-4efb-9dce-a7968d736b42)
This is consistent with the BitNode Multipliers: 
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/e31d48dd-f8a2-4d38-adf1-46a40eeb4153)

Rumor says otherwise:
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/c2da33af-2100-4123-9361-c04b97b571c0)

The player receive invitation from Daedalus when 30 augs are installed, rather than 35.

### Game version
Bitburner v2.5.1 (0c2997d32)

**Comment by jjclark1982** [comment]
This should be fixed by #953
