### ISSUE TITLE
inGang returns: function(){return a.BM.checkEnvFlags(o),a.BM.updateDynamicRam(o,(0,r.By)(e)),i(...arguments)}

### ISSUE THREAD

**Issue by ccheath** [bitburner-official/bitburner-src#981]
in BN2 
creating a simple script for gang management
starting with checking if I'm in a gang.

```
/** @param {NS} ns **/
export async function main(ns) {
  ns.tprint(ns.gang.inGang)
}
```

the output on the terminal is this:
```
[home /]> run test.js 
Running script with 1 thread(s), pid 525936 and args: [].
test.js: function(){return a.BM.checkEnvFlags(o),a.BM.updateDynamicRam(o,(0,r.By)(e)),i(...arguments)}
```
I'm in a gang (black hand) and have recruited 3 members

save file attached [bitburnerSave_1702842961_BN2x1.json](https://github.com/bitburner-official/bitburner-src/files/13697594/bitburnerSave_1702842961_BN2x1.json)
v2.5.1 (oc2997d32)

**Comment by d0sboots** [comment]
`ns.gang.inGang` is a function, so you want to call the function (`ns.gang.inGang()`). Instead, you printed the value of the function, which results in its source code.

**Comment by ccheath** [comment]
thanks for that, not sure why I didn't notice that... geez :facepalm:
