### ISSUE TITLE
Show Multipliers in Stats calculated for current bitnode

### ISSUE THREAD

**Issue by Jona898** [bitburner-official/bitburner-src#986]
Bitnodes have sometimes different start Values.
Is it possible to include these start values into the shown stat multiplier?

Like integrating
![image](https://github.com/bitburner-official/bitburner-src/assets/67005918/e865cd2e-04f6-482c-9734-4c4c695d1d25)
Into
![image](https://github.com/bitburner-official/bitburner-src/assets/67005918/91e525f1-c0da-4119-a762-fb763d426631)

**Comment by d0sboots** [comment]
It shows once you are in or beat BN5.
