### ISSUE TITLE
Can't buy anything after buying first CSEC augmentation

### ISSUE THREAD

**Issue by Asthonishia** [bitburner-official/bitburner-src#991]
I just bought the first CSEC augmentation and now, after game restart, i can't buy any hacknet servers and on the augmentations screen, available amounts are not checked.
It's like my money wasn't taken into account.

- Version of the game : Bitburner v2.5.1

![image](https://github.com/bitburner-official/bitburner-src/assets/20857256/cf144851-b0c2-46e6-849e-9f38281326d7)
![image](https://github.com/bitburner-official/bitburner-src/assets/20857256/53cb816f-9451-4036-b6f5-e0408d6d20da)

**Comment by cigarmemr** [comment]
Is it because of that you've depleted all cashes and cannot afford anything which requires money?
Money may fall below 0 when earning them a little and spending them a lot on university studying / gym training. Try doing something profitable to fill your wallet may fix this.

**Comment by Snarling** [comment]
The only way I know of to get negative player funds is by performing university or gym training. If you were doing this during a period of offline play and didn't have a lot of money to start with, it's not surprising that you are now negative in money.

If you believe you went negative for a reason other than university/gym, then we can keep this issue open but will need more info.

**Comment by cigarmemr** [comment]
> The only way I know of to get negative player funds is by performing university or gym training. If you were doing this during a period of offline play and didn't have a lot of money to start with, it's not surprising that you are now negative in money.
> 
> If you believe you went negative for a reason other than university/gym, then we can keep this issue open but will need more info.

As I see sleeves travelling through NetScripts may also result in negative funds, dunno if it is intended or not.

**Comment by d0sboots** [comment]
> As I see sleeves travelling through NetScripts may also result in negative funds, dunno if it is intended or not.

I'm not sure if that one was intended, but I wouldn't say it's a bug either. It's certainly supposed to cost money, and it's up for debate if it should fail when you have none.

**Comment by HiEv** [comment]
Just to be clear, you have _negative_ money.  That's why you can't buy anything.

**Comment by cigarmemr** [comment]
> I'm not sure if that one was intended, but I wouldn't say it's a bug either. It's certainly supposed to cost money, and it's up for debate if it should fail when you have none.

Agreed. The doc of `travel()` says it will return `false` if fails, but [there](https://github.com/bitburner-official/bitburner-src/blob/dev/src/PersonObjects/Sleeve/Sleeve.ts#L257-L263) seems to be no case for that
```javascript
  /** Travel to another City. Costs money from player */
  travel(newCity: CityName): boolean {
    Player.loseMoney(CONSTANTS.TravelCost, "sleeves");
    this.city = newCity;

    return true;
  }
```

**Comment by steven-r** [comment]
Based on the discussion above, the actual 'bug' is in the documentation, as there is no `false` response. Maybe we should rename the issue then to reflect the actual problem.

Another point: Based on the response from @d0sboots above: Who decides on game semantics? If there's an unclear behavior ('I'm not sure if that one was intended'), does an issue need some kind of escalation or board to decide, to keep the gameplay consistent?

**Comment by d0sboots** [comment]
There's no formal policy: we sort of chew on it and maybe come to a consensus. Ultimately @Snarling has the final say as the maintainer.

**Comment by cigarmemr** [comment]
For the sleeves travelling issue, I think the solution should be one of the following:
- Add checks to `travel()` similar to `travelToCity()` [here](https://github.com/bitburner-official/bitburner-src/blob/dev/src/NetscriptFunctions/Singularity.ts#L390) before actually setting `this.city`:
```javascript
          if (Player.money < CONSTANTS.TravelCost) {
            helpers.log(ctx, () => "Not enough money to travel.");
            return false;
          }
```
- Leave the function to be capable of overdrawing. Rewrite `travel()` and corresponding doc to return void instead of boolean.

The former seems to be more sensible.

**Comment by steven-r** [comment]
> The former seems to be more sensible.

... and AFAIR this is consistent with the UI. The player cannot travel without any money, so why should a sleeve be allowed to?

**Comment by Snarling** [comment]
Yeah with the player not being able to travel without adequate funds, I agree that it's more consistent to apply that to sleeves as well.

**Comment by TheAimMan** [comment]
Fixing Travel on Sleeves will make it much harder to get the debt achievement.
AFAIK Travel with Sleeve's and Courses/Gym are the only way a player can go into debt.

**Comment by GDennis** [comment]
I went into debt with market code before. Selling a market position costs the transaction fee, but if the gain is less than the transaction fee you'll build up debt. Just sell only 1 share per transaction and you'll build up debt quickly.
Btw. if the debt is too large, then a soft reset / install augmentations can be a good option.

**Comment by gmcew** [comment]
I can't change the title, but to summarise: Sleeves should not be able to travel with inadequate funds, as that would then be consistent with player behaviour. The debt achievement can still be gained through other means, though they may be slower.
