### ISSUE TITLE
Documentation page of List of Factions and their Requirements messed up by HTML labels

### ISSUE THREAD

**Issue by cigarmemr** [bitburner-official/bitburner-src#993]
There are HTML labels glitching in List of Factions and their Requirements documentation page:

![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/38469bbb-1943-473a-b9d8-022568685c6a)

### Version
Bitburner v2.5.2 (c6141f2ad)

**Comment by Unrecognized10** [comment]
I wanted to report it earlier and yeah the code was a bit messy

**Comment by Unrecognized10** [comment]
https://github.com/bitburner-official/bitburner-src/blob/dev/src/Documentation/doc/index.md The files here are fine, there is no damage, but why are the files here damaged?
