### ISSUE TITLE
`getResetInfo` timestamps are incorrect at the start of the game

### ISSUE THREAD

**Issue by ZachHaber** [bitburner-official/bitburner-src#997]
At the start of the game, I'd expect the `lastAugReset` and `lastNodeReset` to be set to the timestamp of when you started the save file, rather than -1. After you augment the first time, `lastAugReset` gets set, but `lastNodeReset` stays at -1.

Version: v2.5.2 (c6141f2ad)

Reproduce: 
1. Start a new game
2. run `ns.tprint(ns.getResetInfo())`
3. Be confused that the `lastAugReset` and `lastNodeReset` timestamps are -1

**Comment by steven-r** [comment]
The information is displayed correctly in the stats window, and therefore this seems to be an API issue only.

**Comment by catloversg** [comment]
@d0sboots Do you think this is a bug? `-1` looks like a reasonable default value for `lastAugReset` and `lastNodeReset`.

> The information is displayed correctly in the stats window, and therefore this seems to be an API issue only.

@steven-r The information in the stats window are `playtimeSinceLastAug` and `playtimeSinceLastBitnode`.

**Comment by d0sboots** [comment]
Seems like a bug to me, the start of play seems like the more correct value.
