### ISSUE TITLE
Location names in the new Job Info page mess up with each other when their servers are backdoored

### ISSUE THREAD

**Issue by cigarmemr** [bitburner-official/bitburner-src#998]
### Step to reproduce
1. Apply job for two locations with different length of name (say Ecorp and Fulcrum Technologies)
2. Backdoor their server.
3. Check the Job page and switch to Fulcrum Technologies
4. Use Previous Job or Next Job to switch to Ecorp

### Result
The shuffled string for Fulcrum Technologies still lingers after switch to Ecorp
![image](https://github.com/bitburner-official/bitburner-src/assets/26317456/aa52c66c-5223-4c52-ac76-78820af0f3ed)

### Version
Bitburner v2.5.2 (c6141f2ad)

**Comment by ramou** [comment]
I noted that job names and availability also seem to get borked in what I believe is a related (or even the same) issue.

**Comment by Schlumpf** [comment]
If you apply for 2 jobs, the requirements for position are mixed, too. If you switch between jobs, you can apply for positions without having enough reputation. The reputation from the other company seems to be used.
