### ISSUE TITLE
Docs page for Faction Requirements doesn't currently use number formatting options

### ISSUE THREAD

**Issue by ramou** [bitburner-official/bitburner-src#999]
Given #995 and #996 I figured this was a natural step as it looks like these are already getting processed as more than just strings. At the same time, it's getting used as markdown  so the whole <Money money={2e7} /> might be problematic unless the md files are procedurally generated somewhere.

- v2.5.2
![image](https://github.com/bitburner-official/bitburner-src/assets/1812288/47c4b628-bddd-45c1-b4ec-50cbb3b9a87f)

**Comment by catloversg** [comment]
I don't think we will do that. In order to format the number, we need to "mark" the specific value (`$15m`, `$20m`) with a "marker" and process that marker in the TS code. However, we also need to keep the markdown files "clean" (no weird custom "marker"), so they can be rendered properly on GitHub.

@Snarling @d0sboots What are your opinions?

**Comment by ramou** [comment]
Having thought about it for a while, a solid solution is, as you say, to leave it separate most of the times. The other successful solution I've seen effectively has a central file that is marked up to support all usages, then either on compile/run/ --or likely in this case as it's used as part of the CI process-- generate the MD and/or other files. Still, while a neat practice, it adds a complex step for what is, while inconsistent, small potatoes.

**Comment by catloversg** [comment]
It's too complicated for very little gain. To summarize the "theoretical" solution:
- Leave the markdown files as-is, so GitHub can render it properly.
- Create a central file that contains markers for all special usages.
- Read that central file and process it with whatever method that we can use.
- Render the special markers when we process the markdown files in TS code.

This is too complicated, and it only renders things for in-game documentation. Players will not see them when they read the documentation on GitHub web UI. To be honest, I'm against this idea (implement workaround just to format numbers in markdown files).

**Comment by catloversg** [comment]
It's too complicated for very little gain. To summarize the "theoretical" solution:
- Leave the markdown files as-is, so GitHub can render them properly.
- Create a central file that contains markers for all special usages.
- Read that central file and process it with whatever method we can use.
- Render the special markers when we process the markdown files in TS code.

This is too complicated, and it only renders things for in-game documentation. Players will not see them when they read the documentation on GitHub web UI. To be honest, I'm against this idea (implement a workaround just to format numbers in markdown files).

**Comment by d0sboots** [comment]
Yeah, I'm going to mark this as "won't fix" for the reasons given. It's a neat idea, but the amount of effort exceeds the gain here.
